-- Data for table: budget_friendly_alternatives
-- Generated: 2025-12-02T20:45:31.015Z

INSERT INTO budget_friendly_alternatives (id, affordable_brand_product_id, alternative_name, alternative_cost_euros, cost_savings_euros, effectiveness_comparison, alternative_source, best_for_budget_tier, notes, created_at) VALUES (1, 1, 'Foam Roller + Tennis Ball', '30.00', '50.00', '0.80', 'DIY_Combination', 'minimal_500', '80% effectiveness for 38% of the cost - great for beginners', '2025-08-18T20:28:03.231Z');
INSERT INTO budget_friendly_alternatives (id, affordable_brand_product_id, alternative_name, alternative_cost_euros, cost_savings_euros, effectiveness_comparison, alternative_source, best_for_budget_tier, notes, created_at) VALUES (2, 1, 'Basic Massage Gun', '40.00', '40.00', '0.75', 'Generic_Brand', 'minimal_500', '75% effectiveness for 50% of the cost - good budget option', '2025-08-18T20:28:03.231Z');
INSERT INTO budget_friendly_alternatives (id, affordable_brand_product_id, alternative_name, alternative_cost_euros, cost_savings_euros, effectiveness_comparison, alternative_source, best_for_budget_tier, notes, created_at) VALUES (3, 2, 'Resistance Bands + Manual Techniques', '40.00', '75.00', '0.70', 'DIY_Combination', 'minimal_500', '70% effectiveness for 35% of the cost - manual work but effective', '2025-08-18T20:28:03.231Z');
INSERT INTO budget_friendly_alternatives (id, affordable_brand_product_id, alternative_name, alternative_cost_euros, cost_savings_euros, effectiveness_comparison, alternative_source, best_for_budget_tier, notes, created_at) VALUES (4, 2, 'Mid-Range Massage Gun', '60.00', '55.00', '0.80', 'Generic_Brand', 'moderate_1000', '80% effectiveness for 52% of the cost - good compromise', '2025-08-18T20:28:03.231Z');
INSERT INTO budget_friendly_alternatives (id, affordable_brand_product_id, alternative_name, alternative_cost_euros, cost_savings_euros, effectiveness_comparison, alternative_source, best_for_budget_tier, notes, created_at) VALUES (5, 4, 'DIY Agility Course + Stopwatch', '25.00', '275.00', '0.75', 'DIY_Alternative', 'minimal_500', '75% effectiveness for 8% of the cost - massive savings', '2025-08-18T20:28:03.231Z');
INSERT INTO budget_friendly_alternatives (id, affordable_brand_product_id, alternative_name, alternative_cost_euros, cost_savings_euros, effectiveness_comparison, alternative_source, best_for_budget_tier, notes, created_at) VALUES (6, 4, 'Basic Agility Equipment', '80.00', '220.00', '0.85', 'Generic_Brand', 'moderate_1000', '85% effectiveness for 27% of the cost - good value', '2025-08-18T20:28:03.231Z');
INSERT INTO budget_friendly_alternatives (id, affordable_brand_product_id, alternative_name, alternative_cost_euros, cost_savings_euros, effectiveness_comparison, alternative_source, best_for_budget_tier, notes, created_at) VALUES (7, 6, 'Resistance Training + Bodyweight', '0.00', '200.00', '0.80', 'DIY_Alternative', 'minimal_500', '80% effectiveness for 0% of the cost - completely free', '2025-08-18T20:28:03.231Z');
INSERT INTO budget_friendly_alternatives (id, affordable_brand_product_id, alternative_name, alternative_cost_euros, cost_savings_euros, effectiveness_comparison, alternative_source, best_for_budget_tier, notes, created_at) VALUES (8, 6, 'Basic Recovery Tools', '100.00', '100.00', '0.70', 'DIY_Combination', 'moderate_1000', '70% effectiveness for 50% of the cost - good alternative', '2025-08-18T20:28:03.231Z');
