-- Data for table: sprint_workouts
-- Generated: 2025-12-02T20:45:34.782Z

INSERT INTO sprint_workouts (id, category_id, phase_id, name, distance_yards, intensity_percentage, rest_duration_seconds, sets, reps_per_set, recovery_between_sets_seconds, surface_type, gradient_percentage, coaching_cues, elite_application_notes, created_at) VALUES (1, 1, 2, '3-Point Start Power Development', 10, 95, 180, 3, 6, 300, 'grass', NULL, '["Drive phase forward lean","High knee frequency","Pump arms aggressively"]', 'Target: Sub-1.60s 10-yard split for elite flag football acceleration', '2025-08-17T16:48:27.838Z');
INSERT INTO sprint_workouts (id, category_id, phase_id, name, distance_yards, intensity_percentage, rest_duration_seconds, sets, reps_per_set, recovery_between_sets_seconds, surface_type, gradient_percentage, coaching_cues, elite_application_notes, created_at) VALUES (2, 1, 2, 'Resisted Sprint Acceleration', 15, 90, 120, 4, 4, 240, 'turf', NULL, '["Maintain forward lean","Short powerful steps","Drive through resistance"]', 'Sled training method used by Jamaican sprinters', '2025-08-17T16:48:27.893Z');
INSERT INTO sprint_workouts (id, category_id, phase_id, name, distance_yards, intensity_percentage, rest_duration_seconds, sets, reps_per_set, recovery_between_sets_seconds, surface_type, gradient_percentage, coaching_cues, elite_application_notes, created_at) VALUES (3, 2, 1, 'Power Hill Sprints', 15, 85, 120, 2, 8, 480, 'hill', 10, '["High knee drive","Pump arms powerfully","Maintain speed rhythm"]', 'Builds power for 4.6s 40-yard dash capability', '2025-08-17T16:48:27.943Z');
INSERT INTO sprint_workouts (id, category_id, phase_id, name, distance_yards, intensity_percentage, rest_duration_seconds, sets, reps_per_set, recovery_between_sets_seconds, surface_type, gradient_percentage, coaching_cues, elite_application_notes, created_at) VALUES (4, 2, 1, 'Long Hill Base Building', 40, 75, 180, 3, 6, 360, 'hill', 8, '["Steady rhythm","Relaxed shoulders","Controlled breathing"]', 'Early season conditioning used in Jamaica training camps', '2025-08-17T16:48:27.997Z');
INSERT INTO sprint_workouts (id, category_id, phase_id, name, distance_yards, intensity_percentage, rest_duration_seconds, sets, reps_per_set, recovery_between_sets_seconds, surface_type, gradient_percentage, coaching_cues, elite_application_notes, created_at) VALUES (5, 3, 3, 'Special Endurance I (Flag Football)', 25, 95, 45, 4, 4, 180, 'grass', NULL, '["Maintain sprint form","Fight fatigue","Strong finish"]', 'Game-specific conditioning for maintaining 4.6-4.8s speed', '2025-08-17T16:48:28.047Z');
INSERT INTO sprint_workouts (id, category_id, phase_id, name, distance_yards, intensity_percentage, rest_duration_seconds, sets, reps_per_set, recovery_between_sets_seconds, surface_type, gradient_percentage, coaching_cues, elite_application_notes, created_at) VALUES (6, 3, 3, 'Game Simulation Repeats', 15, 98, 10, 6, 6, 120, 'turf', NULL, '["Quick recovery","Explosive restart","Mental toughness"]', 'Mimics flag football play frequency and intensity', '2025-08-17T16:48:28.125Z');
INSERT INTO sprint_workouts (id, category_id, phase_id, name, distance_yards, intensity_percentage, rest_duration_seconds, sets, reps_per_set, recovery_between_sets_seconds, surface_type, gradient_percentage, coaching_cues, elite_application_notes, created_at) VALUES (7, 1, 2, '3-Point Start Power Development', 10, 95, 180, 3, 6, 300, 'grass', NULL, '["Drive phase forward lean","High knee frequency","Pump arms aggressively"]', 'Target: Sub-1.60s 10-yard split for elite flag football acceleration', '2025-08-17T16:49:01.421Z');
INSERT INTO sprint_workouts (id, category_id, phase_id, name, distance_yards, intensity_percentage, rest_duration_seconds, sets, reps_per_set, recovery_between_sets_seconds, surface_type, gradient_percentage, coaching_cues, elite_application_notes, created_at) VALUES (8, 2, 1, 'Power Hill Sprints', 15, 85, 120, 2, 8, 480, 'hill', 10, '["High knee drive","Pump arms powerfully","Maintain speed rhythm"]', 'Builds power for 4.6s 40-yard dash capability', '2025-08-17T16:49:01.471Z');
