-- Data for table: success_indicators
-- Generated: 2025-12-02T20:45:32.021Z

INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (1, 'Sleep Duration', 'Average nightly sleep duration in hours', 'sleep', '8.00', 'hours', NULL, NULL, '10.00', 'daily', 'Smart ring/watch', 'Smart-ring export data analysis', 'critical', 'active', '2025-08-18T20:02:01.310Z', '2025-08-18T20:02:01.310Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (2, 'HRV Improvement', 'Heart rate variability improvement percentage', 'sleep', '10.00', 'percent', NULL, NULL, '10.00', 'daily', 'Smart ring/watch', 'Smart-ring export data analysis', 'critical', 'active', '2025-08-18T20:02:01.310Z', '2025-08-18T20:02:01.310Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (3, 'Urine Color', 'Hydration status based on urine color (1-8 scale)', 'hydration', '3.00', 'scale', NULL, NULL, '0.00', 'daily', 'Hydration color chart', 'Game-day weigh-in and urine analysis', 'critical', 'active', '2025-08-18T20:02:01.310Z', '2025-08-18T20:02:01.310Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (4, 'Body Mass Loss', 'Maximum body mass loss during training', 'hydration', '2.00', 'percent', NULL, NULL, '0.00', 'daily', 'Digital scale', 'Game-day weigh-in protocol', 'critical', 'active', '2025-08-18T20:02:01.310Z', '2025-08-18T20:02:01.310Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (5, 'Injury Days Missed', 'Days missed due to injuries per 100 athlete-days', 'injuries', '5.00', 'days', NULL, NULL, '-20.00', 'monthly', 'Physio log', 'Physio log analysis and reporting', 'high', 'active', '2025-08-18T20:02:01.310Z', '2025-08-18T20:02:01.310Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (6, 'Flying 10m Sprint', 'Sprint speed improvement after 12 weeks', 'sprint_speed', '3.00', 'percent', NULL, NULL, '3.00', 'quarterly', 'Timing gates/GPS', 'Timing gates or GPS measurement', 'high', 'active', '2025-08-18T20:02:01.310Z', '2025-08-18T20:02:01.310Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (7, 'Passing Completion', 'Team passing completion rate improvement', 'team_chemistry', '6.00', 'percent', NULL, NULL, '6.00', 'weekly', 'Stat sheet', 'Game statistics analysis', 'medium', 'active', '2025-08-18T20:02:01.310Z', '2025-08-18T20:02:01.310Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (8, 'Drop Count Reduction', 'Reduction in dropped passes', 'team_chemistry', '10.00', 'percent', NULL, NULL, '10.00', 'weekly', 'Stat sheet', 'Game statistics analysis', 'medium', 'active', '2025-08-18T20:02:01.310Z', '2025-08-18T20:02:01.310Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (9, 'Stroop Accuracy', 'Cognitive response accuracy improvement', 'cognitive', '5.00', 'percent', NULL, NULL, '5.00', 'weekly', 'App analytics', 'Cognitive training app data', 'medium', 'active', '2025-08-18T20:02:01.310Z', '2025-08-18T20:02:01.310Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (10, 'Reaction Time', 'Cognitive response time improvement', 'cognitive', '8.00', 'percent', NULL, NULL, '8.00', 'weekly', 'App analytics', 'Cognitive training app data', 'medium', 'active', '2025-08-18T20:02:01.310Z', '2025-08-18T20:02:01.310Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (11, 'Sleep Duration', 'Average nightly sleep duration in hours', 'sleep', '8.00', 'hours', NULL, NULL, '10.00', 'daily', 'Smart ring/watch', 'Smart-ring export data analysis', 'critical', 'active', '2025-08-18T20:02:58.835Z', '2025-08-18T20:02:58.835Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (12, 'HRV Improvement', 'Heart rate variability improvement percentage', 'sleep', '10.00', 'percent', NULL, NULL, '10.00', 'daily', 'Smart ring/watch', 'Smart-ring export data analysis', 'critical', 'active', '2025-08-18T20:02:58.835Z', '2025-08-18T20:02:58.835Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (13, 'Urine Color', 'Hydration status based on urine color (1-8 scale)', 'hydration', '3.00', 'scale', NULL, NULL, '0.00', 'daily', 'Hydration color chart', 'Game-day weigh-in and urine analysis', 'critical', 'active', '2025-08-18T20:02:58.835Z', '2025-08-18T20:02:58.835Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (14, 'Body Mass Loss', 'Maximum body mass loss during training', 'hydration', '2.00', 'percent', NULL, NULL, '0.00', 'daily', 'Digital scale', 'Game-day weigh-in protocol', 'critical', 'active', '2025-08-18T20:02:58.835Z', '2025-08-18T20:02:58.835Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (15, 'Injury Days Missed', 'Days missed due to injuries per 100 athlete-days', 'injuries', '5.00', 'days', NULL, NULL, '-20.00', 'monthly', 'Physio log', 'Physio log analysis and reporting', 'high', 'active', '2025-08-18T20:02:58.835Z', '2025-08-18T20:02:58.835Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (16, 'Flying 10m Sprint', 'Sprint speed improvement after 12 weeks', 'sprint_speed', '3.00', 'percent', NULL, NULL, '3.00', 'quarterly', 'Timing gates/GPS', 'Timing gates or GPS measurement', 'high', 'active', '2025-08-18T20:02:58.835Z', '2025-08-18T20:02:58.835Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (17, 'Passing Completion', 'Team passing completion rate improvement', 'team_chemistry', '6.00', 'percent', NULL, NULL, '6.00', 'weekly', 'Stat sheet', 'Game statistics analysis', 'medium', 'active', '2025-08-18T20:02:58.835Z', '2025-08-18T20:02:58.835Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (18, 'Drop Count Reduction', 'Reduction in dropped passes', 'team_chemistry', '10.00', 'percent', NULL, NULL, '10.00', 'weekly', 'Stat sheet', 'Game statistics analysis', 'medium', 'active', '2025-08-18T20:02:58.835Z', '2025-08-18T20:02:58.835Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (19, 'Stroop Accuracy', 'Cognitive response accuracy improvement', 'cognitive', '5.00', 'percent', NULL, NULL, '5.00', 'weekly', 'App analytics', 'Cognitive training app data', 'medium', 'active', '2025-08-18T20:02:58.835Z', '2025-08-18T20:02:58.835Z');
INSERT INTO success_indicators (id, indicator_name, indicator_description, indicator_domain, target_value, target_unit, baseline_value, current_value, improvement_target_percentage, measurement_frequency, measurement_tool, verification_method, priority_level, indicator_status, created_at, updated_at) VALUES (20, 'Reaction Time', 'Cognitive response time improvement', 'cognitive', '8.00', 'percent', NULL, NULL, '8.00', 'weekly', 'App analytics', 'Cognitive training app data', 'medium', 'active', '2025-08-18T20:02:58.835Z', '2025-08-18T20:02:58.835Z');
