-- FlagFit Pro Database Backup
-- Table: research_topics
-- Backup Date: 2025-12-29
-- Records: 15

INSERT INTO research_topics (id, topic_name, display_name, description, parent_topic_id, pubmed_query, europe_pmc_query, keywords, mesh_terms, relevance_to_flag_football, icon_name, color_hex, sort_order, is_active, created_at)
VALUES
  ('b5a90e67-832b-483e-8d81-ee63500c1c9a', 'sprinting', 'Sprint Performance', 'Research on sprint mechanics, acceleration, and maximum velocity development', NULL, '(sprint[Title/Abstract] OR sprinting[Title/Abstract]) AND (performance OR training OR mechanics) OR ("Australian Institute of Sport"[Affiliation] AND sprint)', 'sprint AND (performance OR training OR mechanics) OR (AFF:"Australian Institute of Sport" AND sprint)', '["sprint","acceleration","velocity","speed","AIS","Australian Institute of Sport"]', '["Running","Athletic Performance","Muscle Contraction"]', 'Critical for route running, pursuit, and breakaway speed in flag football', 'zap', '#FF6B35', 1, true, '2025-12-29 13:37:46.882646+00'),
  ('38a11885-ea60-423d-96a3-8a9b70f04a76', 'agility', 'Agility & Change of Direction', 'Research on agility, cutting mechanics, and reactive movement', NULL, '(agility[Title/Abstract] OR "change of direction"[Title/Abstract]) AND (training OR performance)', 'agility OR "change of direction" AND training', '["agility","cutting","COD","reactive agility"]', '["Physical Conditioning, Human","Athletic Performance"]', 'Essential for route running, defensive coverage, and flag pulling', 'refresh-cw', '#4ECDC4', 2, true, '2025-12-29 13:37:46.882646+00'),
  ('100eab89-236f-42c5-9dcf-bb78d26f5f99', 'plyometrics', 'Plyometric Training', 'Research on jump training, reactive strength, and power development', NULL, '(plyometric[Title/Abstract] OR "jump training"[Title/Abstract]) AND (performance OR power) OR ("Australian Institute of Sport"[Affiliation] AND plyometric)', 'plyometric OR "jump training" AND performance OR (AFF:"Australian Institute of Sport" AND plyometric)', '["plyometrics","jump","reactive strength","SSC","AIS","Australian Institute of Sport"]', '["Plyometric Exercise","Muscle Power"]', 'Develops explosive power for jumping catches and quick acceleration', 'trending-up', '#9B59B6', 3, true, '2025-12-29 13:37:46.882646+00'),
  ('2b3d27d9-2ce2-44a8-8c8d-915b6bf0231b', 'isometrics', 'Isometric Training', 'Research on isometric exercises, rate of force development, and strength', NULL, '(isometric[Title/Abstract]) AND (training OR strength OR "rate of force")', 'isometric AND (training OR strength)', '["isometric","RFD","static contraction","strength"]', '["Isometric Contraction","Muscle Strength"]', 'Builds foundational strength and injury resilience for contact situations', 'pause', '#3498DB', 4, true, '2025-12-29 13:37:46.882646+00'),
  ('b40c2a35-740b-47ad-9f66-69d2d29f1cb4', 'recovery', 'Recovery & Regeneration', 'Research on post-exercise recovery methods and adaptation', NULL, '(recovery[Title/Abstract]) AND (exercise OR training OR sport) AND (performance OR adaptation) OR ("Australian Institute of Sport"[Affiliation] AND recovery)', 'recovery AND exercise AND (performance OR adaptation) OR (AFF:"Australian Institute of Sport" AND recovery)', '["recovery","regeneration","adaptation","fatigue","AIS","Australian Institute of Sport"]', '["Recovery of Function","Exercise","Athletic Performance"]', 'Optimizes between-session recovery for practice and game performance', 'battery-charging', '#2ECC71', 5, true, '2025-12-29 13:37:46.882646+00'),
  ('3a89643d-ae24-4722-a56a-dbffca472f0b', 'sleep', 'Sleep & Performance', 'Research on sleep quality, duration, and athletic performance', NULL, '(sleep[Title/Abstract]) AND (athlete OR sport OR performance)', 'sleep AND (athlete OR sport OR performance)', '["sleep","circadian","rest","sleep quality"]', '["Sleep","Athletic Performance","Recovery of Function"]', 'Critical for cognitive function, reaction time, and physical recovery', 'moon', '#34495E', 6, true, '2025-12-29 13:37:46.882646+00'),
  ('30aedf0b-514b-4dcf-9826-e7a96a5b0040', 'muscle_fiber', 'Muscle Fiber Types', 'Research on fast/slow twitch fibers and fiber type adaptations', NULL, '("muscle fiber"[Title/Abstract] OR "fiber type"[Title/Abstract]) AND (training OR adaptation)', '"muscle fiber" OR "fiber type" AND training', '["type I","type II","fast twitch","slow twitch","fiber type"]', '["Muscle Fibers, Fast-Twitch","Muscle Fibers, Slow-Twitch"]', 'Understanding fiber types helps optimize training for speed vs endurance', 'activity', '#E74C3C', 7, true, '2025-12-29 13:37:46.882646+00'),
  ('b9a16a76-5388-4f58-831f-a9eb0b567a85', 'sports_psychology', 'Sports Psychology', 'Research on mental training, focus, and psychological performance', NULL, '("sports psychology"[Title/Abstract] OR "mental training"[Title/Abstract]) AND performance', '"sports psychology" OR "mental training" AND performance', '["mental training","focus","visualization","confidence"]', '["Sports","Psychology","Mental Processes"]', 'Enhances focus, confidence, and performance under pressure', 'brain', '#9B59B6', 8, true, '2025-12-29 13:37:46.882646+00'),
  ('b6c5daeb-80a3-40fd-a7da-083e1e34065f', 'sports_nutrition', 'Sports Nutrition', 'Research on nutrition strategies for athletic performance', NULL, '("sports nutrition"[Title/Abstract] OR "athlete nutrition"[Title/Abstract]) AND performance OR ("Australian Institute of Sport"[Affiliation] AND nutrition)', '"sports nutrition" OR "athlete nutrition" AND performance OR (AFF:"Australian Institute of Sport" AND nutrition)', '["nutrition","fueling","macronutrients","hydration","supplements","AIS","Australian Institute of Sport"]', '["Sports Nutritional Physiological Phenomena","Athletic Performance"]', 'Optimizes energy availability and recovery nutrition', 'utensils', '#F39C12', 9, true, '2025-12-29 13:37:46.882646+00'),
  ('4cedc684-ad7e-4d88-bc22-fd1f393a1e42', 'flag_football', 'Flag Football Research', 'Research specific to flag football and related sports', NULL, '("flag football"[Title/Abstract] OR "non-contact football"[Title/Abstract])', '"flag football" OR "non-contact football"', '["flag football","non-contact","recreational football"]', '["Football","Athletic Performance"]', 'Directly applicable research for flag football athletes', 'flag', '#E67E22', 10, true, '2025-12-29 13:37:46.882646+00'),
  ('782302a4-bc11-4d23-8baa-0c836f8b2984', 'ais_high_performance', 'AIS High Performance Science', 'Research from the Australian Institute of Sport on elite athlete development, periodization, and evidence-based training', NULL, '"Australian Institute of Sport"[Affiliation] AND (training OR performance OR athlete)', 'AFF:"Australian Institute of Sport" AND (training OR performance OR athlete)', '["AIS","Australian Institute of Sport","high performance","elite athlete","periodization","evidence-based"]', '["Athletic Performance","Sports","Physical Conditioning, Human"]', 'World-leading research on athlete development applicable to flag football training periodization', 'award', '#00843D', 11, true, '2025-12-29 13:42:34.487463+00'),
  ('54f94bbb-36fb-4cf4-94f3-3425f79864da', 'velocity_based_training', 'Velocity-Based Training', 'Research on velocity-based training methods for power and strength development', NULL, '("velocity based training"[Title/Abstract] OR "VBT"[Title/Abstract]) AND (strength OR power)', '"velocity based training" OR VBT AND (strength OR power)', '["VBT","velocity","bar speed","autoregulation","power output"]', '["Resistance Training","Muscle Strength","Athletic Performance"]', 'Optimizes power training for explosive movements in flag football', 'gauge', '#FF5722', 12, true, '2025-12-29 13:42:34.487463+00'),
  ('d2b40dd1-f77a-4345-8fa4-1474b9313043', 'supplement_evidence', 'Supplement Evidence (ABCD Framework)', 'Evidence-based supplement research using AIS ABCD classification system', NULL, '(supplement[Title/Abstract] AND athlete) AND (evidence OR efficacy OR performance) OR ("Australian Institute of Sport"[Affiliation] AND supplement)', 'supplement AND athlete AND (evidence OR efficacy) OR (AFF:"Australian Institute of Sport" AND supplement)', '["supplements","ergogenic aids","ABCD framework","Group A","caffeine","creatine","beta-alanine","AIS"]', '["Dietary Supplements","Athletic Performance","Sports Nutritional Physiological Phenomena"]', 'Evidence-based supplement protocols for flag football performance enhancement', 'pill', '#9C27B0', 13, true, '2025-12-29 13:42:34.487463+00'),
  ('fec00074-34e1-4fd7-9ff6-f0aece8836cd', 'acceleration_mechanics', 'Acceleration & Sprint Mechanics', 'Research on acceleration biomechanics, force application, and sprint technique', NULL, '(acceleration[Title/Abstract] AND sprint) AND (mechanics OR biomechanics OR force)', 'acceleration AND sprint AND (mechanics OR biomechanics OR force)', '["acceleration","sprint mechanics","force application","ground contact","horizontal force"]', '["Biomechanical Phenomena","Running","Athletic Performance"]', 'Critical for first-step quickness and route running in flag football', 'fast-forward', '#2196F3', 14, true, '2025-12-29 13:42:34.487463+00'),
  ('cfe4790f-16e9-45d7-9c73-dce21f211ad9', 'mental_performance', 'Mental Performance & Focus', 'Research on concentration, focus, visualization, and mental skills training', NULL, '("mental performance"[Title/Abstract] OR "mental skills"[Title/Abstract] OR visualization[Title/Abstract]) AND (athlete OR sport)', '"mental performance" OR "mental skills" OR visualization AND (athlete OR sport)', '["mental performance","focus","concentration","visualization","imagery","mindfulness"]', '["Mental Processes","Athletic Performance","Sports"]', 'Enhances game-day focus and decision-making under pressure', 'target', '#673AB7', 15, true, '2025-12-29 13:42:34.487463+00')
ON CONFLICT (id) DO UPDATE SET
  topic_name = EXCLUDED.topic_name,
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  pubmed_query = EXCLUDED.pubmed_query,
  europe_pmc_query = EXCLUDED.europe_pmc_query,
  keywords = EXCLUDED.keywords,
  mesh_terms = EXCLUDED.mesh_terms,
  relevance_to_flag_football = EXCLUDED.relevance_to_flag_football,
  icon_name = EXCLUDED.icon_name,
  color_hex = EXCLUDED.color_hex,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active;

