export default [
  {
    ignores: [
      "node_modules/**",
      "dist/**",
      "build/**",
      "angular/**",
      "*.min.js",
      "coverage/**",
      ".netlify/**",
    ],
  },
  {
    files: ["**/*.js", "**/*.jsx"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Node.js globals
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        module: "readonly",
        require: "readonly",
        exports: "readonly",
        global: "readonly",
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        // Browser APIs
        URL: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        File: "readonly",
        Blob: "readonly",
        atob: "readonly",
        btoa: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        CustomEvent: "readonly",
        StorageEvent: "readonly",
        Event: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        performance: "readonly",
        Node: "readonly",
        HTMLElement: "readonly",
        NodeFilter: "readonly",
        // Browser dialogs
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        // Browser objects
        screen: "readonly",
        location: "readonly",
        // Web Crypto API
        crypto: "readonly",
        SubtleCrypto: "readonly",
        // Third-party libraries (loaded via script tags)
        Chart: "readonly",
        lucide: "readonly",
        // Test globals
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        vi: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-console": "off",
      "no-undef": "error",
      "prefer-const": "warn",
      "no-var": "warn",
    },
  },
];
