#!/usr/bin/env node
/**
 * Generate env.js file with Supabase credentials from environment variables
 * This runs during the Netlify build process
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Get Supabase credentials from environment
const supabaseUrl =
  process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || "";
const supabaseAnonKey =
  process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY || "";

// Generate the env.js file
const envJsContent = `// Auto-generated by generate-env.js during build
// DO NOT EDIT THIS FILE MANUALLY
window._env = window._env || {};
window._env.SUPABASE_URL = '${supabaseUrl}';
window._env.SUPABASE_ANON_KEY = '${supabaseAnonKey}';

console.log('✅ Environment variables loaded:', {
  hasSupabaseUrl: !!window._env.SUPABASE_URL,
  hasSupabaseKey: !!window._env.SUPABASE_ANON_KEY
});
`;

// Write to file
const outputPath = path.join(__dirname, "env.js");
fs.writeFileSync(outputPath, envJsContent);

// eslint-disable-next-line no-console
console.log("✅ Generated env.js with Supabase credentials");
// eslint-disable-next-line no-console
console.log(`   URL: ${supabaseUrl ? "✓ Set" : "✗ Missing"}`);
// eslint-disable-next-line no-console
console.log(`   Key: ${supabaseAnonKey ? "✓ Set" : "✗ Missing"}`);
