#!/bin/bash

# Profile Save Fix - Verification Script
# This script helps verify that the profile save functionality is working correctly

echo "======================================================================"
echo "Profile Save Fix - Verification Script"
echo "======================================================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}STEP 1: Apply Database Migration${NC}"
echo "----------------------------------------------------------------------"
echo "Please apply the migration file manually in Supabase:"
echo ""
echo "1. Open Supabase Dashboard"
echo "2. Go to SQL Editor"
echo "3. Copy and run the contents of:"
echo "   database/migrations/112_fix_users_table_profile_fields.sql"
echo ""
echo "Press Enter after you've applied the migration..."
read

echo ""
echo -e "${YELLOW}STEP 2: Verify Database Schema${NC}"
echo "----------------------------------------------------------------------"
echo "Run this query in Supabase SQL Editor to verify columns were added:"
echo ""
echo "SELECT column_name, data_type, character_maximum_length"
echo "FROM information_schema.columns"
echo "WHERE table_schema = 'public'"
echo "  AND table_name = 'users'"
echo "  AND column_name IN ('full_name', 'jersey_number', 'phone', 'team', 'date_of_birth')"
echo "ORDER BY column_name;"
echo ""
echo "You should see 5 rows returned."
echo "Press Enter after verifying..."
read

echo ""
echo -e "${YELLOW}STEP 3: Restart Development Server${NC}"
echo "----------------------------------------------------------------------"
echo "If your Angular dev server is running, restart it to pick up code changes."
echo ""
echo "Press Enter after restarting..."
read

echo ""
echo -e "${YELLOW}STEP 4: Manual Testing Checklist${NC}"
echo "----------------------------------------------------------------------"
echo "Perform these tests in your browser:"
echo ""
echo "[ ] 1. Open the app and navigate to Settings"
echo "[ ] 2. Open Browser DevTools (F12) → Network tab"
echo "[ ] 3. Change profile information:"
echo "       - Display Name"
echo "       - Date of Birth"
echo "       - Position"
echo "       - Jersey Number"
echo "       - Phone Number"
echo "[ ] 4. Click 'Save Changes'"
echo "[ ] 5. Check Network tab:"
echo "       - Should see request to Supabase"
echo "       - Status should be 200 OK"
echo "[ ] 6. Check Console tab:"
echo "       - Should see: 'User profile saved successfully'"
echo "       - No error messages"
echo "[ ] 7. Check UI:"
echo "       - Should see green success toast"
echo "       - NOT an error message"
echo "[ ] 8. CRITICAL: Refresh page (F5)"
echo "[ ] 9. Verify changes persisted after refresh"
echo ""
echo "Press Enter after completing manual tests..."
read

echo ""
echo -e "${YELLOW}STEP 5: Verify in Database${NC}"
echo "----------------------------------------------------------------------"
echo "Run this query in Supabase to verify data was saved:"
echo ""
echo "SELECT"
echo "  id,"
echo "  full_name,"
echo "  jersey_number,"
echo "  phone,"
echo "  date_of_birth,"
echo "  position,"
echo "  created_at,"
echo "  updated_at"
echo "FROM public.users"
echo "WHERE email = 'YOUR_EMAIL_HERE'"  
echo "ORDER BY updated_at DESC"
echo "LIMIT 1;"
echo ""
echo "Verify:"
echo "  - full_name has your display name"
echo "  - jersey_number has your jersey number"
echo "  - phone has your phone number"
echo "  - date_of_birth has your birth date"
echo "  - position has your position"
echo "  - created_at is NOT recent (original registration date)"
echo "  - updated_at IS recent (when you saved)"
echo ""
echo "Press Enter after verifying database..."
read

echo ""
echo -e "${YELLOW}STEP 6: Test Error Handling${NC}"
echo "----------------------------------------------------------------------"
echo "To verify error handling works:"
echo ""
echo "1. In Supabase Dashboard → Database → Policies"
echo "2. Temporarily disable the 'Users can update own profile' policy"
echo "3. Try to save profile changes in the app"
echo "4. You should see an ERROR message (not success)"
echo "5. Re-enable the policy"
echo ""
echo "This confirms errors are no longer silently swallowed."
echo ""
echo "Press Enter after testing error handling..."
read

echo ""
echo "======================================================================"
echo -e "${GREEN}✅ Verification Complete!${NC}"
echo "======================================================================"
echo ""
echo "If all tests passed:"
echo "  - Profile changes now save to database ✅"
echo "  - Changes persist after page refresh ✅"
echo "  - created_at timestamp is preserved ✅"
echo "  - Errors are shown to user ✅"
echo ""
echo "Summary of changes:"
echo "  1. Added missing columns to database (full_name, jersey_number, phone)"
echo "  2. Fixed created_at overwrite bug"
echo "  3. Added proper error handling"
echo "  4. Aligned field names with database schema"
echo ""
echo -e "${GREEN}The profile save issue is now RESOLVED! 🎉${NC}"
echo ""
