/**
 * Country Options Constants
 *
 * Single source of truth for country dropdowns (settings, onboarding, etc.)
 * Use with roster-utils getCountryCode/getCountryFlag for display/validation.
 *
 * @example
 * import { COUNTRY_OPTIONS } from '@core/constants';
 * <p-select [options]="COUNTRY_OPTIONS" optionLabel="label" optionValue="value" />
 */

export interface CountryOption {
  label: string;
  value: string;
}

export const COUNTRY_OPTIONS: CountryOption[] = [
  { label: "🇺🇸 United States", value: "United States" },
  { label: "🇲🇽 Mexico", value: "Mexico" },
  { label: "🇨🇦 Canada", value: "Canada" },
  { label: "🇩🇪 Germany", value: "Germany" },
  { label: "🇦🇹 Austria", value: "Austria" },
  { label: "🇮🇹 Italy", value: "Italy" },
  { label: "🇫🇷 France", value: "France" },
  { label: "🇬🇧 United Kingdom", value: "United Kingdom" },
  { label: "🇪🇸 Spain", value: "Spain" },
  { label: "🇯🇵 Japan", value: "Japan" },
  { label: "🇧🇷 Brazil", value: "Brazil" },
  { label: "🇵🇱 Poland", value: "Poland" },
  { label: "🇸🇮 Slovenia", value: "Slovenia" },
  { label: "🇭🇷 Croatia", value: "Croatia" },
  { label: "🇷🇸 Serbia", value: "Serbia" },
  { label: "🇭🇺 Hungary", value: "Hungary" },
  { label: "🇨🇿 Czech Republic", value: "Czech Republic" },
  { label: "🇸🇰 Slovakia", value: "Slovakia" },
  { label: "🇩🇰 Denmark", value: "Denmark" },
  { label: "🇸🇪 Sweden", value: "Sweden" },
  { label: "🇳🇴 Norway", value: "Norway" },
  { label: "🇫🇮 Finland", value: "Finland" },
  { label: "🇳🇱 Netherlands", value: "Netherlands" },
  { label: "🇧🇪 Belgium", value: "Belgium" },
  { label: "🇨🇭 Switzerland", value: "Switzerland" },
  { label: "🇵🇹 Portugal", value: "Portugal" },
  { label: "🇬🇷 Greece", value: "Greece" },
  { label: "🇮🇱 Israel", value: "Israel" },
  { label: "🇦🇺 Australia", value: "Australia" },
  { label: "🇳🇿 New Zealand", value: "New Zealand" },
  { label: "🇰🇷 South Korea", value: "South Korea" },
  { label: "🇨🇳 China", value: "China" },
  { label: "🇵🇭 Philippines", value: "Philippines" },
  { label: "🇮🇳 India", value: "India" },
  { label: "🇦🇷 Argentina", value: "Argentina" },
  { label: "🇨🇴 Colombia", value: "Colombia" },
  { label: "🇵🇦 Panama", value: "Panama" },
  { label: "🇬🇹 Guatemala", value: "Guatemala" },
  { label: "🇨🇷 Costa Rica", value: "Costa Rica" },
  { label: "🇵🇷 Puerto Rico", value: "Puerto Rico" },
  { label: "🇦🇸 American Samoa", value: "American Samoa" },
  { label: "🇦🇫 Afghanistan", value: "Afghanistan" },
  { label: "🇦🇱 Albania", value: "Albania" },
  { label: "🇩🇿 Algeria", value: "Algeria" },
  { label: "🇦🇩 Andorra", value: "Andorra" },
  { label: "🇦🇴 Angola", value: "Angola" },
  { label: "🇦🇲 Armenia", value: "Armenia" },
  { label: "🇦🇿 Azerbaijan", value: "Azerbaijan" },
  { label: "🇧🇸 Bahamas", value: "Bahamas" },
  { label: "🇧🇭 Bahrain", value: "Bahrain" },
  { label: "🇧🇩 Bangladesh", value: "Bangladesh" },
  { label: "🇧🇧 Barbados", value: "Barbados" },
  { label: "🇧🇾 Belarus", value: "Belarus" },
  { label: "🇧🇿 Belize", value: "Belize" },
  { label: "🇧🇯 Benin", value: "Benin" },
  { label: "🇧🇹 Bhutan", value: "Bhutan" },
  { label: "🇧🇴 Bolivia", value: "Bolivia" },
  { label: "🇧🇦 Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  { label: "🇧🇼 Botswana", value: "Botswana" },
  { label: "🇧🇳 Brunei", value: "Brunei" },
  { label: "🇧🇬 Bulgaria", value: "Bulgaria" },
  { label: "🇧🇫 Burkina Faso", value: "Burkina Faso" },
  { label: "🇧🇮 Burundi", value: "Burundi" },
  { label: "🇰🇭 Cambodia", value: "Cambodia" },
  { label: "🇨🇲 Cameroon", value: "Cameroon" },
  { label: "🇨🇻 Cape Verde", value: "Cape Verde" },
  { label: "🇨🇫 Central African Republic", value: "Central African Republic" },
  { label: "🇹🇩 Chad", value: "Chad" },
  { label: "🇨🇱 Chile", value: "Chile" },
  { label: "🇨🇺 Cuba", value: "Cuba" },
  { label: "🇨🇾 Cyprus", value: "Cyprus" },
  { label: "🇨🇩 DR Congo", value: "DR Congo" },
  { label: "🇩🇯 Djibouti", value: "Djibouti" },
  { label: "🇩🇲 Dominica", value: "Dominica" },
  { label: "🇩🇴 Dominican Republic", value: "Dominican Republic" },
  { label: "🇪🇨 Ecuador", value: "Ecuador" },
  { label: "🇪🇬 Egypt", value: "Egypt" },
  { label: "🇸🇻 El Salvador", value: "El Salvador" },
  { label: "🇬🇶 Equatorial Guinea", value: "Equatorial Guinea" },
  { label: "🇪🇷 Eritrea", value: "Eritrea" },
  { label: "🇪🇪 Estonia", value: "Estonia" },
  { label: "🇸🇿 Eswatini", value: "Eswatini" },
  { label: "🇪🇹 Ethiopia", value: "Ethiopia" },
  { label: "🇫🇯 Fiji", value: "Fiji" },
  { label: "🇬🇦 Gabon", value: "Gabon" },
  { label: "🇬🇲 Gambia", value: "Gambia" },
  { label: "🇬🇪 Georgia", value: "Georgia" },
  { label: "🇬🇭 Ghana", value: "Ghana" },
  { label: "🇬🇩 Grenada", value: "Grenada" },
  { label: "🇬🇳 Guinea", value: "Guinea" },
  { label: "🇬🇼 Guinea-Bissau", value: "Guinea-Bissau" },
  { label: "🇬🇾 Guyana", value: "Guyana" },
  { label: "🇭🇹 Haiti", value: "Haiti" },
  { label: "🇭🇳 Honduras", value: "Honduras" },
  { label: "🇭🇰 Hong Kong", value: "Hong Kong" },
  { label: "🇮🇸 Iceland", value: "Iceland" },
  { label: "🇮🇩 Indonesia", value: "Indonesia" },
  { label: "🇮🇷 Iran", value: "Iran" },
  { label: "🇮🇶 Iraq", value: "Iraq" },
  { label: "🇮🇪 Ireland", value: "Ireland" },
  { label: "🇯🇲 Jamaica", value: "Jamaica" },
  { label: "🇯🇴 Jordan", value: "Jordan" },
  { label: "🇰🇿 Kazakhstan", value: "Kazakhstan" },
  { label: "🇰🇪 Kenya", value: "Kenya" },
  { label: "🇰🇮 Kiribati", value: "Kiribati" },
  { label: "🇽🇰 Kosovo", value: "Kosovo" },
  { label: "🇰🇼 Kuwait", value: "Kuwait" },
  { label: "🇰🇬 Kyrgyzstan", value: "Kyrgyzstan" },
  { label: "🇱🇦 Laos", value: "Laos" },
  { label: "🇱🇻 Latvia", value: "Latvia" },
  { label: "🇱🇧 Lebanon", value: "Lebanon" },
  { label: "🇱🇸 Lesotho", value: "Lesotho" },
  { label: "🇱🇷 Liberia", value: "Liberia" },
  { label: "🇱🇾 Libya", value: "Libya" },
  { label: "🇱🇮 Liechtenstein", value: "Liechtenstein" },
  { label: "🇱🇹 Lithuania", value: "Lithuania" },
  { label: "🇱🇺 Luxembourg", value: "Luxembourg" },
  { label: "🇲🇬 Madagascar", value: "Madagascar" },
  { label: "🇲🇼 Malawi", value: "Malawi" },
  { label: "🇲🇾 Malaysia", value: "Malaysia" },
  { label: "🇲🇻 Maldives", value: "Maldives" },
  { label: "🇲🇱 Mali", value: "Mali" },
  { label: "🇲🇹 Malta", value: "Malta" },
  { label: "🇲🇭 Marshall Islands", value: "Marshall Islands" },
  { label: "🇲🇷 Mauritania", value: "Mauritania" },
  { label: "🇲🇺 Mauritius", value: "Mauritius" },
  { label: "🇫🇲 Micronesia", value: "Micronesia" },
  { label: "🇲🇩 Moldova", value: "Moldova" },
  { label: "🇲🇨 Monaco", value: "Monaco" },
  { label: "🇲🇳 Mongolia", value: "Mongolia" },
  { label: "🇲🇪 Montenegro", value: "Montenegro" },
  { label: "🇲🇦 Morocco", value: "Morocco" },
  { label: "🇲🇿 Mozambique", value: "Mozambique" },
  { label: "🇲🇲 Myanmar", value: "Myanmar" },
  { label: "🇳🇦 Namibia", value: "Namibia" },
  { label: "🇳🇷 Nauru", value: "Nauru" },
  { label: "🇳🇵 Nepal", value: "Nepal" },
  { label: "🇳🇮 Nicaragua", value: "Nicaragua" },
  { label: "🇳🇪 Niger", value: "Niger" },
  { label: "🇳🇬 Nigeria", value: "Nigeria" },
  { label: "🇰🇵 North Korea", value: "North Korea" },
  { label: "🇲🇰 North Macedonia", value: "North Macedonia" },
  { label: "🇴🇲 Oman", value: "Oman" },
  { label: "🇵🇰 Pakistan", value: "Pakistan" },
  { label: "🇵🇼 Palau", value: "Palau" },
  { label: "🇵🇸 Palestine", value: "Palestine" },
  { label: "🇵🇬 Papua New Guinea", value: "Papua New Guinea" },
  { label: "🇵🇾 Paraguay", value: "Paraguay" },
  { label: "🇵🇪 Peru", value: "Peru" },
  { label: "🇶🇦 Qatar", value: "Qatar" },
  { label: "🇷🇴 Romania", value: "Romania" },
  { label: "🇷🇺 Russia", value: "Russia" },
  { label: "🇷🇼 Rwanda", value: "Rwanda" },
  { label: "🇰🇳 Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
  { label: "🇱🇨 Saint Lucia", value: "Saint Lucia" },
  {
    label: "🇻🇨 Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
  },
  { label: "🇼🇸 Samoa", value: "Samoa" },
  { label: "🇸🇲 San Marino", value: "San Marino" },
  { label: "🇸🇹 São Tomé and Príncipe", value: "São Tomé and Príncipe" },
  { label: "🇸🇦 Saudi Arabia", value: "Saudi Arabia" },
  { label: "🇸🇳 Senegal", value: "Senegal" },
  { label: "🇸🇨 Seychelles", value: "Seychelles" },
  { label: "🇸🇱 Sierra Leone", value: "Sierra Leone" },
  { label: "🇸🇬 Singapore", value: "Singapore" },
  { label: "🇸🇧 Solomon Islands", value: "Solomon Islands" },
  { label: "🇸🇴 Somalia", value: "Somalia" },
  { label: "🇿🇦 South Africa", value: "South Africa" },
  { label: "🇸🇸 South Sudan", value: "South Sudan" },
  { label: "🇱🇰 Sri Lanka", value: "Sri Lanka" },
  { label: "🇸🇩 Sudan", value: "Sudan" },
  { label: "🇸🇷 Suriname", value: "Suriname" },
  { label: "🇸🇾 Syria", value: "Syria" },
  { label: "🇹🇼 Taiwan", value: "Taiwan" },
  { label: "🇹🇯 Tajikistan", value: "Tajikistan" },
  { label: "🇹🇿 Tanzania", value: "Tanzania" },
  { label: "🇹🇭 Thailand", value: "Thailand" },
  { label: "🇹🇱 Timor-Leste", value: "Timor-Leste" },
  { label: "🇹🇬 Togo", value: "Togo" },
  { label: "🇹🇴 Tonga", value: "Tonga" },
  { label: "🇹🇹 Trinidad and Tobago", value: "Trinidad and Tobago" },
  { label: "🇹🇳 Tunisia", value: "Tunisia" },
  { label: "🇹🇷 Turkey", value: "Turkey" },
  { label: "🇹🇲 Turkmenistan", value: "Turkmenistan" },
  { label: "🇹🇻 Tuvalu", value: "Tuvalu" },
  { label: "🇺🇬 Uganda", value: "Uganda" },
  { label: "🇺🇦 Ukraine", value: "Ukraine" },
  { label: "🇦🇪 United Arab Emirates", value: "United Arab Emirates" },
  { label: "🇺🇾 Uruguay", value: "Uruguay" },
  { label: "🇺🇿 Uzbekistan", value: "Uzbekistan" },
  { label: "🇻🇺 Vanuatu", value: "Vanuatu" },
  { label: "🇻🇦 Vatican City", value: "Vatican City" },
  { label: "🇻🇪 Venezuela", value: "Venezuela" },
  { label: "🇻🇳 Vietnam", value: "Vietnam" },
  { label: "🇾🇪 Yemen", value: "Yemen" },
  { label: "🇿🇲 Zambia", value: "Zambia" },
  { label: "🇿🇼 Zimbabwe", value: "Zimbabwe" },
];

/**
 * Country name to ISO 3166-1 alpha-2 code mapping.
 * Used by getCountryCode/getCountryFlag for roster display.
 */
const COUNTRY_NAME_TO_CODE_MAP: Record<string, string> = {
  "United States": "US",
  "United Kingdom": "GB",
  Mexico: "MX",
  Canada: "CA",
  Germany: "DE",
  Austria: "AT",
  Italy: "IT",
  France: "FR",
  Spain: "ES",
  Japan: "JP",
  Brazil: "BR",
  Poland: "PL",
  Slovenia: "SI",
  Croatia: "HR",
  Serbia: "RS",
  Hungary: "HU",
  "Czech Republic": "CZ",
  Slovakia: "SK",
  Denmark: "DK",
  Sweden: "SE",
  Norway: "NO",
  Finland: "FI",
  Netherlands: "NL",
  Belgium: "BE",
  Switzerland: "CH",
  Portugal: "PT",
  Greece: "GR",
  Israel: "IL",
  Australia: "AU",
  "New Zealand": "NZ",
  "South Korea": "KR",
  China: "CN",
  Philippines: "PH",
  India: "IN",
  Argentina: "AR",
  Colombia: "CO",
  Panama: "PA",
  Guatemala: "GT",
  "Costa Rica": "CR",
  "Puerto Rico": "PR",
  "American Samoa": "AS",
  Afghanistan: "AF",
  Albania: "AL",
  Algeria: "DZ",
  Andorra: "AD",
  Angola: "AO",
  Ireland: "IE",
  Russia: "RU",
  Ukraine: "UA",
  Turkey: "TR",
  Romania: "RO",
  Bulgaria: "BG",
  "Bosnia and Herzegovina": "BA",
  Montenegro: "ME",
  "North Macedonia": "MK",
  Lithuania: "LT",
  Latvia: "LV",
  Estonia: "EE",
  Cyprus: "CY",
  Malta: "MT",
  Luxembourg: "LU",
  Iceland: "IS",
  Egypt: "EG",
  "South Africa": "ZA",
  Nigeria: "NG",
  Kenya: "KE",
  Morocco: "MA",
  Tunisia: "TN",
  Ghana: "GH",
  Senegal: "SN",
  "Ivory Coast": "CI",
  Cameroon: "CM",
  Tanzania: "TZ",
  Ethiopia: "ET",
  "United Arab Emirates": "AE",
  "Saudi Arabia": "SA",
  Qatar: "QA",
  Kuwait: "KW",
  Bahrain: "BH",
  Oman: "OM",
  Jordan: "JO",
  Lebanon: "LB",
  Singapore: "SG",
  Malaysia: "MY",
  Thailand: "TH",
  Indonesia: "ID",
  Vietnam: "VN",
  Taiwan: "TW",
  "Hong Kong": "HK",
  Chile: "CL",
  Peru: "PE",
  Ecuador: "EC",
  Venezuela: "VE",
  Bolivia: "BO",
  Paraguay: "PY",
  Uruguay: "UY",
  "Dominican Republic": "DO",
  Jamaica: "JM",
  "Trinidad and Tobago": "TT",
  Bahamas: "BS",
  Barbados: "BB",
  Cuba: "CU",
  Haiti: "HT",
  Honduras: "HN",
  "El Salvador": "SV",
  Nicaragua: "NI",
  Belize: "BZ",
};

export function getCountryCode(countryName: string): string {
  if (!countryName) return "";
  if (countryName.length === 2 && countryName === countryName.toUpperCase()) {
    return countryName;
  }
  return COUNTRY_NAME_TO_CODE_MAP[countryName] ?? "";
}

export function getCountryFlag(country: string): string {
  if (!country || country === "Unknown") return "🏳️";
  let countryCode = country;
  if (country.length > 2) {
    countryCode = getCountryCode(country);
  }
  if (!countryCode || countryCode.length !== 2) return "🏳️";
  const codePoints = countryCode
    .toUpperCase()
    .split("")
    .map((char) => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}
