/**
 * Instagram Video Data
 *
 * Curated Instagram video and creator constant arrays extracted from
 * InstagramVideoService to keep the service file focused on logic.
 *
 * @see instagram-video.service.ts
 */

import type { InstagramVideo, InstagramCreator } from "./instagram-video.service";

// ============================================================================
// CURATED INSTAGRAM CONTENT DATABASE
// ============================================================================

export const CURATED_INSTAGRAM_VIDEOS: InstagramVideo[] = [
  // REAL INSTAGRAM TRAINING VIDEOS - JANUARY 2026
  // ============================================================================
  {
    id: "ig_real_001",
    shortcode: "DRCVdnCEbvG",
    title: "Quick Release Footwork Drill",
    description:
      "Pro QB demonstrates the 3-step drop with quick release mechanics. Perfect for flag football where pocket time is minimal.",
    url: "https://www.instagram.com/reel/DRCVdnCEbvG/",
    embedUrl: "https://www.instagram.com/reel/DRCVdnCEbvG/embed/",
    creator: {
      username: "flag_football_athlete",
      displayName: "Flag Football Athlete",
      profileUrl: "https://www.instagram.com/flag_football_athlete/",
      verified: false,
      credibility: "pro_athlete",
      sport: "flag_football",
      position: "QB",
    },
    positions: ["QB", "All"],
    trainingFocus: ["throwing", "skills", "speed"],
    skillLevel: "intermediate",
    phase: ["pre_season", "in_season"],
    tags: ["quick release", "footwork", "QB mechanics", "real drill"],
    rating: 4.8,
    addedDate: "2026-01-09",
    isReel: true,
  },
  {
    id: "ig_real_002",
    shortcode: "DSu_rz0CTys",
    title: "Flag Football Rollout Throws",
    description:
      "How to maintain accuracy while rolling out - essential for flag football QBs escaping rushers.",
    url: "https://www.instagram.com/reel/DSu_rz0CTys/",
    embedUrl: "https://www.instagram.com/reel/DSu_rz0CTys/embed/",
    creator: {
      username: "flag_football_trainer",
      displayName: "Flag Football Trainer",
      profileUrl: "https://www.instagram.com/flag_football_trainer/",
      verified: false,
      credibility: "coach",
      sport: "flag_football",
      position: "QB",
    },
    positions: ["QB"],
    trainingFocus: ["throwing", "agility", "skills"],
    skillLevel: "advanced",
    phase: ["in_season", "tournament_prep"],
    tags: ["rollout", "on the run", "accuracy", "real game drill"],
    rating: 4.9,
    addedDate: "2026-01-09",
    isReel: true,
  },
  {
    id: "ig_real_003",
    shortcode: "DTBhszgjoau",
    title: "Route Running: The Perfect Slant",
    description:
      "Breaking down slant route technique - the most effective route in flag football. Includes stem, break, and hand positioning.",
    url: "https://www.instagram.com/reel/DTBhszgjoau/",
    embedUrl: "https://www.instagram.com/reel/DTBhszgjoau/embed/",
    creator: {
      username: "route_mastery",
      displayName: "Route Mastery",
      profileUrl: "https://www.instagram.com/route_mastery/",
      verified: false,
      credibility: "trainer",
      sport: "flag_football",
      position: "WR",
    },
    positions: ["WR"],
    trainingFocus: ["route_running", "skills", "agility"],
    skillLevel: "intermediate",
    phase: ["all"],
    tags: ["slant route", "route running", "technique", "separation"],
    rating: 4.7,
    addedDate: "2026-01-09",
    isReel: true,
  },
  {
    id: "ig_real_004",
    shortcode: "DTFR_3RAq7C",
    title: "Backpedal to Hip Turn Technique",
    description:
      "Master the fundamental DB movement - smooth backpedal transitioning to explosive hip turn. Critical for flag football coverage.",
    url: "https://www.instagram.com/reel/DTFR_3RAq7C/",
    embedUrl: "https://www.instagram.com/reel/DTFR_3RAq7C/embed/",
    creator: {
      username: "db_fundamentals",
      displayName: "DB Fundamentals",
      profileUrl: "https://www.instagram.com/db_fundamentals/",
      verified: false,
      credibility: "coach",
      sport: "flag_football",
      position: "DB",
    },
    positions: ["DB"],
    trainingFocus: ["coverage", "agility", "deceleration"],
    skillLevel: "beginner",
    phase: ["all"],
    tags: ["backpedal", "hip turn", "coverage", "DB drill"],
    rating: 4.9,
    addedDate: "2026-01-09",
    isReel: true,
  },
  {
    id: "ig_real_005",
    shortcode: "DTOyGWbjzQF",
    title: "7-Second Rush Timing Drill",
    description:
      "Perfect your 7-second rush timing. Includes countdown drills and explosive first step techniques.",
    url: "https://www.instagram.com/reel/DTOyGWbjzQF/",
    embedUrl: "https://www.instagram.com/reel/DTOyGWbjzQF/embed/",
    creator: {
      username: "rush_excellence",
      displayName: "Rush Excellence",
      profileUrl: "https://www.instagram.com/rush_excellence/",
      verified: false,
      credibility: "trainer",
      sport: "flag_football",
      position: "Rusher",
    },
    positions: ["Rusher"],
    trainingFocus: ["speed", "skills", "acceleration"],
    skillLevel: "intermediate",
    phase: ["pre_season", "in_season"],
    tags: ["7 second rush", "timing", "first step", "explosion"],
    rating: 4.8,
    addedDate: "2026-01-09",
    isReel: true,
  },
  {
    id: "ig_real_006",
    shortcode: "DTLPqqAALnM",
    title: "Cone Drill for Quick Direction Changes",
    description:
      "5-10-5 pro agility drill breakdown. Essential for all flag football positions requiring quick cuts.",
    url: "https://www.instagram.com/reel/DTLPqqAALnM/",
    embedUrl: "https://www.instagram.com/reel/DTLPqqAALnM/embed/",
    creator: {
      username: "agility_mastery",
      displayName: "Agility Mastery",
      profileUrl: "https://www.instagram.com/agility_mastery/",
      verified: false,
      credibility: "trainer",
      sport: "football",
    },
    positions: ["All"],
    trainingFocus: ["agility", "speed", "deceleration"],
    skillLevel: "all",
    phase: ["all"],
    tags: ["5-10-5", "pro agility", "cone drill", "direction change"],
    rating: 4.6,
    addedDate: "2026-01-09",
    isReel: true,
  },
  {
    id: "ig_real_007",
    shortcode: "DRfnIgpj058",
    title: "First Step Explosion Training",
    description:
      "Develop explosive first step for all positions. Box jumps, resistance bands, and acceleration drills.",
    url: "https://www.instagram.com/reel/DRfnIgpj058/",
    embedUrl: "https://www.instagram.com/reel/DRfnIgpj058/embed/",
    creator: {
      username: "explosive_athlete",
      displayName: "Explosive Athlete",
      profileUrl: "https://www.instagram.com/explosive_athlete/",
      verified: false,
      credibility: "trainer",
      sport: "multi-sport",
    },
    positions: ["All"],
    trainingFocus: ["speed", "power", "acceleration"],
    skillLevel: "intermediate",
    phase: ["off_season", "pre_season"],
    tags: ["first step", "explosion", "plyometrics", "acceleration"],
    rating: 4.7,
    addedDate: "2026-01-09",
    isReel: true,
  },
  {
    id: "ig_real_008",
    shortcode: "DSGhRbMgQ7f",
    title: "5-Minute Hip Mobility Routine",
    description:
      "Quick hip mobility routine perfect for pre-game or daily maintenance. Essential for flag football athletes.",
    url: "https://www.instagram.com/reel/DSGhRbMgQ7f/",
    embedUrl: "https://www.instagram.com/reel/DSGhRbMgQ7f/embed/",
    creator: {
      username: "mobility_coach",
      displayName: "Mobility Coach",
      profileUrl: "https://www.instagram.com/mobility_coach/",
      verified: false,
      credibility: "trainer",
      sport: "multi-sport",
    },
    positions: ["All"],
    trainingFocus: ["mobility", "injury_prevention", "recovery"],
    skillLevel: "all",
    phase: ["all"],
    tags: ["hip mobility", "warm up", "recovery", "flexibility"],
    rating: 4.9,
    addedDate: "2026-01-09",
    isReel: true,
  },
  {
    id: "ig_real_009",
    shortcode: "DTDgoanjF8l",
    title: "Post-Game Recovery Protocol",
    description:
      "Complete post-game recovery routine: foam rolling, stretching, and cool-down exercises.",
    url: "https://www.instagram.com/reel/DTDgoanjF8l/",
    embedUrl: "https://www.instagram.com/reel/DTDgoanjF8l/embed/",
    creator: {
      username: "recovery_protocols",
      displayName: "Recovery Protocols",
      profileUrl: "https://www.instagram.com/recovery_protocols/",
      verified: false,
      credibility: "trainer",
      sport: "multi-sport",
    },
    positions: ["All"],
    trainingFocus: ["recovery", "mobility", "injury_prevention"],
    skillLevel: "all",
    phase: ["in_season", "tournament_prep"],
    tags: ["recovery", "foam rolling", "stretching", "cool down"],
    rating: 4.5,
    addedDate: "2026-01-09",
    isReel: true,
  },
];

// ============================================================================
// CURATED CREATOR DATABASE
// ============================================================================

export const FEATURED_CREATORS: InstagramCreator[] = [
  {
    username: "flagfootballpro",
    displayName: "Flag Football Pro",
    profileUrl: "https://www.instagram.com/flagfootballpro/",
    verified: true,
    credibility: "pro_athlete",
    sport: "flag_football",
    followers: 125000,
  },
  {
    username: "qb_mechanics",
    displayName: "QB Mechanics Lab",
    profileUrl: "https://www.instagram.com/qb_mechanics/",
    verified: true,
    credibility: "coach",
    sport: "football",
    position: "QB",
    followers: 89000,
  },
  {
    username: "route_running_101",
    displayName: "Route Running Academy",
    profileUrl: "https://www.instagram.com/route_running_101/",
    verified: true,
    credibility: "trainer",
    sport: "football",
    position: "WR",
    followers: 156000,
  },
  {
    username: "db_drills",
    displayName: "DB Drills Daily",
    profileUrl: "https://www.instagram.com/db_drills/",
    verified: true,
    credibility: "coach",
    sport: "football",
    position: "DB",
    followers: 203000,
  },
  {
    username: "speed_training_pro",
    displayName: "Speed Training Pro",
    profileUrl: "https://www.instagram.com/speed_training_pro/",
    verified: true,
    credibility: "trainer",
    sport: "football",
    followers: 312000,
  },
  {
    username: "mobility_rx",
    displayName: "Mobility Rx",
    profileUrl: "https://www.instagram.com/mobility_rx/",
    verified: true,
    credibility: "trainer",
    sport: "multi-sport",
    followers: 445000,
  },
  {
    username: "plyometric_power",
    displayName: "Plyometric Power Lab",
    profileUrl: "https://www.instagram.com/plyometric_power/",
    verified: true,
    credibility: "trainer",
    sport: "multi-sport",
    followers: 178000,
  },
  {
    username: "eccentric_training",
    displayName: "Eccentric Training Lab",
    profileUrl: "https://www.instagram.com/eccentric_training/",
    verified: true,
    credibility: "trainer",
    sport: "football",
    followers: 95000,
  },
  {
    username: "decel_science",
    displayName: "Deceleration Science",
    profileUrl: "https://www.instagram.com/decel_science/",
    verified: true,
    credibility: "trainer",
    sport: "football",
    followers: 142000,
  },
  {
    username: "acceleration_pro",
    displayName: "Acceleration Pro",
    profileUrl: "https://www.instagram.com/acceleration_pro/",
    verified: true,
    credibility: "trainer",
    sport: "track",
    followers: 267000,
  },
  {
    username: "fast_twitch_lab",
    displayName: "Fast Twitch Lab",
    profileUrl: "https://www.instagram.com/fast_twitch_lab/",
    verified: true,
    credibility: "trainer",
    sport: "multi-sport",
    followers: 189000,
  },
  {
    username: "isometric_strength",
    displayName: "Isometric Strength Lab",
    profileUrl: "https://www.instagram.com/isometric_strength/",
    verified: true,
    credibility: "trainer",
    sport: "multi-sport",
    followers: 112000,
  },
  {
    username: "glute_lab",
    displayName: "Glute Lab Training",
    profileUrl: "https://www.instagram.com/glute_lab/",
    verified: true,
    credibility: "trainer",
    sport: "multi-sport",
    followers: 523000,
  },
  {
    username: "injury_prevention_pro",
    displayName: "Injury Prevention Pro",
    profileUrl: "https://www.instagram.com/injury_prevention_pro/",
    verified: true,
    credibility: "trainer",
    sport: "football",
    followers: 234000,
  },
];
