import type { TrainingGoal, TrainingSessionTemplate } from "./training-plan.service";

// ============================================================================
// GOAL TRAINING TEMPLATES
// Static training session templates for each goal × phase combination.
// Extracted from TrainingPlanService to keep the service focused on
// orchestration and persistence.
// ============================================================================

export const GOAL_TEMPLATES: Record<
  TrainingGoal,
  Record<string, TrainingSessionTemplate[]>
> = {
speed: {
    foundation: [
      {
        day: 0,
        sessionType: "speed",
        focus: ["Mechanics", "Acceleration"],
        exercises: ["Wall drills", "10m sprints", "Resisted sprints"],
        duration: 45,
        intensity: "medium",
        volume: 8,
        restPeriods: "2-3 min",
        notes: "Focus on form",
      },
      {
        day: 2,
        sessionType: "strength",
        focus: ["Posterior chain"],
        exercises: ["RDLs", "Hip thrusts"],
        duration: 60,
        intensity: "medium",
        volume: 4,
        restPeriods: "3 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "speed",
        focus: ["Top speed"],
        exercises: ["Flying 20s", "30m sprints"],
        duration: 45,
        intensity: "high",
        volume: 6,
        restPeriods: "4-5 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Dynamic warmup", "Foam rolling"],
        duration: 30,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "Active recovery",
      },
    ],
    strength: [
      {
        day: 0,
        sessionType: "speed",
        focus: ["Acceleration", "Power"],
        exercises: ["Resisted sprints", "Hill sprints", "Plyometrics"],
        duration: 60,
        intensity: "high",
        volume: 10,
        restPeriods: "3-4 min",
        notes: "Max effort",
      },
      {
        day: 2,
        sessionType: "strength",
        focus: ["Max strength"],
        exercises: ["Squats", "Deadlifts", "Nordic curls"],
        duration: 75,
        intensity: "high",
        volume: 5,
        restPeriods: "4-5 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "speed",
        focus: ["Top speed", "Speed endurance"],
        exercises: ["Flying 30s", "150m repeats"],
        duration: 60,
        intensity: "high",
        volume: 8,
        restPeriods: "5-6 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Yoga", "Foam rolling"],
        duration: 45,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "",
      },
    ],
  },
  "change-of-direction": {
    foundation: [
      {
        day: 0,
        sessionType: "agility",
        focus: ["Lateral movement", "Deceleration"],
        exercises: ["Lateral shuffles", "5-10-5 drill", "Cone drills"],
        duration: 45,
        intensity: "medium",
        volume: 10,
        restPeriods: "2 min",
        notes: "Focus on technique",
      },
      {
        day: 2,
        sessionType: "strength",
        focus: ["Eccentric strength"],
        exercises: ["Split squats", "Lunges", "Single-leg RDLs"],
        duration: 60,
        intensity: "medium",
        volume: 4,
        restPeriods: "2-3 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "agility",
        focus: ["Multi-directional"],
        exercises: ["T-drill", "L-drill", "Reactive agility"],
        duration: 50,
        intensity: "high",
        volume: 8,
        restPeriods: "3 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Hip mobility", "Ankle mobility"],
        duration: 30,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "",
      },
    ],
    strength: [
      {
        day: 0,
        sessionType: "agility",
        focus: ["Reactive COD", "Power"],
        exercises: [
          "Reactive cone drills",
          "Plyometric cuts",
          "Mirror drills",
        ],
        duration: 60,
        intensity: "high",
        volume: 12,
        restPeriods: "3-4 min",
        notes: "Game-like intensity",
      },
      {
        day: 2,
        sessionType: "strength",
        focus: ["Eccentric power"],
        exercises: ["Depth jumps", "Lateral bounds", "Single-leg hops"],
        duration: 75,
        intensity: "high",
        volume: 6,
        restPeriods: "4 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "agility",
        focus: ["Speed-COD"],
        exercises: ["Sprint-cut-sprint", "Zigzag sprints"],
        duration: 60,
        intensity: "high",
        volume: 10,
        restPeriods: "4-5 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Full body mobility"],
        duration: 45,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "",
      },
    ],
  },
  agility: {
    foundation: [
      {
        day: 0,
        sessionType: "agility",
        focus: ["Footwork", "Quickness"],
        exercises: ["Ladder drills", "Cone drills", "Reaction drills"],
        duration: 40,
        intensity: "medium",
        volume: 12,
        restPeriods: "1-2 min",
        notes: "High volume, low intensity",
      },
      {
        day: 2,
        sessionType: "strength",
        focus: ["Lower body"],
        exercises: ["Goblet squats", "Step-ups", "Calf raises"],
        duration: 50,
        intensity: "medium",
        volume: 3,
        restPeriods: "2 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "agility",
        focus: ["Reactive agility"],
        exercises: ["Mirror drills", "Partner drills", "Random direction"],
        duration: 45,
        intensity: "high",
        volume: 10,
        restPeriods: "2-3 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Dynamic stretching"],
        duration: 30,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "",
      },
    ],
    strength: [
      {
        day: 0,
        sessionType: "agility",
        focus: ["Game-speed agility"],
        exercises: [
          "Position-specific drills",
          "Reactive cuts",
          "Open-field agility",
        ],
        duration: 60,
        intensity: "high",
        volume: 15,
        restPeriods: "3 min",
        notes: "Competition intensity",
      },
      {
        day: 2,
        sessionType: "strength",
        focus: ["Power"],
        exercises: ["Box jumps", "Lateral bounds", "Medicine ball throws"],
        duration: 60,
        intensity: "high",
        volume: 5,
        restPeriods: "3-4 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "agility",
        focus: ["Speed-agility"],
        exercises: ["Sprint-agility combos", "Multi-directional sprints"],
        duration: 60,
        intensity: "high",
        volume: 12,
        restPeriods: "4 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Yoga flow"],
        duration: 45,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "",
      },
    ],
  },
  "route-running": {
    foundation: [
      {
        day: 0,
        sessionType: "technique",
        focus: ["Route mechanics", "Separation"],
        exercises: ["Route tree practice", "Release drills", "Cone routes"],
        duration: 60,
        intensity: "medium",
        volume: 20,
        restPeriods: "1-2 min",
        notes: "Focus on technique",
      },
      {
        day: 2,
        sessionType: "speed",
        focus: ["Acceleration"],
        exercises: ["10m sprints", "Starts", "Resisted sprints"],
        duration: 45,
        intensity: "medium",
        volume: 8,
        restPeriods: "2-3 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "technique",
        focus: ["Route execution"],
        exercises: ["Full routes", "Catch drills", "Contested catches"],
        duration: 60,
        intensity: "high",
        volume: 15,
        restPeriods: "2 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Hip mobility", "Shoulder mobility"],
        duration: 30,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "",
      },
    ],
    strength: [
      {
        day: 0,
        sessionType: "technique",
        focus: ["Advanced routes", "Game situations"],
        exercises: ["Double moves", "Route combinations", "QB-WR timing"],
        duration: 75,
        intensity: "high",
        volume: 25,
        restPeriods: "2 min",
        notes: "Game-speed",
      },
      {
        day: 2,
        sessionType: "speed",
        focus: ["Top speed"],
        exercises: ["Flying 20s", "30m sprints"],
        duration: 50,
        intensity: "high",
        volume: 10,
        restPeriods: "4 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "technique",
        focus: ["Route precision"],
        exercises: ["Precision routes", "Separation moves"],
        duration: 70,
        intensity: "high",
        volume: 20,
        restPeriods: "2-3 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Full body mobility"],
        duration: 45,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "",
      },
    ],
  },
  defense: {
    foundation: [
      {
        day: 0,
        sessionType: "technique",
        focus: ["Backpedal", "Hip turn"],
        exercises: [
          "Backpedal drills",
          "Hip turn drills",
          "Coverage technique",
        ],
        duration: 60,
        intensity: "medium",
        volume: 15,
        restPeriods: "2 min",
        notes: "Focus on form",
      },
      {
        day: 2,
        sessionType: "agility",
        focus: ["Lateral movement"],
        exercises: ["Lateral shuffles", "Cone drills", "Mirror drills"],
        duration: 50,
        intensity: "medium",
        volume: 12,
        restPeriods: "2-3 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "technique",
        focus: ["Coverage", "Ball skills"],
        exercises: ["Coverage drills", "Ball drills", "Break on ball"],
        duration: 60,
        intensity: "high",
        volume: 15,
        restPeriods: "2 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Hip mobility", "Ankle mobility"],
        duration: 30,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "",
      },
    ],
    strength: [
      {
        day: 0,
        sessionType: "technique",
        focus: ["Game situations", "Reactive coverage"],
        exercises: [
          "Coverage scenarios",
          "Break drills",
          "Contested catches",
        ],
        duration: 75,
        intensity: "high",
        volume: 20,
        restPeriods: "2-3 min",
        notes: "Game-speed",
      },
      {
        day: 2,
        sessionType: "agility",
        focus: ["Reactive agility"],
        exercises: ["Reactive cuts", "Direction changes"],
        duration: 60,
        intensity: "high",
        volume: 15,
        restPeriods: "3-4 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "technique",
        focus: ["Advanced coverage"],
        exercises: ["Zone coverage", "Man coverage", "Ball skills"],
        duration: 70,
        intensity: "high",
        volume: 18,
        restPeriods: "2-3 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Full body mobility"],
        duration: 45,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "",
      },
    ],
  },
  power: {
    foundation: [
      {
        day: 0,
        sessionType: "strength",
        focus: ["Max strength"],
        exercises: ["Squats", "Deadlifts", "Press"],
        duration: 75,
        intensity: "high",
        volume: 5,
        restPeriods: "4-5 min",
        notes: "Heavy loads",
      },
      {
        day: 2,
        sessionType: "speed",
        focus: ["Power development"],
        exercises: ["Plyometrics", "Jumps", "Throws"],
        duration: 50,
        intensity: "high",
        volume: 8,
        restPeriods: "3-4 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "strength",
        focus: ["Power"],
        exercises: ["Olympic lifts", "Explosive movements"],
        duration: 70,
        intensity: "high",
        volume: 6,
        restPeriods: "4 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Full body mobility"],
        duration: 45,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "",
      },
    ],
    strength: [
      {
        day: 0,
        sessionType: "strength",
        focus: ["Peak power"],
        exercises: ["Max effort lifts", "Plyometrics", "Speed work"],
        duration: 90,
        intensity: "high",
        volume: 6,
        restPeriods: "5 min",
        notes: "Peak intensity",
      },
      {
        day: 2,
        sessionType: "speed",
        focus: ["Explosive speed"],
        exercises: ["Sprint work", "Jumps", "Throws"],
        duration: 60,
        intensity: "high",
        volume: 10,
        restPeriods: "4-5 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "strength",
        focus: ["Power maintenance"],
        exercises: ["Moderate loads", "Power movements"],
        duration: 75,
        intensity: "medium",
        volume: 5,
        restPeriods: "3-4 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Yoga", "Foam rolling"],
        duration: 45,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "",
      },
    ],
  },
  endurance: {
    foundation: [
      {
        day: 0,
        sessionType: "conditioning",
        focus: ["Aerobic base"],
        exercises: ["Tempo runs", "Interval runs", "Fartlek"],
        duration: 60,
        intensity: "medium",
        volume: 3,
        restPeriods: "2 min",
        notes: "Steady pace",
      },
      {
        day: 2,
        sessionType: "strength",
        focus: ["Endurance strength"],
        exercises: ["Circuit training", "High reps"],
        duration: 60,
        intensity: "medium",
        volume: 3,
        restPeriods: "1 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "conditioning",
        focus: ["Anaerobic"],
        exercises: ["Sprint intervals", "Shuttle runs"],
        duration: 50,
        intensity: "high",
        volume: 6,
        restPeriods: "3 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Light jog", "Stretching"],
        duration: 30,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "",
      },
    ],
    strength: [
      {
        day: 0,
        sessionType: "conditioning",
        focus: ["VO2 max"],
        exercises: ["High-intensity intervals", "Sprint repeats"],
        duration: 70,
        intensity: "high",
        volume: 8,
        restPeriods: "3-4 min",
        notes: "Max effort",
      },
      {
        day: 2,
        sessionType: "strength",
        focus: ["Endurance"],
        exercises: ["Circuit", "High volume"],
        duration: 60,
        intensity: "medium",
        volume: 4,
        restPeriods: "1-2 min",
        notes: "",
      },
      {
        day: 4,
        sessionType: "conditioning",
        focus: ["Lactate threshold"],
        exercises: ["Tempo intervals", "Sustained efforts"],
        duration: 65,
        intensity: "high",
        volume: 5,
        restPeriods: "4 min",
        notes: "",
      },
      {
        day: 6,
        sessionType: "recovery",
        focus: ["Mobility"],
        exercises: ["Active recovery"],
        duration: 45,
        intensity: "low",
        volume: 1,
        restPeriods: "N/A",
        notes: "",
      },
    ],
  },
}
