-- Backend de-drift — Phase 5 (partial): drop the legacy `sessions` table.
--
-- `sessions` was a GPS/open-data import table that was never written. Read only by two
-- legacy analytics paths, both now safe against a missing table:
--   - training-metrics.js fetchLegacyMetrics — returns { data: [], error } on error
--   - trends.js (×2) — guarded to ignore 42P01; downstream uses `data || []`
-- Canonical session table is training_sessions. No FK or view dependents.
--
-- DEFERRED (own focused phase, touches live write paths): merge workout_logs into
-- training_sessions, and re-home the training-load write that daily-protocol.js still
-- sends to wellness_logs (training_load/duration/rpe) → training_sessions, then drop
-- wellness_logs. See docs/DATA_MODEL.md.
--
-- Applied via Supabase MCP on 2026-05-29 (project grfjmnjpzvknmsxrwesx).
DROP TABLE IF EXISTS public.sessions;
