-- Cluster 4 of the identity standardization: drop training_sessions.athlete_id duplicate.
-- Applied via Supabase MCP 2026-05-29 (project grfjmnjpzvknmsxrwesx).
--
-- training_sessions had user_id (canonical, used by all RLS policies) + an athlete_id
-- duplicate written only by log_training_session. Backfilled, recreated
-- v_training_sessions_consent without the athlete_id passthrough column (DROP+CREATE,
-- security_invoker=true, re-GRANT SELECT to anon/authenticated/service_role), dropped
-- the column, and rewrote log_training_session to stop writing athlete_id.
--
-- Code: calc-readiness fetchTrainingSessions collapsed from a 3-attempt
-- (user_id → athlete_id → UNFILTERED) fallback to a single user_id query (the unfiltered
-- attempt was a latent all-athletes data-leak); consent-data-reader dropped the
-- ",athlete_id.eq/​in" alternative from its 3 training_sessions .or() filters.
