-- Backend de-drift — Phase 2: hydration consolidated onto athlete_hydration_logs.
--
-- Canonical hydration store is public.athlete_hydration_logs (one row per drink:
-- logged_at timestamptz, amount_ml, beverage_type, source, metadata jsonb). All code
-- repointed off the legacy hydration_logs table:
--   - netlify/functions/hydration.js (get today / log / history)
--   - netlify/functions/staff-nutritionist.js (report read)
--   - angular .../tournament-nutrition/tournament-nutrition-state.service.ts
--     (read / write / realtime / clear; context now lives in metadata->>'context',
--      day filtering via logged_at range)
--
-- hydration_logs had 0 rows, 0 remaining code references, and no FK dependents.
-- Applied via Supabase MCP on 2026-05-29 (project grfjmnjpzvknmsxrwesx).
--
-- DEFERRED (separate task): the subjective daily_wellness_checkin.hydration_level
-- column + its upsert_wellness_checkin() RPC param. Hydration must not be a wellness
-- field (no double entry); the rebuilt wellness form omits it, then the column +
-- RPC param are removed together. See docs/DATA_MODEL.md.
DROP TABLE IF EXISTS public.hydration_logs;
