-- Cluster 5 of the identity standardization: consent / audit / parent / achievements → user_id.
-- Applied via Supabase MCP 2026-05-29. Pure renames (RLS/views/FK/indexes auto-update).
--   athlete_consent_settings, consent_access_log, consent_change_log, parent_guardian_links,
--   parent_notifications, athlete_achievements: athlete_id → user_id
--   roster_audit_log: player_id → user_id  (performed_by stays = the actor)
-- parent_guardian_links.parent_id / parent_notifications.parent_id stay (the guardian).
-- Function bodies fixed: get_athlete_consent, log_roster_change, award_achievement
--   (dynamic-SQL legacy dual-write into athlete_achievements), process_hard_deletion
--   (athlete_achievements delete → user_id).
-- Code: consent-guard.js athlete_consent_settings query athlete_id → user_id (2 sites).
--
-- NOTES (separate, pre-existing — NOT fixed here, dormant features, fix at port):
--  * athlete_achievements is a CONSOLIDATION CANDIDATE — player_achievements (already user_id)
--    is the canonical achievements table; athlete_achievements is a legacy dual-write whose
--    response-feedback.js upsert writes ~9 columns that don't exist in the schema.
--  * ai-chat youth-parent code queries parent_guardian_links/parent_notifications with a
--    wholly different schema (youth_id/status/can_view_ai_chats/summary/delivery_*) — broken
--    regardless of this rename; it never referenced athlete_id, so no repoint was needed.
--  * consent-data-reader consent_access_log insert writes accessor_user_id/target_user_id/...
--    (none in schema) — also dormant/mismatched.
