-- Cluster 3 of the identity standardization: collapse readiness_scores' triple-drift.
-- Applied via Supabase MCP 2026-05-29 (project grfjmnjpzvknmsxrwesx).
--
-- The table carried two column generations kept in lockstep by the
-- sync_readiness_scores_compat BEFORE trigger:
--   legacy NOT NULL: athlete_id, date, readiness_score (+ dead fatigue_score/stress_score/overall_readiness)
--   canonical:       user_id, day, score (+ component scores the engine writes)
-- Collapsed to user_id / day / score: backfilled, dropped the trigger+fn, recreated the
-- SELECT RLS policy on user_id (DROP COLUMN can't auto-rewrite a dependent policy),
-- dropped the legacy/dead columns, set user_id+day NOT NULL, replaced the partial
-- (user_id,day) index with a full UNIQUE constraint (so PostgREST onConflict can infer it),
-- and rewrote get_athlete_readiness to the canonical columns.
--
-- Code: persistReadinessScore simplified to a single upsert onConflict "user_id,day"
-- (was a 3-way athlete_id,date / athlete_id,day / user_id,day fallback); removed athlete_id
-- from the payload; readiness-history.js + consent-guard.js readiness query → user_id;
-- daily-protocol.js reads .score (dropped the || readiness_score fallback).
--
-- NOTE (separate pre-existing bug, not fixed here): readiness-history.js selects a
-- nonexistent column `data_mode` on readiness_scores — to fix at port with real intent.
