-- Consolidated participation model — Phase 1 (additive): the ACTUALS that feed ACWR.
-- Applied via Supabase MCP 2026-06-01.
--
-- The schedule spine (competition_events.expected_game_count) is the PLAN; ACWR needs the
-- GROUND TRUTH — did the athlete attend, and how many of the expected games did they really
-- play (hamstring → 5 of 8). New event_participation captures that; record_event_participation
-- computes session-RPE load (games × ~40min × RPE, default 7) and writes a 'competition'
-- training_sessions row so the existing ACWR pipeline includes it automatically (5/8 → ~62%).
-- v_pending_event_participation drives the post-event prompt: recent ended events the athlete
-- was rostered for, with no confirmed participation yet → "Were you at {event}? How many games?"
--
-- See the applied migration for the full DDL (event_participation table + RLS using
-- ff_is_team_staff/ff_is_active_team_member, record_event_participation RPC,
-- v_pending_event_participation view). Phase 2 will migrate availability→spine + retire the
-- legacy tournaments cluster.
