-- Cluster 7 (final identity cluster): attendance/payments/coach/game tables → user_id.
-- Applied via Supabase MCP 2026-05-29. Pure renames (RLS/views/FK/index/constraint NAMES
-- preserved on rename — so PostgREST hints by constraint name, e.g.
-- team_members!player_payments_player_id_fkey, still resolve). coach_id (actor) kept.
--   game_participations, player_tournament_availability, attendance_records, player_payments,
--   coach_activity_log, coach_alert_acknowledgments, coach_inbox_items, template_assignments:
--   player_id → user_id
--
-- Code repoints touched ONLY DB-column refs: .eq filters, select column-lists, onConflict
-- keys, insert/upsert object keys targeting the table, column-based embed hints
-- (users:player_id → users:user_id), and result-row reads (p.player_id → p.user_id).
-- LEFT intact (client contract, reconciled at UI port): API request/response field names &
-- local vars (destructured from request bodies), function args, and constraint-name embed hints.
-- template_assignments + coach_activity_log + coach_alert_acknowledgments needed NO code change
-- (already used user_id / only a constraint-name hint / no column ref).
--
-- NOTE (pre-existing dormant, NOT identity): attendance.js references player_id on
-- player_attendance_stats and absence_requests, neither of which has that column per the
-- schema scan — broken regardless; fix at port.
