-- Backend de-drift — Phase 7: drop legacy wellness_logs (was dual-purpose drift).
--
-- wellness_logs mixed two domains:
--   1. Training load — daily-protocol.js upserted training_load/duration/rpe here. DEAD:
--      the same completed session is already inserted into training_sessions (the canonical
--      ACWR load source, calc-readiness reads only training_sessions). Removed the dup write.
--   2. Wellness/sleep fields — read by sleep-data.js (legacy fallback) and
--      smart-training-recommendations.js. Repointed both to daily_wellness_checkin
--      (canonical subjective wellness), with field normalization (muscle_soreness→soreness,
--      energy_level→energy) and the latest-row order bug fixed.
--
-- No remaining .from("wellness_logs") references; no FK or view dependents.
-- Applied via Supabase MCP on 2026-05-29 (project grfjmnjpzvknmsxrwesx).
DROP TABLE IF EXISTS public.wellness_logs;
