-- Data for table: affordable_equipment
-- Generated: 2025-12-01T20:59:18.967Z

INSERT INTO affordable_equipment (id, equipment_name, equipment_category, description, price_range_min, price_range_max, where_to_buy, diy_alternatives, expected_lifespan_months, maintenance_requirements, performance_benefit, priority_for_amateur, created_at) VALUES (1, 'Foam Roller', 'recovery', 'Basic foam roller for muscle recovery and mobility', '15.00', '40.00', '["sports_stores","online_retailers","supermarkets"]', '["tennis_ball","water_bottle","rolled_towel"]', 24, '["clean_regularly","replace_when_worn"]', 'Improves muscle recovery and mobility', 'essential', '2025-08-18T20:14:28.722Z');
INSERT INTO affordable_equipment (id, equipment_name, equipment_category, description, price_range_min, price_range_max, where_to_buy, diy_alternatives, expected_lifespan_months, maintenance_requirements, performance_benefit, priority_for_amateur, created_at) VALUES (2, 'Resistance Bands', 'training', 'Versatile resistance bands for strength training', '20.00', '60.00', '["sports_stores","online_retailers","fitness_stores"]', '["bodyweight_exercises","household_items","water_jugs"]', 18, '["check_for_tears","store_properly"]', 'Enables strength training at home', 'essential', '2025-08-18T20:14:28.722Z');
INSERT INTO affordable_equipment (id, equipment_name, equipment_category, description, price_range_min, price_range_max, where_to_buy, diy_alternatives, expected_lifespan_months, maintenance_requirements, performance_benefit, priority_for_amateur, created_at) VALUES (3, 'Protein Powder', 'nutrition', 'Basic whey protein for muscle recovery', '25.00', '80.00', '["supermarkets","health_stores","online_retailers"]', '["eggs","greek_yogurt","lean_meat"]', 12, '["store_cool_dry_place","use_by_date"]', 'Supports muscle recovery and growth', 'essential', '2025-08-18T20:14:28.722Z');
INSERT INTO affordable_equipment (id, equipment_name, equipment_category, description, price_range_min, price_range_max, where_to_buy, diy_alternatives, expected_lifespan_months, maintenance_requirements, performance_benefit, priority_for_amateur, created_at) VALUES (4, 'Heart Rate Monitor', 'measurement', 'Basic heart rate monitoring for training intensity', '30.00', '100.00', '["sports_stores","online_retailers","electronics_stores"]', '["perceived_exertion","talk_test","manual_pulse"]', 36, '["clean_sensors","replace_battery"]', 'Tracks training intensity and recovery', 'recommended', '2025-08-18T20:14:28.722Z');
INSERT INTO affordable_equipment (id, equipment_name, equipment_category, description, price_range_min, price_range_max, where_to_buy, diy_alternatives, expected_lifespan_months, maintenance_requirements, performance_benefit, priority_for_amateur, created_at) VALUES (5, 'Creatine Monohydrate', 'nutrition', 'Evidence-based supplement for strength and power', '15.00', '40.00', '["health_stores","online_retailers","pharmacies"]', '["natural_foods","other_supplements"]', 24, '["store_dry_place","use_consistently"]', 'Improves strength and power output', 'recommended', '2025-08-18T20:14:28.722Z');
INSERT INTO affordable_equipment (id, equipment_name, equipment_category, description, price_range_min, price_range_max, where_to_buy, diy_alternatives, expected_lifespan_months, maintenance_requirements, performance_benefit, priority_for_amateur, created_at) VALUES (6, 'Mobility Tools', 'recovery', 'Lacrosse ball, massage stick for mobility work', '10.00', '30.00', '["sports_stores","online_retailers"]', '["tennis_ball","water_bottle","rolling_pin"]', 24, '["clean_regularly","replace_when_worn"]', 'Improves joint mobility and flexibility', 'recommended', '2025-08-18T20:14:28.722Z');
INSERT INTO affordable_equipment (id, equipment_name, equipment_category, description, price_range_min, price_range_max, where_to_buy, diy_alternatives, expected_lifespan_months, maintenance_requirements, performance_benefit, priority_for_amateur, created_at) VALUES (7, 'Portable Ice Bath Tub', 'recovery', 'XL portable foldable ice bath tub with cover for cold therapy recovery', '80.00', '150.00', '["online_retailers","temu","amazon","fitness_stores"]', '["bathtub","large_bucket","storage_bin"]', 60, '["clean_after_each_use","store_dry_location","check_for_damage"]', 'Professional-grade cold therapy recovery at home', 'recommended', '2025-08-18T20:19:58.336Z');
