-- Data for table: affordable_brand_products
-- Generated: 2025-12-01T20:59:18.047Z

INSERT INTO affordable_brand_products (id, brand_name, brand_website, product_name, product_category, price_euros, amateur_budget_tier, affordability_rating, quality_rating, value_for_money, best_for, considerations, created_at) VALUES (1, 'Pulsio', 'https://pulsio.co.uk', 'Pulsio AIR Massage Gun', 'recovery', '80.00', 'moderate_1000', 8, 8, 9, 'Serious amateur athletes who want quality recovery tools', '["Excellent value for money","British quality","Good warranty","Portable design"]', '2025-08-18T20:28:03.147Z');
INSERT INTO affordable_brand_products (id, brand_name, brand_website, product_name, product_category, price_euros, amateur_budget_tier, affordability_rating, quality_rating, value_for_money, best_for, considerations, created_at) VALUES (2, 'Pulsio', 'https://pulsio.co.uk', 'Pulsio ELITE', 'recovery', '115.00', 'serious_2000', 7, 9, 8, 'Advanced amateur athletes who need deep tissue work', '["High power output","Professional quality","Good for serious training","Worth the investment"]', '2025-08-18T20:28:03.147Z');
INSERT INTO affordable_brand_products (id, brand_name, brand_website, product_name, product_category, price_euros, amateur_budget_tier, affordability_rating, quality_rating, value_for_money, best_for, considerations, created_at) VALUES (3, 'Pulsio', 'https://pulsio.co.uk', 'Compression Sleeve', 'recovery', '79.99', 'moderate_1000', 8, 8, 8, 'Amateur athletes who want compression therapy', '["Portable compression","Good for travel","Easy to use","Reasonable price"]', '2025-08-18T20:28:03.147Z');
INSERT INTO affordable_brand_products (id, brand_name, brand_website, product_name, product_category, price_euros, amateur_budget_tier, affordability_rating, quality_rating, value_for_money, best_for, considerations, created_at) VALUES (4, 'Blazepod', 'https://blazepod.eu', 'Blazepod Training Set', 'performance', '300.00', 'serious_2000', 6, 9, 7, 'Performance-focused amateur athletes', '["Smart training technology","Great for skill development","Professional quality","Investment piece"]', '2025-08-18T20:28:03.147Z');
INSERT INTO affordable_brand_products (id, brand_name, brand_website, product_name, product_category, price_euros, amateur_budget_tier, affordability_rating, quality_rating, value_for_money, best_for, considerations, created_at) VALUES (5, 'Blazepod', 'https://blazepod.eu', 'Blazepod Reaction Trainer', 'performance', '150.00', 'moderate_1000', 7, 8, 8, 'Intermediate athletes improving reaction time', '["Good for cognitive training","Portable","Reasonable price","Effective for skill development"]', '2025-08-18T20:28:03.147Z');
INSERT INTO affordable_brand_products (id, brand_name, brand_website, product_name, product_category, price_euros, amateur_budget_tier, affordability_rating, quality_rating, value_for_money, best_for, considerations, created_at) VALUES (6, 'Fizian', 'https://fizian.si', 'Basic EMS Device', 'recovery', '200.00', 'serious_2000', 7, 8, 7, 'Serious amateur athletes with specific needs', '["Professional quality","Specific use cases","Good for recovery","Investment for serious athletes"]', '2025-08-18T20:28:03.147Z');
INSERT INTO affordable_brand_products (id, brand_name, brand_website, product_name, product_category, price_euros, amateur_budget_tier, affordability_rating, quality_rating, value_for_money, best_for, considerations, created_at) VALUES (7, 'Fizian', 'https://fizian.si', 'Portable Tecar Device', 'recovery', '500.00', 'serious_2000', 6, 9, 6, 'Very serious amateur athletes', '["Professional grade","Expensive but effective","Long-term investment","For committed athletes only"]', '2025-08-18T20:28:03.147Z');
INSERT INTO affordable_brand_products (id, brand_name, brand_website, product_name, product_category, price_euros, amateur_budget_tier, affordability_rating, quality_rating, value_for_money, best_for, considerations, created_at) VALUES (8, 'Globus Corporation', 'https://www.globuscorporation.com/en/', 'Basic Rehabilitation Kit', 'recovery', '300.00', 'serious_2000', 7, 9, 7, 'Serious amateur athletes with injury history', '["Medical grade quality","Professional standard","Good for rehabilitation","Investment for serious needs"]', '2025-08-18T20:28:03.147Z');
INSERT INTO affordable_brand_products (id, brand_name, brand_website, product_name, product_category, price_euros, amateur_budget_tier, affordability_rating, quality_rating, value_for_money, best_for, considerations, created_at) VALUES (9, 'Globus Corporation', 'https://www.globuscorporation.com/en/', 'Performance Monitoring Device', 'performance', '400.00', 'serious_2000', 6, 9, 7, 'Data-driven amateur athletes', '["Professional monitoring","Accurate data","Good for tracking progress","Investment for serious athletes"]', '2025-08-18T20:28:03.147Z');
