-- Data for table: budget_categories
-- Generated: 2025-12-01T20:59:19.657Z

INSERT INTO budget_categories (id, category_name, category_description, why_it_matters, recommended_min_spend, recommended_max_spend, priority_level, expected_roi_percentage, created_at) VALUES (1, 'Sleep & Recovery Tech', 'Technology and equipment for optimizing sleep quality and recovery', 'Accelerates muscle repair, boosts cognition, improves performance consistency', '1300.00', '2000.00', 'critical', '85.00', '2025-08-18T20:00:38.371Z');
INSERT INTO budget_categories (id, category_name, category_description, why_it_matters, recommended_min_spend, recommended_max_spend, priority_level, expected_roi_percentage, created_at) VALUES (2, 'Nutrition & Meal Prep', 'Food services, supplements, and meal preparation tools', 'Fuels training, supports immunity, provides consistent energy levels', '1200.00', '1800.00', 'critical', '90.00', '2025-08-18T20:00:38.371Z');
INSERT INTO budget_categories (id, category_name, category_description, why_it_matters, recommended_min_spend, recommended_max_spend, priority_level, expected_roi_percentage, created_at) VALUES (3, 'Training & Coaching', 'Flag-specific coaching, strength programs, and skill development', 'Reduces injury risk, optimizes progress, improves technique', '1000.00', '2000.00', 'high', '75.00', '2025-08-18T20:00:38.371Z');
INSERT INTO budget_categories (id, category_name, category_description, why_it_matters, recommended_min_spend, recommended_max_spend, priority_level, expected_roi_percentage, created_at) VALUES (4, 'Preventive Medical & Bodywork', 'Physio check-ups, massage, mobility classes, and health screenings', 'Keeps athletes on the field, prevents injuries, maintains health', '700.00', '1500.00', 'high', '80.00', '2025-08-18T20:00:38.371Z');
INSERT INTO budget_categories (id, category_name, category_description, why_it_matters, recommended_min_spend, recommended_max_spend, priority_level, expected_roi_percentage, created_at) VALUES (5, 'Sport-Science Tooling', 'GPS trackers, heart rate monitors, and analytics platforms', 'Provides objective data for smarter training decisions', '500.00', '900.00', 'medium', '70.00', '2025-08-18T20:00:38.371Z');
INSERT INTO budget_categories (id, category_name, category_description, why_it_matters, recommended_min_spend, recommended_max_spend, priority_level, expected_roi_percentage, created_at) VALUES (6, 'Evidence-Based Supplements', 'Creatine, caffeine, beta-alanine, and other proven supplements', 'Small but meaningful performance edge with scientific backing', '300.00', '600.00', 'medium', '60.00', '2025-08-18T20:00:38.371Z');
INSERT INTO budget_categories (id, category_name, category_description, why_it_matters, recommended_min_spend, recommended_max_spend, priority_level, expected_roi_percentage, created_at) VALUES (7, 'Competition & Travel Buffer', 'Tournament costs, travel expenses, and contingency funds', 'Ensures participation in competitions and handles unexpected costs', '0.00', '1000.00', 'low', '50.00', '2025-08-18T20:00:38.371Z');
