-- Data for table: equipment_alternatives_comparison
-- Generated: 2025-12-01T20:59:19.198Z

INSERT INTO equipment_alternatives_comparison (id, primary_equipment_id, alternative_name, alternative_cost_euros, effectiveness_comparison, convenience_rating, space_requirements, setup_time_minutes, maintenance_effort, notes, created_at) VALUES (1, 7, 'Bathtub with Ice', '5.00', '0.70', 3, 'bathroom', 15, 'low', 'Uses existing bathtub, requires ice purchase each time', '2025-08-18T20:19:58.719Z');
INSERT INTO equipment_alternatives_comparison (id, primary_equipment_id, alternative_name, alternative_cost_euros, effectiveness_comparison, convenience_rating, space_requirements, setup_time_minutes, maintenance_effort, notes, created_at) VALUES (2, 7, 'Large Storage Bin', '20.00', '0.60', 4, 'garage_backyard', 10, 'low', 'Cheap alternative but less comfortable and portable', '2025-08-18T20:19:58.719Z');
INSERT INTO equipment_alternatives_comparison (id, primary_equipment_id, alternative_name, alternative_cost_euros, effectiveness_comparison, convenience_rating, space_requirements, setup_time_minutes, maintenance_effort, notes, created_at) VALUES (3, 7, 'Professional Cryotherapy', '50.00', '1.00', 9, 'clinic', 5, 'none', 'Most effective but expensive and requires travel', '2025-08-18T20:19:58.719Z');
INSERT INTO equipment_alternatives_comparison (id, primary_equipment_id, alternative_name, alternative_cost_euros, effectiveness_comparison, convenience_rating, space_requirements, setup_time_minutes, maintenance_effort, notes, created_at) VALUES (4, 1, 'Tennis Ball', '2.00', '0.50', 6, 'anywhere', 2, 'low', 'Good for targeted areas but limited coverage', '2025-08-18T20:19:58.719Z');
INSERT INTO equipment_alternatives_comparison (id, primary_equipment_id, alternative_name, alternative_cost_euros, effectiveness_comparison, convenience_rating, space_requirements, setup_time_minutes, maintenance_effort, notes, created_at) VALUES (5, 1, 'Water Bottle', '1.00', '0.40', 5, 'anywhere', 2, 'low', 'Basic alternative but not ideal for rolling', '2025-08-18T20:19:58.719Z');
INSERT INTO equipment_alternatives_comparison (id, primary_equipment_id, alternative_name, alternative_cost_euros, effectiveness_comparison, convenience_rating, space_requirements, setup_time_minutes, maintenance_effort, notes, created_at) VALUES (6, 1, 'Rolled Towel', '0.00', '0.30', 4, 'anywhere', 3, 'low', 'Free but very limited effectiveness', '2025-08-18T20:19:58.719Z');
INSERT INTO equipment_alternatives_comparison (id, primary_equipment_id, alternative_name, alternative_cost_euros, effectiveness_comparison, convenience_rating, space_requirements, setup_time_minutes, maintenance_effort, notes, created_at) VALUES (7, 2, 'Bodyweight Exercises', '0.00', '0.80', 7, 'anywhere', 1, 'none', 'Free and effective but limited resistance progression', '2025-08-18T20:19:58.719Z');
INSERT INTO equipment_alternatives_comparison (id, primary_equipment_id, alternative_name, alternative_cost_euros, effectiveness_comparison, convenience_rating, space_requirements, setup_time_minutes, maintenance_effort, notes, created_at) VALUES (8, 2, 'Water Jugs', '5.00', '0.60', 4, 'home', 5, 'low', 'Cheap alternative but awkward to use', '2025-08-18T20:19:58.719Z');
INSERT INTO equipment_alternatives_comparison (id, primary_equipment_id, alternative_name, alternative_cost_euros, effectiveness_comparison, convenience_rating, space_requirements, setup_time_minutes, maintenance_effort, notes, created_at) VALUES (9, 2, 'Household Items', '0.00', '0.40', 3, 'home', 10, 'low', 'Free but limited and potentially unsafe', '2025-08-18T20:19:58.719Z');
