-- Data for table: implementation_steps
-- Generated: 2025-12-01T20:59:18.232Z

INSERT INTO implementation_steps (id, user_id, step_name, step_description, step_category, step_order, estimated_duration_days, dependencies, required_resources, success_criteria, step_status, start_date, completion_date, actual_duration_days, notes, created_at, updated_at) VALUES (1, 'f31b59e5-8a73-4afb-a444-f80b728a8a54', 'Baseline Testing', 'Complete comprehensive baseline testing for body composition, sprint time, HRV, and FMS screen', 'baseline_testing', 1, 3, '[]', '["testing_equipment","qualified_tester"]', '["all_tests_completed","baseline_data_recorded","testing_report_generated"]', 'pending', NULL, NULL, NULL, NULL, '2025-08-18T20:02:58.773Z', '2025-08-18T20:02:58.773Z');
INSERT INTO implementation_steps (id, user_id, step_name, step_description, step_category, step_order, estimated_duration_days, dependencies, required_resources, success_criteria, step_status, start_date, completion_date, actual_duration_days, notes, created_at, updated_at) VALUES (2, 'f31b59e5-8a73-4afb-a444-f80b728a8a54', 'Budget Allocation', 'Pre-pay core technology and secure shared resources', 'budget_allocation', 2, 2, '["Baseline Testing"]', '["financial_resources","budget_plan"]', '["core_tech_purchased","shared_resources_secured","budget_tracking_setup"]', 'pending', NULL, NULL, NULL, NULL, '2025-08-18T20:02:58.773Z', '2025-08-18T20:02:58.773Z');
INSERT INTO implementation_steps (id, user_id, step_name, step_description, step_category, step_order, estimated_duration_days, dependencies, required_resources, success_criteria, step_status, start_date, completion_date, actual_duration_days, notes, created_at, updated_at) VALUES (3, 'f31b59e5-8a73-4afb-a444-f80b728a8a54', 'Personalized Plan Build', 'Create vegan vs. omnivore nutrition templates and individual supplement checklists', 'plan_building', 3, 5, '["Baseline Testing"]', '["nutrition_expertise","supplement_knowledge"]', '["nutrition_templates_created","supplement_checklists_completed","plan_personalized"]', 'pending', NULL, NULL, NULL, NULL, '2025-08-18T20:02:58.773Z', '2025-08-18T20:02:58.773Z');
INSERT INTO implementation_steps (id, user_id, step_name, step_description, step_category, step_order, estimated_duration_days, dependencies, required_resources, success_criteria, step_status, start_date, completion_date, actual_duration_days, notes, created_at, updated_at) VALUES (4, 'f31b59e5-8a73-4afb-a444-f80b728a8a54', 'Education Blitz', 'Four 60-minute clinics on sleep, nutrition, training, and recovery', 'education', 4, 7, '["Personalized Plan Build"]', '["expert_presenters","facility_equipment"]', '["clinics_delivered","recordings_created","materials_distributed"]', 'pending', NULL, NULL, NULL, NULL, '2025-08-18T20:02:58.773Z', '2025-08-18T20:02:58.773Z');
INSERT INTO implementation_steps (id, user_id, step_name, step_description, step_category, step_order, estimated_duration_days, dependencies, required_resources, success_criteria, step_status, start_date, completion_date, actual_duration_days, notes, created_at, updated_at) VALUES (5, 'f31b59e5-8a73-4afb-a444-f80b728a8a54', 'Accountability Groups', 'Form 8-10 athlete mentor coach groups with weekly check-ins', 'accountability', 5, 3, '["Education Blitz"]', '["mentor_coaches","group_platforms"]', '["groups_formed","check_in_schedule_set","mentorship_relationships_established"]', 'pending', NULL, NULL, NULL, NULL, '2025-08-18T20:02:58.773Z', '2025-08-18T20:02:58.773Z');
INSERT INTO implementation_steps (id, user_id, step_name, step_description, step_category, step_order, estimated_duration_days, dependencies, required_resources, success_criteria, step_status, start_date, completion_date, actual_duration_days, notes, created_at, updated_at) VALUES (6, 'f31b59e5-8a73-4afb-a444-f80b728a8a54', 'Data Dashboard Launch', 'Launch simple tracking system for sleep, load, soreness, and hydration', 'dashboard', 6, 2, '["Accountability Groups"]', '["dashboard_platform","data_tracking_tools"]', '["dashboard_launched","users_trained","data_collection_started"]', 'pending', NULL, NULL, NULL, NULL, '2025-08-18T20:02:58.773Z', '2025-08-18T20:02:58.773Z');
