-- Data for table: performance_competencies
-- Generated: 2025-12-01T20:59:25.174Z

INSERT INTO performance_competencies (id, competency_name, competency_category, competency_description, position_specific, applicable_positions, competency_levels, assessment_methods, development_activities, benchmark_standards, evidence_level, created_at) VALUES (1, 'Route Running Precision', 'technical', 'Ability to execute precise routes with proper timing and spacing', TRUE, '["receiver","tight_end"]', '{"elite":"Exceptional route mastery with deception","advanced":"Precise timing and spacing","beginner":"Basic route understanding","intermediate":"Consistent route execution"}', '["video_analysis","coach_observation","timing_measurements"]', '["route_drills","timing_work","film_study"]', NULL, 'high', '2025-08-17T20:37:53.415Z');
INSERT INTO performance_competencies (id, competency_name, competency_category, competency_description, position_specific, applicable_positions, competency_levels, assessment_methods, development_activities, benchmark_standards, evidence_level, created_at) VALUES (2, 'Pass Rush Technique', 'technical', 'Effective pass rushing with proper hand placement and leverage', TRUE, '["defensive_end","linebacker"]', '{"elite":"Elite pass rush dominance","advanced":"Counter move effectiveness","beginner":"Basic pass rush moves","intermediate":"Multiple move repertoire"}', '["coach_evaluation","success_rate_analysis","opponent_feedback"]', '["pass_rush_drills","hand_fighting_practice","film_study"]', NULL, 'high', '2025-08-17T20:37:53.415Z');
INSERT INTO performance_competencies (id, competency_name, competency_category, competency_description, position_specific, applicable_positions, competency_levels, assessment_methods, development_activities, benchmark_standards, evidence_level, created_at) VALUES (3, 'Decision Making Speed', 'cognitive', 'Quick and accurate decision making under pressure', FALSE, '["quarterback","safety","linebacker"]', '{"elite":"Exceptional decision speed and accuracy","advanced":"Fast accurate decisions","beginner":"Basic decision making","intermediate":"Quick decisions"}', '["cognitive_testing","game_situation_analysis","reaction_time_tests"]', '["cognitive_training","situation_practice","pressure_simulation"]', NULL, 'high', '2025-08-17T20:37:53.415Z');
INSERT INTO performance_competencies (id, competency_name, competency_category, competency_description, position_specific, applicable_positions, competency_levels, assessment_methods, development_activities, benchmark_standards, evidence_level, created_at) VALUES (4, 'Team Chemistry', 'social', 'Ability to work effectively with teammates and build cohesion', FALSE, '["all"]', '{"elite":"Exceptional team building","advanced":"Strong leadership","beginner":"Basic teamwork","intermediate":"Good communication"}', '["peer_evaluations","coach_observations","team_surveys"]', '["team_building_activities","communication_practice","leadership_development"]', NULL, 'medium', '2025-08-17T20:37:53.415Z');
INSERT INTO performance_competencies (id, competency_name, competency_category, competency_description, position_specific, applicable_positions, competency_levels, assessment_methods, development_activities, benchmark_standards, evidence_level, created_at) VALUES (5, 'Route Running Precision', 'technical', 'Ability to execute precise routes with proper timing and spacing', TRUE, '["receiver","tight_end"]', '{"elite":"Exceptional route mastery with deception","advanced":"Precise timing and spacing","beginner":"Basic route understanding","intermediate":"Consistent route execution"}', '["video_analysis","coach_observation","timing_measurements"]', '["route_drills","timing_work","film_study"]', NULL, 'high', '2025-08-17T20:38:15.164Z');
INSERT INTO performance_competencies (id, competency_name, competency_category, competency_description, position_specific, applicable_positions, competency_levels, assessment_methods, development_activities, benchmark_standards, evidence_level, created_at) VALUES (6, 'Pass Rush Technique', 'technical', 'Effective pass rushing with proper hand placement and leverage', TRUE, '["defensive_end","linebacker"]', '{"elite":"Elite pass rush dominance","advanced":"Counter move effectiveness","beginner":"Basic pass rush moves","intermediate":"Multiple move repertoire"}', '["coach_evaluation","success_rate_analysis","opponent_feedback"]', '["pass_rush_drills","hand_fighting_practice","film_study"]', NULL, 'high', '2025-08-17T20:38:15.164Z');
INSERT INTO performance_competencies (id, competency_name, competency_category, competency_description, position_specific, applicable_positions, competency_levels, assessment_methods, development_activities, benchmark_standards, evidence_level, created_at) VALUES (7, 'Decision Making Speed', 'cognitive', 'Quick and accurate decision making under pressure', FALSE, '["quarterback","safety","linebacker"]', '{"elite":"Exceptional decision speed and accuracy","advanced":"Fast accurate decisions","beginner":"Basic decision making","intermediate":"Quick decisions"}', '["cognitive_testing","game_situation_analysis","reaction_time_tests"]', '["cognitive_training","situation_practice","pressure_simulation"]', NULL, 'high', '2025-08-17T20:38:15.164Z');
INSERT INTO performance_competencies (id, competency_name, competency_category, competency_description, position_specific, applicable_positions, competency_levels, assessment_methods, development_activities, benchmark_standards, evidence_level, created_at) VALUES (8, 'Team Chemistry', 'social', 'Ability to work effectively with teammates and build cohesion', FALSE, '["all"]', '{"elite":"Exceptional team building","advanced":"Strong leadership","beginner":"Basic teamwork","intermediate":"Good communication"}', '["peer_evaluations","coach_observations","team_surveys"]', '["team_building_activities","communication_practice","leadership_development"]', NULL, 'medium', '2025-08-17T20:38:15.164Z');
