-- Data for table: realistic_budget_categories
-- Generated: 2025-12-01T20:59:19.105Z

INSERT INTO realistic_budget_categories (id, category_name, category_description, why_it_matters, min_spend_euros, max_spend_euros, priority_level, expected_roi_percentage, diy_alternatives, local_resource_options, created_at) VALUES (1, 'Basic Recovery Tools', 'Essential recovery equipment for home use', 'Prevents injuries, improves recovery, affordable investment', '50.00', '200.00', 'critical', '80.00', '["foam_rolling","stretching","ice_baths"]', '["sports_stores","online_retailers","second_hand"]', '2025-08-18T20:14:28.669Z');
INSERT INTO realistic_budget_categories (id, category_name, category_description, why_it_matters, min_spend_euros, max_spend_euros, priority_level, expected_roi_percentage, diy_alternatives, local_resource_options, created_at) VALUES (2, 'Nutrition Basics', 'Protein powder, basic supplements, meal planning', 'Fuels training, supports recovery, cost-effective nutrition', '100.00', '300.00', 'critical', '85.00', '["home_cooking","meal_prep","local_produce"]', '["supermarkets","health_stores","bulk_stores"]', '2025-08-18T20:14:28.669Z');
INSERT INTO realistic_budget_categories (id, category_name, category_description, why_it_matters, min_spend_euros, max_spend_euros, priority_level, expected_roi_percentage, diy_alternatives, local_resource_options, created_at) VALUES (3, 'Personal Training', '1-2 sessions per month with qualified coach', 'Improves technique, prevents injuries, personalized guidance', '80.00', '200.00', 'high', '75.00', '["online_coaching","team_practices","self_study"]', '["local_coaches","team_coaches","online_platforms"]', '2025-08-18T20:14:28.669Z');
INSERT INTO realistic_budget_categories (id, category_name, category_description, why_it_matters, min_spend_euros, max_spend_euros, priority_level, expected_roi_percentage, diy_alternatives, local_resource_options, created_at) VALUES (4, 'Basic Equipment', 'Personal gear, training tools, measurement devices', 'Enables training, tracks progress, long-term investment', '100.00', '300.00', 'high', '70.00', '["bodyweight_exercises","household_items","public_parks"]', '["sports_stores","online_retailers","community_centers"]', '2025-08-18T20:14:28.669Z');
INSERT INTO realistic_budget_categories (id, category_name, category_description, why_it_matters, min_spend_euros, max_spend_euros, priority_level, expected_roi_percentage, diy_alternatives, local_resource_options, created_at) VALUES (5, 'Health Screenings', 'Annual basic health check, injury assessment', 'Prevents serious issues, early intervention', '50.00', '150.00', 'medium', '90.00', '["self_assessment","team_screening","free_clinics"]', '["local_clinics","sports_medicine","community_health"]', '2025-08-18T20:14:28.669Z');
INSERT INTO realistic_budget_categories (id, category_name, category_description, why_it_matters, min_spend_euros, max_spend_euros, priority_level, expected_roi_percentage, diy_alternatives, local_resource_options, created_at) VALUES (6, 'Performance Apps', 'Training apps, nutrition tracking, recovery monitoring', 'Affordable technology, data-driven decisions', '20.00', '100.00', 'medium', '60.00', '["free_apps","manual_tracking","spreadsheets"]', '["app_stores","online_platforms","free_alternatives"]', '2025-08-18T20:14:28.669Z');
INSERT INTO realistic_budget_categories (id, category_name, category_description, why_it_matters, min_spend_euros, max_spend_euros, priority_level, expected_roi_percentage, diy_alternatives, local_resource_options, created_at) VALUES (7, 'Tournament Fees', 'Local and regional competition entry fees', 'Game experience, skill development, motivation', '50.00', '200.00', 'low', '50.00', '["friendly_games","practice_matches","local_leagues"]', '["local_clubs","regional_federations","community_events"]', '2025-08-18T20:14:28.669Z');
