-- Data for table: flag_football_positions
-- Generated: 2025-12-02T20:27:57.540Z

INSERT INTO flag_football_positions (id, position_name, position_category, primary_responsibilities, physical_requirements, technical_skills, tactical_understanding, created_at) VALUES (1, 'Quarterback', 'offense', '["Pass the ball","Read defenses","Call plays","Lead offense"]', '{"leadership":"essential","arm_strength":"high","decision_making":"critical"}', '["Throwing accuracy","Footwork","Pocket presence","Reading defenses"]', '["Defensive formations","Coverage schemes","Blitz recognition","Clock management"]', '2025-08-17T20:08:18.752Z');
INSERT INTO flag_football_positions (id, position_name, position_category, primary_responsibilities, physical_requirements, technical_skills, tactical_understanding, created_at) VALUES (2, 'Wide Receiver', 'offense', '["Run routes","Catch passes","Block for runners","Create separation"]', '{"speed":"high","agility":"high","hand_eye_coordination":"critical"}', '["Route running","Hands","Speed","Blocking technique"]', '["Route concepts","Coverage recognition","Field awareness","Timing"]', '2025-08-17T20:08:18.752Z');
INSERT INTO flag_football_positions (id, position_name, position_category, primary_responsibilities, physical_requirements, technical_skills, tactical_understanding, created_at) VALUES (3, 'Running Back', 'offense', '["Run the ball","Catch passes","Pass protection","Block for others"]', '{"power":"medium","speed":"high","vision":"critical","balance":"high"}', '["Ball security","Cutting ability","Pass catching","Pass protection"]', '["Gap recognition","Defensive reading","Clock management","Field position"]', '2025-08-17T20:08:18.752Z');
INSERT INTO flag_football_positions (id, position_name, position_category, primary_responsibilities, physical_requirements, technical_skills, tactical_understanding, created_at) VALUES (4, 'Center', 'offense', '["Snap the ball","Block defenders","Call blocking assignments","Protect quarterback"]', '{"strength":"high","intelligence":"high","communication":"critical"}', '["Snapping","Blocking technique","Line calls","Pass protection"]', '["Defensive fronts","Blitz recognition","Gap assignments","Line communication"]', '2025-08-17T20:08:18.752Z');
INSERT INTO flag_football_positions (id, position_name, position_category, primary_responsibilities, physical_requirements, technical_skills, tactical_understanding, created_at) VALUES (5, 'Defensive End', 'defense', '["Rush the passer","Stop the run","Contain the edge","Pressure quarterback"]', '{"power":"high","speed":"medium","agility":"medium","strength":"high"}', '["Pass rush moves","Tackling","Block shedding","Edge setting"]', '["Run fits","Pass rush lanes","Gap responsibility","Field awareness"]', '2025-08-17T20:08:18.752Z');
INSERT INTO flag_football_positions (id, position_name, position_category, primary_responsibilities, physical_requirements, technical_skills, tactical_understanding, created_at) VALUES (6, 'Linebacker', 'defense', '["Stop the run","Cover receivers","Blitz the quarterback","Tackle ball carriers"]', '{"power":"medium","speed":"medium","agility":"high","instincts":"critical"}', '["Tackling","Coverage","Blitzing","Block shedding"]', '["Run fits","Coverage schemes","Blitz timing","Field awareness"]', '2025-08-17T20:08:18.752Z');
INSERT INTO flag_football_positions (id, position_name, position_category, primary_responsibilities, physical_requirements, technical_skills, tactical_understanding, created_at) VALUES (7, 'Cornerback', 'defense', '["Cover receivers","Tackle runners","Intercept passes","Support run defense"]', '{"speed":"high","agility":"high","ball_skills":"high","recovery_speed":"critical"}', '["Man coverage","Zone coverage","Tackling","Ball skills"]', '["Coverage schemes","Route recognition","Field awareness","Tackling angles"]', '2025-08-17T20:08:18.752Z');
INSERT INTO flag_football_positions (id, position_name, position_category, primary_responsibilities, physical_requirements, technical_skills, tactical_understanding, created_at) VALUES (8, 'Safety', 'defense', '["Cover deep zones","Support run defense","Cover tight ends","Provide help coverage"]', '{"speed":"high","coverage":"high","tackling":"high","instincts":"critical"}', '["Zone coverage","Tackling","Ball skills","Communication"]', '["Coverage schemes","Run fits","Communication","Field awareness"]', '2025-08-17T20:08:18.752Z');
INSERT INTO flag_football_positions (id, position_name, position_category, primary_responsibilities, physical_requirements, technical_skills, tactical_understanding, created_at) VALUES (9, 'Kicker', 'special_teams', '["Kick field goals","Kick extra points","Kick offs","Onside kicks"]', '{"accuracy":"critical","consistency":"essential","leg_strength":"high"}', '["Kicking technique","Ball placement","Follow through","Mental focus"]', '["Field position","Clock management","Weather conditions","Pressure situations"]', '2025-08-17T20:08:18.752Z');
INSERT INTO flag_football_positions (id, position_name, position_category, primary_responsibilities, physical_requirements, technical_skills, tactical_understanding, created_at) VALUES (10, 'Punter', 'special_teams', '["Punt the ball","Directional punting","Hang time","Field position"]', '{"accuracy":"critical","consistency":"essential","leg_strength":"high"}', '["Punting technique","Ball placement","Directional control","Hang time"]', '["Field position","Clock management","Weather conditions","Coverage support"]', '2025-08-17T20:08:18.752Z');
