-- Data for table: local_premium_alternatives
-- Generated: 2025-12-02T20:27:56.072Z

INSERT INTO local_premium_alternatives (id, premium_brand_id, local_alternative_type, local_alternative_name, local_alternative_cost_euros, accessibility_rating, effectiveness_comparison, location_requirements, availability_notes, created_at) VALUES (1, 1, 'physio', 'Local Physiotherapist', '60.00', 7, '0.90', 'local_clinic', 'Professional treatment, much cheaper than buying equipment', '2025-08-18T20:24:57.039Z');
INSERT INTO local_premium_alternatives (id, premium_brand_id, local_alternative_type, local_alternative_name, local_alternative_cost_euros, accessibility_rating, effectiveness_comparison, location_requirements, availability_notes, created_at) VALUES (2, 1, 'gym', 'Gym Recovery Room', '30.00', 6, '0.75', 'local_gym', 'Access to professional equipment, monthly membership cost', '2025-08-18T20:24:57.039Z');
INSERT INTO local_premium_alternatives (id, premium_brand_id, local_alternative_type, local_alternative_name, local_alternative_cost_euros, accessibility_rating, effectiveness_comparison, location_requirements, availability_notes, created_at) VALUES (3, 1, 'community_center', 'Community Recovery Classes', '15.00', 8, '0.70', 'community_center', 'Group sessions, very affordable, good for beginners', '2025-08-18T20:24:57.039Z');
INSERT INTO local_premium_alternatives (id, premium_brand_id, local_alternative_type, local_alternative_name, local_alternative_cost_euros, accessibility_rating, effectiveness_comparison, location_requirements, availability_notes, created_at) VALUES (4, 2, 'sports_club', 'Team Recovery Sessions', '20.00', 9, '0.80', 'local_sports_club', 'Team-based recovery, very affordable, good for motivation', '2025-08-18T20:24:57.039Z');
INSERT INTO local_premium_alternatives (id, premium_brand_id, local_alternative_type, local_alternative_name, local_alternative_cost_euros, accessibility_rating, effectiveness_comparison, location_requirements, availability_notes, created_at) VALUES (5, 2, 'gym', 'Gym Recovery Equipment', '40.00', 7, '0.85', 'local_gym', 'Access to quality equipment, monthly cost spread out', '2025-08-18T20:24:57.039Z');
INSERT INTO local_premium_alternatives (id, premium_brand_id, local_alternative_type, local_alternative_name, local_alternative_cost_euros, accessibility_rating, effectiveness_comparison, location_requirements, availability_notes, created_at) VALUES (6, 3, 'physio', 'Professional Physiotherapy', '80.00', 6, '0.95', 'local_clinic', 'Professional treatment, highest effectiveness, reasonable cost', '2025-08-18T20:24:57.039Z');
INSERT INTO local_premium_alternatives (id, premium_brand_id, local_alternative_type, local_alternative_name, local_alternative_cost_euros, accessibility_rating, effectiveness_comparison, location_requirements, availability_notes, created_at) VALUES (7, 3, 'community_center', 'Community Health Programs', '25.00', 8, '0.60', 'community_center', 'Basic health services, very affordable, good for prevention', '2025-08-18T20:24:57.039Z');
INSERT INTO local_premium_alternatives (id, premium_brand_id, local_alternative_type, local_alternative_name, local_alternative_cost_euros, accessibility_rating, effectiveness_comparison, location_requirements, availability_notes, created_at) VALUES (8, 4, 'sports_club', 'Performance Training Classes', '35.00', 7, '0.85', 'local_sports_club', 'Professional coaching, good for skill development', '2025-08-18T20:24:57.039Z');
INSERT INTO local_premium_alternatives (id, premium_brand_id, local_alternative_type, local_alternative_name, local_alternative_cost_euros, accessibility_rating, effectiveness_comparison, location_requirements, availability_notes, created_at) VALUES (9, 4, 'community_center', 'Community Sports Programs', '20.00', 9, '0.70', 'community_center', 'Group training, very affordable, good for beginners', '2025-08-18T20:24:57.039Z');
INSERT INTO local_premium_alternatives (id, premium_brand_id, local_alternative_type, local_alternative_name, local_alternative_cost_euros, accessibility_rating, effectiveness_comparison, location_requirements, availability_notes, created_at) VALUES (10, 5, 'medical_center', 'Medical Rehabilitation Center', '100.00', 5, '0.95', 'medical_facility', 'Professional medical treatment, highest quality, expensive but covered by insurance', '2025-08-18T20:24:57.039Z');
INSERT INTO local_premium_alternatives (id, premium_brand_id, local_alternative_type, local_alternative_name, local_alternative_cost_euros, accessibility_rating, effectiveness_comparison, location_requirements, availability_notes, created_at) VALUES (11, 5, 'community_center', 'Community Health Center', '30.00', 8, '0.70', 'community_center', 'Basic health services, very affordable, good for maintenance', '2025-08-18T20:24:57.039Z');
