-- Data for table: nfl_combine_performances
-- Generated: 2025-12-02T20:28:01.369Z

INSERT INTO nfl_combine_performances (id, player_name, position, college, draft_year, draft_round, draft_pick, height_inches, weight_pounds, forty_yard_dash, ten_yard_split, twenty_yard_split, three_cone_drill, twenty_yard_shuttle, vertical_jump, broad_jump, bench_press_reps, nfl_seasons_played, career_achievements, career_stats, success_rating, combine_year, notable_achievements, current_status, created_at) VALUES (1, 'Xavier Worthy', 'WR', 'Texas', 2024, NULL, NULL, NULL, NULL, '4.21', '1.42', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["NFL_Record_Holder"]', NULL, 8, NULL, NULL, 'Active', '2025-08-17T17:44:49.392Z');
INSERT INTO nfl_combine_performances (id, player_name, position, college, draft_year, draft_round, draft_pick, height_inches, weight_pounds, forty_yard_dash, ten_yard_split, twenty_yard_split, three_cone_drill, twenty_yard_shuttle, vertical_jump, broad_jump, bench_press_reps, nfl_seasons_played, career_achievements, career_stats, success_rating, combine_year, notable_achievements, current_status, created_at) VALUES (2, 'Jerry Rice', 'WR', 'Mississippi Valley State', 1985, NULL, NULL, NULL, NULL, '4.59', '1.65', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["Hall_of_Fame","Super_Bowl","All_Pro"]', NULL, 10, NULL, NULL, 'Hall_of_Fame', '2025-08-17T17:44:49.514Z');
INSERT INTO nfl_combine_performances (id, player_name, position, college, draft_year, draft_round, draft_pick, height_inches, weight_pounds, forty_yard_dash, ten_yard_split, twenty_yard_split, three_cone_drill, twenty_yard_shuttle, vertical_jump, broad_jump, bench_press_reps, nfl_seasons_played, career_achievements, career_stats, success_rating, combine_year, notable_achievements, current_status, created_at) VALUES (3, 'Hines Ward', 'WR', 'Georgia', 1998, NULL, NULL, NULL, NULL, '4.68', '1.72', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["Pro_Bowl","Super_Bowl"]', NULL, 8, NULL, NULL, 'Retired', '2025-08-17T17:44:49.556Z');
INSERT INTO nfl_combine_performances (id, player_name, position, college, draft_year, draft_round, draft_pick, height_inches, weight_pounds, forty_yard_dash, ten_yard_split, twenty_yard_split, three_cone_drill, twenty_yard_shuttle, vertical_jump, broad_jump, bench_press_reps, nfl_seasons_played, career_achievements, career_stats, success_rating, combine_year, notable_achievements, current_status, created_at) VALUES (4, 'Cooper Kupp', 'WR', 'Eastern Washington', 2017, NULL, NULL, NULL, NULL, '4.62', '1.68', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["All_Pro","Triple_Crown"]', NULL, 9, NULL, NULL, 'Active', '2025-08-17T17:44:49.595Z');
INSERT INTO nfl_combine_performances (id, player_name, position, college, draft_year, draft_round, draft_pick, height_inches, weight_pounds, forty_yard_dash, ten_yard_split, twenty_yard_split, three_cone_drill, twenty_yard_shuttle, vertical_jump, broad_jump, bench_press_reps, nfl_seasons_played, career_achievements, career_stats, success_rating, combine_year, notable_achievements, current_status, created_at) VALUES (5, 'Wes Welker', 'WR', 'Texas Tech', 2004, NULL, NULL, NULL, NULL, '4.65', '1.70', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["Pro_Bowl","All_Pro"]', NULL, 8, NULL, NULL, 'Retired', '2025-08-17T17:44:49.638Z');
INSERT INTO nfl_combine_performances (id, player_name, position, college, draft_year, draft_round, draft_pick, height_inches, weight_pounds, forty_yard_dash, ten_yard_split, twenty_yard_split, three_cone_drill, twenty_yard_shuttle, vertical_jump, broad_jump, bench_press_reps, nfl_seasons_played, career_achievements, career_stats, success_rating, combine_year, notable_achievements, current_status, created_at) VALUES (6, 'Deion Sanders', 'CB', 'Florida State', 1989, NULL, NULL, NULL, NULL, '4.21', '1.45', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["Hall_of_Fame","Super_Bowl","All_Pro"]', NULL, 10, NULL, NULL, 'Hall_of_Fame', '2025-08-17T17:44:49.679Z');
INSERT INTO nfl_combine_performances (id, player_name, position, college, draft_year, draft_round, draft_pick, height_inches, weight_pounds, forty_yard_dash, ten_yard_split, twenty_yard_split, three_cone_drill, twenty_yard_shuttle, vertical_jump, broad_jump, bench_press_reps, nfl_seasons_played, career_achievements, career_stats, success_rating, combine_year, notable_achievements, current_status, created_at) VALUES (7, 'Adam Thielen', 'WR', 'Minnesota State', 2013, NULL, NULL, NULL, NULL, '4.64', '1.70', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '["Pro_Bowl"]', NULL, 7, NULL, NULL, 'Active', '2025-08-17T17:44:49.720Z');
