-- Data for table: performance_plan_templates
-- Generated: 2025-12-02T20:27:57.446Z

INSERT INTO performance_plan_templates (id, template_name, template_description, template_category, target_athlete_type, budget_range_min, budget_range_max, timeline_weeks, core_pillars, recommended_resources, success_metrics, template_status, created_at, updated_at) VALUES (1, 'Amateur Performance Foundation', 'Comprehensive performance plan for amateur flag football players with €5,000-€10,000 budget', 'intermediate', 'competitive', '5000.00', '10000.00', 52, '["sleep_recovery","nutrition_meal_prep","training_coaching","preventive_medical","sport_science","supplements","competition_travel"]', '["smart_ring_watch","high_end_mattress","compression_boots","gps_tracker","heart_rate_monitor"]', '["sleep_improvement","strength_gains","injury_reduction","performance_improvement"]', 'active', '2025-08-18T20:02:01.347Z', '2025-08-18T20:02:01.347Z');
INSERT INTO performance_plan_templates (id, template_name, template_description, template_category, target_athlete_type, budget_range_min, budget_range_max, timeline_weeks, core_pillars, recommended_resources, success_metrics, template_status, created_at, updated_at) VALUES (2, 'Elite Performance Optimization', 'Advanced performance plan for elite flag football players with €15,000-€25,000 budget', 'advanced', 'elite', '15000.00', '25000.00', 52, '["advanced_recovery","premium_nutrition","elite_coaching","comprehensive_medical","advanced_analytics","premium_supplements","international_travel"]', '["cryo_sauna","hyperbaric_chamber","personal_chef","biomechanical_analysis"]', '["elite_performance","international_competition","professional_development"]', 'active', '2025-08-18T20:02:01.347Z', '2025-08-18T20:02:01.347Z');
INSERT INTO performance_plan_templates (id, template_name, template_description, template_category, target_athlete_type, budget_range_min, budget_range_max, timeline_weeks, core_pillars, recommended_resources, success_metrics, template_status, created_at, updated_at) VALUES (3, 'Recreational Performance Starter', 'Basic performance plan for recreational flag football players with €2,000-€5,000 budget', 'beginner', 'recreational', '2000.00', '5000.00', 26, '["basic_recovery","nutrition_basics","fundamental_training","basic_health","simple_tracking"]', '["basic_sleep_tracker","foam_roller","protein_powder","simple_apps"]', '["basic_fitness","injury_prevention","enjoyment_improvement"]', 'active', '2025-08-18T20:02:01.347Z', '2025-08-18T20:02:01.347Z');
INSERT INTO performance_plan_templates (id, template_name, template_description, template_category, target_athlete_type, budget_range_min, budget_range_max, timeline_weeks, core_pillars, recommended_resources, success_metrics, template_status, created_at, updated_at) VALUES (4, 'Amateur Performance Foundation', 'Comprehensive performance plan for amateur flag football players with €5,000-€10,000 budget', 'intermediate', 'competitive', '5000.00', '10000.00', 52, '["sleep_recovery","nutrition_meal_prep","training_coaching","preventive_medical","sport_science","supplements","competition_travel"]', '["smart_ring_watch","high_end_mattress","compression_boots","gps_tracker","heart_rate_monitor"]', '["sleep_improvement","strength_gains","injury_reduction","performance_improvement"]', 'active', '2025-08-18T20:02:58.887Z', '2025-08-18T20:02:58.887Z');
INSERT INTO performance_plan_templates (id, template_name, template_description, template_category, target_athlete_type, budget_range_min, budget_range_max, timeline_weeks, core_pillars, recommended_resources, success_metrics, template_status, created_at, updated_at) VALUES (5, 'Elite Performance Optimization', 'Advanced performance plan for elite flag football players with €15,000-€25,000 budget', 'advanced', 'elite', '15000.00', '25000.00', 52, '["advanced_recovery","premium_nutrition","elite_coaching","comprehensive_medical","advanced_analytics","premium_supplements","international_travel"]', '["cryo_sauna","hyperbaric_chamber","personal_chef","biomechanical_analysis"]', '["elite_performance","international_competition","professional_development"]', 'active', '2025-08-18T20:02:58.887Z', '2025-08-18T20:02:58.887Z');
INSERT INTO performance_plan_templates (id, template_name, template_description, template_category, target_athlete_type, budget_range_min, budget_range_max, timeline_weeks, core_pillars, recommended_resources, success_metrics, template_status, created_at, updated_at) VALUES (6, 'Recreational Performance Starter', 'Basic performance plan for recreational flag football players with €2,000-€5,000 budget', 'beginner', 'recreational', '2000.00', '5000.00', 26, '["basic_recovery","nutrition_basics","fundamental_training","basic_health","simple_tracking"]', '["basic_sleep_tracker","foam_roller","protein_powder","simple_apps"]', '["basic_fitness","injury_prevention","enjoyment_improvement"]', 'active', '2025-08-18T20:02:58.887Z', '2025-08-18T20:02:58.887Z');
