-- Data for table: premium_product_alternatives
-- Generated: 2025-12-02T20:27:56.494Z

INSERT INTO premium_product_alternatives (id, premium_brand_id, premium_product_name, premium_product_price_euros, premium_product_features, affordable_alternative_name, affordable_alternative_price_euros, cost_savings_euros, effectiveness_comparison, alternative_source, alternative_notes, created_at) VALUES (1, 1, 'Hypervolt 2.0 Pro', '350.00', '["percussion_therapy","quiet_operation","professional_grade"]', 'Pulsio AIR Massage Gun', '80.00', '270.00', '0.85', 'Pulsio', 'Similar percussion therapy, 85% effectiveness, much more affordable', '2025-08-18T20:24:56.956Z');
INSERT INTO premium_product_alternatives (id, premium_brand_id, premium_product_name, premium_product_price_euros, premium_product_features, affordable_alternative_name, affordable_alternative_price_euros, cost_savings_euros, effectiveness_comparison, alternative_source, alternative_notes, created_at) VALUES (2, 1, 'Normatec 3 Legs', '800.00', '["compression_therapy","sequential_compression","medical_grade"]', 'Portable Ice Bath + Compression Sleeves', '120.00', '680.00', '0.70', 'DIY_Combination', 'Combined approach: cold therapy + compression, 70% effectiveness', '2025-08-18T20:24:56.956Z');
INSERT INTO premium_product_alternatives (id, premium_brand_id, premium_product_name, premium_product_price_euros, premium_product_features, affordable_alternative_name, affordable_alternative_price_euros, cost_savings_euros, effectiveness_comparison, alternative_source, alternative_notes, created_at) VALUES (3, 1, 'Venom 2 Back', '400.00', '["heat_therapy","targeted_relief","professional_quality"]', 'Heating Pad + Tennis Ball', '25.00', '375.00', '0.65', 'DIY_Combination', 'Basic heat + targeted pressure, 65% effectiveness', '2025-08-18T20:24:56.956Z');
INSERT INTO premium_product_alternatives (id, premium_brand_id, premium_product_name, premium_product_price_euros, premium_product_features, affordable_alternative_name, affordable_alternative_price_euros, cost_savings_euros, effectiveness_comparison, alternative_source, alternative_notes, created_at) VALUES (4, 2, 'Pulsio Compression Boots', '370.00', '["compression_therapy","adjustable_pressure","professional_quality"]', 'Compression Sleeves + Manual Massage', '50.00', '320.00', '0.75', 'DIY_Combination', 'Compression + manual techniques, 75% effectiveness', '2025-08-18T20:24:56.956Z');
INSERT INTO premium_product_alternatives (id, premium_brand_id, premium_product_name, premium_product_price_euros, premium_product_features, affordable_alternative_name, affordable_alternative_price_euros, cost_savings_euros, effectiveness_comparison, alternative_source, alternative_notes, created_at) VALUES (5, 2, 'Pulsio AIR Massage Gun', '80.00', '["percussion_therapy","portable","good_quality"]', 'Foam Roller + Tennis Ball', '30.00', '50.00', '0.80', 'DIY_Combination', 'Manual techniques, 80% effectiveness, great value', '2025-08-18T20:24:56.956Z');
INSERT INTO premium_product_alternatives (id, premium_brand_id, premium_product_name, premium_product_price_euros, premium_product_features, affordable_alternative_name, affordable_alternative_price_euros, cost_savings_euros, effectiveness_comparison, alternative_source, alternative_notes, created_at) VALUES (6, 2, 'Pulsio ELITE', '115.00', '["high_power","deep_tissue","professional_grade"]', 'Resistance Bands + Manual Techniques', '40.00', '75.00', '0.70', 'DIY_Combination', 'Resistance training + manual work, 70% effectiveness', '2025-08-18T20:24:56.956Z');
INSERT INTO premium_product_alternatives (id, premium_brand_id, premium_product_name, premium_product_price_euros, premium_product_features, affordable_alternative_name, affordable_alternative_price_euros, cost_savings_euros, effectiveness_comparison, alternative_source, alternative_notes, created_at) VALUES (7, 3, 'Tecar Therapy Device', '3000.00', '["radio_frequency","deep_heating","clinical_grade"]', 'Hot Water Bottle + Manual Techniques', '15.00', '2985.00', '0.50', 'DIY_Combination', 'Basic heat + manual work, 50% effectiveness but massive savings', '2025-08-18T20:24:56.956Z');
INSERT INTO premium_product_alternatives (id, premium_brand_id, premium_product_name, premium_product_price_euros, premium_product_features, affordable_alternative_name, affordable_alternative_price_euros, cost_savings_euros, effectiveness_comparison, alternative_source, alternative_notes, created_at) VALUES (8, 3, 'EMS Device', '800.00', '["electrical_stimulation","muscle_activation","professional_grade"]', 'Resistance Training + Bodyweight', '0.00', '800.00', '0.80', 'DIY_Alternative', 'Active training alternatives, 80% effectiveness, completely free', '2025-08-18T20:24:56.956Z');
INSERT INTO premium_product_alternatives (id, premium_brand_id, premium_product_name, premium_product_price_euros, premium_product_features, affordable_alternative_name, affordable_alternative_price_euros, cost_savings_euros, effectiveness_comparison, alternative_source, alternative_notes, created_at) VALUES (9, 3, 'Shockwave Device', '5000.00', '["acoustic_waves","tissue_regeneration","clinical_grade"]', 'Foam Rolling + Stretching', '30.00', '4970.00', '0.60', 'DIY_Alternative', 'Manual tissue work, 60% effectiveness, massive cost savings', '2025-08-18T20:24:56.956Z');
INSERT INTO premium_product_alternatives (id, premium_brand_id, premium_product_name, premium_product_price_euros, premium_product_features, affordable_alternative_name, affordable_alternative_price_euros, cost_savings_euros, effectiveness_comparison, alternative_source, alternative_notes, created_at) VALUES (10, 4, 'Blazepod Training Set', '300.00', '["smart_training","reaction_time","performance_tracking"]', 'DIY Agility Course + Stopwatch', '25.00', '275.00', '0.75', 'DIY_Alternative', 'Homemade agility course, 75% effectiveness, great for skill development', '2025-08-18T20:24:56.956Z');
INSERT INTO premium_product_alternatives (id, premium_brand_id, premium_product_name, premium_product_price_euros, premium_product_features, affordable_alternative_name, affordable_alternative_price_euros, cost_savings_euros, effectiveness_comparison, alternative_source, alternative_notes, created_at) VALUES (11, 4, 'Blazepod Reaction Trainer', '150.00', '["reaction_training","cognitive_development","portable"]', 'Tennis Ball + Partner', '5.00', '145.00', '0.80', 'DIY_Alternative', 'Partner-based reaction training, 80% effectiveness', '2025-08-18T20:24:56.956Z');
INSERT INTO premium_product_alternatives (id, premium_brand_id, premium_product_name, premium_product_price_euros, premium_product_features, affordable_alternative_name, affordable_alternative_price_euros, cost_savings_euros, effectiveness_comparison, alternative_source, alternative_notes, created_at) VALUES (12, 5, 'Professional Treadmill', '8000.00', '["cardio_training","performance_tracking","medical_grade"]', 'Local Park + Heart Rate Monitor', '80.00', '7920.00', '0.85', 'Local_Resources', 'Outdoor training + basic monitoring, 85% effectiveness', '2025-08-18T20:24:56.956Z');
INSERT INTO premium_product_alternatives (id, premium_brand_id, premium_product_name, premium_product_price_euros, premium_product_features, affordable_alternative_name, affordable_alternative_price_euros, cost_savings_euros, effectiveness_comparison, alternative_source, alternative_notes, created_at) VALUES (13, 5, 'Rehabilitation Equipment', '15000.00', '["clinical_rehabilitation","professional_grade","comprehensive"]', 'Local Physio + Home Exercises', '500.00', '14500.00', '0.90', 'Local_Resources', 'Professional guidance + home work, 90% effectiveness', '2025-08-18T20:24:56.956Z');
