-- Data for table: team_resources
-- Generated: 2025-12-02T20:27:56.259Z

INSERT INTO team_resources (id, resource_name, resource_type, resource_category, description, one_time_cost, per_athlete_share, total_athletes_capacity, current_utilization_percentage, ownership_model, location, availability_status, maintenance_schedule, insurance_coverage, depreciation_years, expected_lifespan_years, created_at, updated_at) VALUES (1, 'Mobile Cryo-Sauna Trailer', 'equipment', 'recovery', 'Portable cryotherapy unit for post-tournament recovery', '70000.00', '70.00', 1000, '0.00', 'community_owned', 'Mobile - travels to tournaments', 'available', '["monthly_cleaning","quarterly_inspection","annual_calibration"]', NULL, NULL, 8, '2025-08-18T20:01:06.150Z', '2025-08-18T20:01:06.150Z');
INSERT INTO team_resources (id, resource_name, resource_type, resource_category, description, one_time_cost, per_athlete_share, total_athletes_capacity, current_utilization_percentage, ownership_model, location, availability_status, maintenance_schedule, insurance_coverage, depreciation_years, expected_lifespan_years, created_at, updated_at) VALUES (2, 'Infrared Sauna Cabin (x3)', 'facility', 'recovery', 'Three infrared sauna units for year-round recovery sessions', '18000.00', '18.00', 1000, '0.00', 'community_owned', 'Main training facility', 'available', '["weekly_cleaning","monthly_inspection","quarterly_maintenance"]', NULL, NULL, 10, '2025-08-18T20:01:06.150Z', '2025-08-18T20:01:06.150Z');
INSERT INTO team_resources (id, resource_name, resource_type, resource_category, description, one_time_cost, per_athlete_share, total_athletes_capacity, current_utilization_percentage, ownership_model, location, availability_status, maintenance_schedule, insurance_coverage, depreciation_years, expected_lifespan_years, created_at, updated_at) VALUES (3, 'Team Hyperbaric Chamber', 'equipment', 'recovery', 'Hyperbaric oxygen therapy for injury and soft-tissue recovery', '22000.00', '22.00', 1000, '0.00', 'community_owned', 'Medical wing', 'available', '["daily_inspection","weekly_cleaning","monthly_calibration"]', NULL, NULL, 12, '2025-08-18T20:01:06.150Z', '2025-08-18T20:01:06.150Z');
INSERT INTO team_resources (id, resource_name, resource_type, resource_category, description, one_time_cost, per_athlete_share, total_athletes_capacity, current_utilization_percentage, ownership_model, location, availability_status, maintenance_schedule, insurance_coverage, depreciation_years, expected_lifespan_years, created_at, updated_at) VALUES (4, 'GPS Team Set (30 units)', 'technology', 'analytics', 'GPS tracking units for workload monitoring during practices', '15000.00', '15.00', 1000, '0.00', 'community_owned', 'Equipment room', 'available', '["weekly_charging","monthly_calibration","quarterly_software_update"]', NULL, NULL, 5, '2025-08-18T20:01:06.150Z', '2025-08-18T20:01:06.150Z');
INSERT INTO team_resources (id, resource_name, resource_type, resource_category, description, one_time_cost, per_athlete_share, total_athletes_capacity, current_utilization_percentage, ownership_model, location, availability_status, maintenance_schedule, insurance_coverage, depreciation_years, expected_lifespan_years, created_at, updated_at) VALUES (5, 'Group Dietitian Webinar Series (6)', 'service', 'nutrition', 'Six nutrition webinars covering plant-based and omnivore personalization', '6000.00', '6.00', 1000, '0.00', 'community_owned', 'Virtual platform', 'available', '["pre_webinar_testing","post_webinar_feedback"]', NULL, NULL, 1, '2025-08-18T20:01:06.150Z', '2025-08-18T20:01:06.150Z');
INSERT INTO team_resources (id, resource_name, resource_type, resource_category, description, one_time_cost, per_athlete_share, total_athletes_capacity, current_utilization_percentage, ownership_model, location, availability_status, maintenance_schedule, insurance_coverage, depreciation_years, expected_lifespan_years, created_at, updated_at) VALUES (6, 'Cognitive-Training Platform (1-yr license)', 'technology', 'training', 'Unlimited user seats for cognitive training and brain games', '10000.00', '10.00', 1000, '0.00', 'community_owned', 'Online platform', 'available', '["monthly_software_update","quarterly_performance_review"]', NULL, NULL, 1, '2025-08-18T20:01:06.150Z', '2025-08-18T20:01:06.150Z');
