-- mobility/recovery batch 2: 12 new exercise-catalog rows.
-- Skips near-duplicates already present: Pigeon Pose, World's Greatest Stretch, Child's Pose.
-- Idempotent on slug (unique constraint uq_exercises_slug) via WHERE NOT EXISTS.

INSERT INTO public.exercises (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.* FROM (VALUES
  ('Cat-Cow', 'cat-cow', 'mobility', 'spine_mobility', 'Mobility', 'Alternating spinal flexion and extension on hands and knees -- a foundational spine-mobility reset used at the start of nearly any warm-up or recovery session.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'On hands and knees, alternate arching the back up toward the ceiling (cat) and dropping the belly down while lifting the chest (cow), moving slowly with the breath.', 'A gentle wave of movement through the entire spine, releasing tension segment by segment.', 'Do not force the range; let the movement stay slow and breath-paced.', 1, NULL::text[], NULL::text[], 'beginner', 1, 10, NULL::integer, true, false),
  ('Couch Stretch (Hip Flexor)', 'couch-stretch-hip-flexor', 'mobility', 'hip_mobility', 'Mobility', 'Deep hip-flexor and quad stretch with the rear shin supported vertically -- addresses the tight hip flexors common from repeated sprinting.', NULL, '{"Bench or Wall"}'::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Kneel with the rear shin propped vertically against a wall or bench, and drive the hips forward while keeping the torso upright.', 'A deep stretch through the front of the hip and quad of the rear leg.', 'Do not let the lower back arch to increase the stretch; keep the core braced and the hips squared.', 2, NULL::text[], NULL::text[], 'moderate', 1, NULL::integer, 40, true, false),
  ('Seated Figure-4 Stretch', 'seated-figure-4-stretch', 'mobility', 'hip_mobility', 'Mobility', 'Seated glute and piriformis stretch using a figure-4 leg position -- a simple, accessible alternative to Pigeon Pose.', NULL, '{"Chair"}'::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Sitting in a chair, cross one ankle over the opposite knee, and gently lean the torso forward while keeping the back flat.', 'A deep stretch through the glute of the crossed leg.', 'Do not round the lower back to increase the lean; hinge from the hips with a flat back.', 1, NULL::text[], NULL::text[], 'beginner', 1, NULL::integer, 30, true, false),
  ('Standing Quad Stretch', 'standing-quad-stretch', 'mobility', 'lower_body', 'Mobility', 'Standing stretch for the quadriceps -- a basic mobility staple for the front of the thigh, commonly needed after heavy sprint or squat volume.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Standing on one leg, grab the opposite ankle behind you and gently pull the heel toward the glute, keeping the knees close together.', 'A stretch through the front of the thigh of the pulled leg.', 'Do not let the knee flare out to the side; keep it pointing straight down.', 1, NULL::text[], NULL::text[], 'beginner', 1, NULL::integer, 30, true, false),
  ('Doorway Chest Stretch', 'doorway-chest-stretch', 'mobility', 'upper_body', 'Mobility', 'Chest and anterior-shoulder stretch using a doorway -- counters the forward-shoulder posture common from repeated pressing and throwing.', NULL, '{"Doorway"}'::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Place the forearm against a door frame at shoulder height and gently lean the body forward through the doorway until a stretch is felt across the chest.', 'An opening stretch across the chest and front of the shoulder.', 'Do not lean so far that the shoulder joint itself feels pinched; the stretch should be in the muscle, not the joint.', 1, NULL::text[], NULL::text[], 'beginner', 1, NULL::integer, 30, true, false),
  ('Sleeper Stretch (Shoulder)', 'sleeper-stretch-shoulder', 'mobility', 'upper_body', 'Mobility', 'Internal-rotation shoulder stretch performed lying on the side -- addresses the posterior shoulder tightness common in overhead-throwing athletes.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Lie on your side with the bottom arm bent 90 degrees in front of you, and use the top hand to gently press the bottom forearm down toward the ground.', 'A stretch through the back of the shoulder as the forearm presses down.', 'Do not press hard enough to cause sharp pain in the joint; the stretch should be moderate and tolerable.', 1, NULL::text[], NULL::text[], 'beginner', 1, NULL::integer, 30, true, false),
  ('Cross-Body Shoulder Stretch', 'cross-body-shoulder-stretch', 'mobility', 'upper_body', 'Mobility', 'Simple posterior-shoulder stretch pulling the arm across the body -- a quick, accessible shoulder-mobility staple.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Bring one arm straight across the chest and use the opposite hand to gently pull it closer to the body.', 'A stretch through the back and outside of the shoulder.', 'Do not shrug the shoulder up toward the ear while pulling; keep it relaxed and down.', 1, NULL::text[], NULL::text[], 'beginner', 1, NULL::integer, 20, true, false),
  ('Contrast Shower Protocol', 'contrast-shower-protocol', 'recovery', NULL, NULL, 'Alternating hot and cold shower exposure -- an accessible contrast-therapy recovery method supporting circulation and perceived recovery without a cold plunge.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Alternate 1-2 minutes of comfortably hot water with 30-60 seconds of cold water, repeating for 3-4 cycles, finishing on cold.', 'An initial shock on the cold phases that eases with repetition, followed by a refreshed, alert feeling afterward.', 'Do not use water so cold or hot it becomes unsafe; comfortable-but-challenging is the target, not extreme.', 2, NULL::text[], NULL::text[], 'beginner', 1, NULL::integer, 600, true, false),
  ('Box Breathing (Recovery)', 'box-breathing-recovery', 'recovery', NULL, NULL, 'Structured equal-count breathing pattern -- a simple, evidence-informed technique for downregulating the nervous system after high-intensity training.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Inhale for a count of 4, hold for a count of 4, exhale for a count of 4, hold empty for a count of 4, and repeat the cycle.', 'A gradual settling of heart rate and a calmer, more relaxed state as the cycles continue.', 'Do not force the breath holds to the point of discomfort; shorten the count if needed.', 0, NULL::text[], NULL::text[], 'beginner', 1, NULL::integer, 300, true, false),
  ('Diaphragmatic Breathing', 'diaphragmatic-breathing', 'recovery', NULL, NULL, 'Belly-breathing technique emphasizing diaphragm expansion over shoulder/chest breathing -- supports recovery and can be used as a pre-sleep wind-down.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Lying down with one hand on the chest and one on the belly, breathe slowly so the belly hand rises more than the chest hand, then exhale fully.', 'A slow, deep, calming breath pattern with minimal chest or shoulder movement.', 'Do not let the shoulders rise with each breath; the movement should be concentrated in the belly.', 0, NULL::text[], NULL::text[], 'beginner', 1, 10, NULL::integer, true, false),
  ('Foam Roll -- IT Band', 'foam-roll-it-band', 'foam_roll', 'lower_body', NULL, 'Self-myofascial release along the outside of the thigh -- complements the existing quad/hamstring/calf/glute foam-roll set for full lower-body coverage.', NULL, '{"Foam Roller"}'::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Lie on your side with the roller under the outer thigh, and roll slowly from the hip to just above the knee, pausing on tender spots.', 'Pressure and release along the outer thigh, easing as you continue to roll and breathe.', 'Do not roll directly over the knee joint; keep the roller on the muscle length only.', 1, NULL::text[], NULL::text[], 'beginner', 1, NULL::integer, 60, true, false),
  ('Foam Roll -- Lats', 'foam-roll-lats', 'foam_roll', 'upper_body', NULL, 'Self-myofascial release for the lat muscles along the side of the torso -- supports overhead and throwing-shoulder mobility.', NULL, '{"Foam Roller"}'::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Lie on your side with the roller under the armpit/lat area and one arm extended overhead, and roll slowly along the side of the torso.', 'Pressure and release along the side of the torso, easing with continued breathing.', 'Do not roll directly onto the ribs with excessive body weight; control the pressure with the supporting arm and leg.', 1, NULL::text[], NULL::text[], 'beginner', 1, NULL::integer, 60, true, false)
) AS v (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.slug = v.slug
);
