-- position_specific batch 2: 10 new exercise-catalog rows (center/QB/DB/rusher technique).
-- Idempotent on slug (unique constraint uq_exercises_slug) via WHERE NOT EXISTS.

INSERT INTO public.exercises (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.* FROM (VALUES
  ('Snap Accuracy Drill (Center)', 'snap-accuracy-drill-center', 'Position-Specific', NULL, 'Center Technique', 'Repetition-based snapping drill focused purely on accuracy and consistency to a stationary target -- the foundational center skill underneath every other center drill.', NULL, '{"Football"}'::text[], '{"center"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Snap the ball repeatedly to a fixed target (partner or net) at the quarterback''s normal depth, focusing on a consistent, accurate spiral or direct hand-to-hand snap.', 'A consistent, repeatable motion with the same grip, tempo, and release every time.', 'Do not rush the snap motion to add speed before accuracy is consistent; accuracy comes first.', 4, NULL::text[], NULL::text[], 'beginner', 3, 15, NULL::integer, true, false),
  ('Shotgun Snap Under Pressure', 'shotgun-snap-under-pressure', 'Position-Specific', NULL, 'Center Technique', 'Shotgun snap performed with a simulated rusher closing distance -- adds the specific pressure a center faces getting off a clean snap before defending the rush.', NULL, '{"Football","Partner"}'::text[], '{"center"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Execute a shotgun snap while a partner simulates an approaching rush from the front, then transition immediately into a protection stance.', 'A clean, unaffected snap motion despite the visual distraction of the approaching rusher.', 'Do not let the pressure rush the snap motion into an inaccurate throw; the snap must stay clean regardless of distraction.', 8, NULL::text[], NULL::text[], 'moderate', 1, 10, NULL::integer, true, false),
  ('QB Footwork -- 3-Step Drop', 'qb-footwork-3-step-drop', 'Position-Specific', NULL, 'QB Mobility', 'Quick 3-step dropback footwork from center/shotgun -- timing footwork for the fastest-developing pass routes (e.g. slants).', NULL, NULL::text[], '{"quarterback"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'From the snap, take three quick, controlled steps back into a balanced throwing base, timed to arrive as the receiver breaks on a short route.', 'A quick, efficient drop with the feet arriving set and balanced exactly on the third step.', 'Do not let the drop steps be choppy or uneven; each step should cover consistent ground.', 6, NULL::text[], NULL::text[], 'moderate', 1, 10, NULL::integer, true, false),
  ('QB Footwork -- 5-Step Drop', 'qb-footwork-5-step-drop', 'Position-Specific', NULL, 'QB Mobility', 'Standard 5-step dropback footwork -- timing footwork for intermediate-depth routes, the most common drop in a flag-football passing game.', NULL, NULL::text[], '{"quarterback"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'From the snap, take five quick, controlled steps back into a balanced throwing base, arriving set as the intermediate route develops.', 'A smooth, accelerating drop that arrives balanced and ready to throw on the fifth step.', 'Do not let the final step overshoot the balanced base; the last step should settle the feet, not extend them further back.', 7, NULL::text[], NULL::text[], 'moderate', 1, 10, NULL::integer, true, false),
  ('QB Play-Action Fake Footwork', 'qb-play-action-fake-footwork', 'Position-Specific', NULL, 'QB Mobility', 'Footwork rehearsing a hand-off fake before dropping to throw -- sells the run threat that opens up the passing game.', NULL, '{"Football"}'::text[], '{"quarterback"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Execute a believable hand-off fake with a full turn and ball-carry motion, then transition smoothly into the dropback footwork to throw.', 'A convincing, full-commitment fake motion followed by a clean transition into the pass drop.', 'Do not rush the fake so much it looks obviously fake; sell it with real tempo before transitioning.', 6, NULL::text[], NULL::text[], 'moderate', 1, 8, NULL::integer, true, false),
  ('Blitz Pickup Recognition Drill', 'blitz-pickup-recognition-drill', 'Position-Specific', NULL, 'Center Technique', 'Post-snap read drill identifying which rusher poses the greatest threat and adjusting protection angle accordingly -- the decision-making layer beneath center protection footwork.', NULL, '{"Partner"}'::text[], '{"center"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'After the snap, read the rush pattern of one or more approaching defenders and adjust body position to protect the most immediate threat first.', 'A quick visual scan immediately after the snap followed by a decisive positional adjustment.', 'Do not fixate on one rusher if a more immediate threat appears from another angle; the read must stay active.', 7, NULL::text[], NULL::text[], 'advanced', 1, 8, NULL::integer, true, false),
  ('Zone Coverage Drop Drill (DB)', 'zone-coverage-drop-drill', 'Position-Specific', NULL, 'Coverage', 'Backpedal into an assigned zone depth while reading the quarterback''s eyes -- the core zone-coverage movement and recognition pattern.', NULL, '{"Cones","Partner"}'::text[], '{"wr_db","db"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Backpedal to the assigned zone depth while keeping the eyes on the quarterback, then break toward the ball once a throw is read.', 'A controlled backpedal with the eyes doing most of the work, followed by an explosive break the instant the throw is read.', 'Do not watch the receiver instead of the quarterback; zone coverage discipline depends on reading the passer.', 9, NULL::text[], NULL::text[], 'advanced', 1, 8, NULL::integer, true, false),
  ('Man Coverage Trail Technique (DB)', 'man-coverage-trail-technique', 'Position-Specific', NULL, 'Coverage', 'Running stride-for-stride slightly behind and to the side of a receiver -- the trail-position technique used in man coverage on deeper routes.', NULL, '{"Partner"}'::text[], '{"wr_db","db"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Run alongside a partner simulating a route, staying a half-step behind and to the inside or outside as instructed, mirroring their speed changes without losing position.', 'Constant, small speed adjustments to stay in trail position without closing to a collision or falling behind.', 'Do not look back at the quarterback too early and lose track of the receiver''s position.', 10, NULL::text[], NULL::text[], 'advanced', 1, 6, NULL::integer, true, false),
  ('Rusher Counter Move (Spin)', 'rusher-counter-move-spin', 'Position-Specific', NULL, 'Rusher Technique', 'Spin-move counter used when a straight rush lane is blocked -- a secondary rush technique for continuing pressure after an initial path is denied.', NULL, '{"Partner"}'::text[], '{"blitzer","rusher"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Rush toward the mark, and if the direct lane is blocked, plant the outside foot and spin the body around to continue toward the quarterback on the opposite side.', 'A quick, tight rotation around a planted foot that loses minimal ground during the spin.', 'Do not let the spin become wide and slow; keep the rotation tight and close to the blocker.', 9, NULL::text[], NULL::text[], 'advanced', 1, 8, NULL::integer, true, false),
  ('Rusher Hand-Fight Release', 'rusher-hand-fight-release', 'Position-Specific', NULL, 'Rusher Technique', 'Hand-use technique to disengage from a blocker and continue the rush -- legal hand-fighting mechanics within typical flag-football contact rules.', NULL, '{"Partner"}'::text[], '{"blitzer","rusher"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Engage a blocker with a controlled hand placement, then use a swim or rip motion with one arm to disengage and continue toward the quarterback.', 'A quick, decisive hand action that frees the rush lane rather than a prolonged hand-fight.', 'Do not grab or hold the blocker''s jersey; keep all hand contact within legal, brief limits.', 8, NULL::text[], NULL::text[], 'advanced', 1, 8, NULL::integer, true, false)
) AS v (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.slug = v.slug
);
