-- power: 15 new exercise-catalog rows.
-- Source: Ljubljana Frogs 2026 Summer Pre-Season Program (physio-approved
-- 9-week block) + standard flag-football S&C/technical drill taxonomy.
-- Idempotent on (name, category) via WHERE NOT EXISTS (no unique constraint
-- exists on exercises besides the id PK).

INSERT INTO public.exercises (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.* FROM (VALUES
  ('Pogo Hop (Bilateral)', 'pogo-hop-bilateral', 'Power', NULL, 'Reactive', 'Low-amplitude, stiff-ankle bilateral hop -- trains reactive ground contact stiffness, the foundation of the drill ladder''s power series.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps","Contact Time"}'::text[], 'Hop continuously in place with stiff ankles and minimal knee bend, staying on the balls of the feet. Ground contact should be as short as possible.', 'A springy, rebounding sensation through the calves and ankles -- each contact should feel elastic, not heavy.', 'Do not let the knees bend deeply into a squat-like absorption; the ankle, not the knee, should do the work.', 8, NULL::text[], NULL::text[], 'moderate', 4, 15, NULL::integer, true, false),
  ('Pogo Hop (Single-Leg / Ankle Hop)', 'pogo-hop-single-leg', 'Power', NULL, 'Reactive', 'Single-leg version of the pogo hop -- unilateral reactive ankle stiffness for sprint contact preparation.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps","Contact Time"}'::text[], 'Hop continuously on one leg with a stiff ankle and minimal knee bend, staying light and quick on the ball of the foot.', 'A quick, elastic bounce through the ankle and calf of the working leg.', 'Do not let the hip drop or the standing knee buckle inward on landing.', 9, NULL::text[], NULL::text[], 'moderate', 3, 10, NULL::integer, true, false),
  ('Tuck Jump', 'tuck-jump', 'Power', NULL, 'Vertical', 'Maximal vertical jump driving both knees to the chest -- develops explosive hip flexion power and reinforces soft landings.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps","Height"}'::text[], 'Jump straight up as high as possible, driving both knees toward the chest at peak height, then land softly and absorb through the hips and knees.', 'A powerful, explosive extension into the air followed by a quiet, controlled landing.', 'Do not let the knees cave inward on landing or let the landing be loud/stiff-legged.', 13, NULL::text[], NULL::text[], 'moderate', 3, 6, NULL::integer, true, true),
  ('Split Jump (Switch Lunge Jump)', 'split-jump-switch-lunge', 'Power', NULL, 'Unilateral', 'Alternating jumping lunge -- builds single-leg reactive power and hip stability for change-of-direction acceleration.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps","Height"}'::text[], 'From a lunge stance, jump explosively and switch legs mid-air, landing in the opposite lunge. Repeat continuously.', 'A quick, powerful pop through both legs on every switch, with a stable, controlled landing each time.', 'Do not let the front knee travel past the toes on landing or the torso lean forward excessively.', 12, NULL::text[], NULL::text[], 'moderate', 3, 8, NULL::integer, true, true),
  ('Multi-Hop (Continuous Bounding)', 'multi-hop-continuous-bounding', 'Power', NULL, 'Horizontal', 'Continuous single-leg-to-single-leg bounding across distance -- horizontal reactive power for stride power and acceleration mechanics.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Distance","Reps"}'::text[], 'Bound continuously from one leg to the other, covering maximal distance on each contact while maintaining rhythm and posture.', 'A powerful, rhythmic bound-to-bound flow with each landing driving directly into the next push-off.', 'Do not let ground contact time creep up (turning it into a slow series of single jumps rather than continuous bounds).', 14, NULL::text[], NULL::text[], 'advanced', 3, 6, NULL::integer, true, true),
  ('Reactive Box Jump (Minimal Contact)', 'reactive-box-jump-min-contact', 'Power', NULL, 'Vertical', 'Box jump performed for minimal ground contact time rather than maximal height -- trains reactive strength once the basic box jump is mastered.', NULL, '{"Plyo Box"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Contact Time"}'::text[], 'Jump onto the box focusing on leaving the ground as quickly as possible rather than jumping as high as possible. Step down and reset between reps.', 'A sharp, snappy takeoff -- less about jump height, more about how fast you leave the ground.', 'Do not sacrifice a safe landing for speed; if landings get sloppy, slow down and reset intent.', 13, NULL::text[], NULL::text[], 'advanced', 4, 4, NULL::integer, true, true),
  ('45-Degree Cut Jump', '45-degree-cut-jump', 'Power', NULL, 'Change of Direction', 'Single-leg bound into a 45-degree cutting angle -- bridges plyometric power directly into the route-break and pursuit-angle patterns used on the field.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Distance"}'::text[], 'Bound off one leg and land in a stable athletic position turned 45 degrees from the original direction, absorbing force before driving out.', 'A strong, controlled deceleration into the cut with the outside leg loading before an explosive redirect.', 'Do not let the landing knee collapse inward or the torso overrotate past the intended angle.', 12, NULL::text[], NULL::text[], 'advanced', 4, 4, NULL::integer, true, true),
  ('Medicine Ball Slam', 'medicine-ball-slam', 'Power', NULL, 'Explosive', 'Maximal-effort overhead slam -- total-body explosive power with no eccentric deceleration demand, ideal as an early-block power exercise.', NULL, '{"Medicine Ball"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Raise the ball overhead and slam it into the ground as hard as possible, driving through the hips and core, then reset and repeat.', 'A full-body, explosive whip from the hips through the arms into the slam.', 'Do not round the lower back on the reach overhead; keep the core braced throughout.', 11, NULL::text[], NULL::text[], 'moderate', 4, 8, NULL::integer, true, true),
  ('Medicine Ball Rotational Throw', 'medicine-ball-rotational-throw', 'Power', NULL, 'Rotational', 'Rotational med-ball throw against a wall or to a partner -- builds transferable rotational power for throwing, cutting, and change-of-direction force.', NULL, '{"Medicine Ball"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Throws"}'::text[], 'Stand side-on to the target, load by rotating away, then explosively rotate through the hips and release the ball at the target.', 'Power should originate from the hips and transfer through the trunk into the arms, not from the arms alone.', 'Do not let the throw become an arm-only motion; if the hips stop driving, reduce load or reps.', 10, NULL::text[], NULL::text[], 'moderate', 3, 8, NULL::integer, true, false),
  ('Curb / Step Jump', 'curb-step-jump', 'Power', NULL, 'Vertical', 'Low-height bilateral jump onto a curb or single step -- a soft-landing entry point to plyometrics for early-phase or return-to-play work.', NULL, '{"Curb or Low Step"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Jump onto a low curb or step with both feet, landing softly in a quarter-squat, then step down and reset.', 'A gentle, controlled pop with a quiet landing -- this should feel easy relative to a full box jump.', 'Do not let the landing be loud or the knees cave inward; regress height further if either happens.', 7, NULL::text[], NULL::text[], 'beginner', 4, 5, NULL::integer, true, false),
  ('Squat Jump (Bodyweight Explosive)', 'squat-jump-bodyweight-explosive', 'Power', NULL, 'Vertical', 'Maximal-effort vertical jump from a quarter-squat start -- concentric-only power development, mirrors the reference program''s ''explosive intent squat'' pattern.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps","Height"}'::text[], 'From a quarter-squat position, jump straight up as explosively as possible, extending fully through the hips, knees, and ankles.', 'A maximal, whole-body extension upward with full effort on every rep.', 'Do not let quality drop across the set -- if jumps get lower or heavier-landing, the set is done.', 12, NULL::text[], NULL::text[], 'moderate', 4, 5, NULL::integer, true, true),
  ('Countermovement Jump', 'countermovement-jump', 'Power', NULL, 'Vertical', 'Vertical jump using a quick downward countermovement before takeoff -- the standard power-testing jump and a stretch-shortening-cycle training exercise.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps","Height"}'::text[], 'From standing, drop quickly into a quarter-squat and immediately reverse into a maximal vertical jump -- no pause at the bottom.', 'A fast, springy rebound out of the dip -- the transition from down to up should feel instantaneous.', 'Do not pause at the bottom of the countermovement; a pause turns this into a squat jump and defeats the purpose.', 11, NULL::text[], NULL::text[], 'moderate', 4, 5, NULL::integer, true, true),
  ('Lateral Hop Over Line', 'lateral-hop-over-line', 'Power', NULL, 'Lateral', 'Continuous side-to-side bilateral hops over a line or low marker -- frontal-plane reactive power for lateral coverage and shuffle mechanics.', NULL, '{"Cones or Line Marker"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Hop side to side over a line with both feet together, staying light and quick on each contact.', 'A quick, springy side-to-side rhythm through the ankles and hips.', 'Do not let the hops become slow, deliberate steps instead of quick reactive hops.', 8, NULL::text[], NULL::text[], 'moderate', 3, 16, NULL::integer, true, false),
  ('Depth Drop to Stick Landing', 'depth-drop-to-stick-landing', 'Power', NULL, 'Landing Mechanics', 'Step off a low box and land in a held, stable position -- landing-mechanics precursor to the Depth Jump, isolating absorption before adding the rebound.', NULL, '{"Plyo Box"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Step off a low box and land on both feet, absorbing the landing into a quarter-squat and holding the position for a full second before resetting.', 'A quiet, controlled landing with a clear stick -- no wobble, no extra steps to catch balance.', 'Do not let the knees cave in or the landing be audible; lower the box if either happens.', 9, NULL::text[], NULL::text[], 'moderate', 4, 4, NULL::integer, true, false),
  ('Broad Jump to Vertical (Combo)', 'broad-jump-to-vertical-combo', 'Power', NULL, 'Combo', 'Horizontal broad jump immediately transitioned into a maximal vertical jump -- combination plyometric that trains horizontal-to-vertical force redirection.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Perform a standing broad jump, and the instant you land, immediately explode into a maximal vertical jump with no pause.', 'The landing from the broad jump should flow directly into the vertical effort without a reset step.', 'Do not add an extra stabilizing step between the two jumps; if you need one, the intensity or fatigue is too high.', 15, NULL::text[], NULL::text[], 'advanced', 3, 4, NULL::integer, true, true)
) AS v (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.name = v.name AND e.category = v.category
);
