-- warm_up: 15 new exercise-catalog rows.
-- Source: Ljubljana Frogs 2026 Summer Pre-Season Program (physio-approved
-- 9-week block) + standard flag-football S&C/technical drill taxonomy.
-- Idempotent on (name, category) via WHERE NOT EXISTS (no unique constraint
-- exists on exercises besides the id PK).

INSERT INTO public.exercises (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.* FROM (VALUES
  ('A-March', 'a-march', 'warm_up', 'running_drills', 'Sprint Mechanics', 'Marching knee-drive drill -- the entry point of the A/B/C sprint-mechanics progression, teaching knee height and foot strike position.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Distance"}'::text[], 'March forward slowly, driving one knee to hip height with the opposite arm driving forward, striking the ground directly under the hips before switching legs.', 'A slow, controlled, deliberate rhythm -- every position should be held and correct, not rushed.', 'Do not reach the foot forward to strike ahead of the hips; the strike must land directly underneath.', 3, NULL::text[], NULL::text[], 'beginner', 1, 1, NULL::integer, true, false),
  ('A-Run (Run-Out)', 'a-run-run-out', 'warm_up', 'running_drills', 'Sprint Mechanics', 'The A-Skip pattern integrated into a fast jog -- bridges the isolated drill into real running speed.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Distance"}'::text[], 'Begin with the A-Skip knee-drive rhythm and gradually accelerate it into a fast jog, keeping the same knee height and strike position at speed.', 'The same crisp knee drive and under-hip strike as the A-Skip, now happening at real running speed.', 'Do not let the mechanics collapse as speed increases; if form breaks down, slow back to a skip.', 6, NULL::text[], NULL::text[], 'moderate', 1, 1, NULL::integer, true, false),
  ('B-March', 'b-march', 'warm_up', 'running_drills', 'Sprint Mechanics', 'Marching version of the hamstring-cycling B pattern -- teaches the pawing action used to apply force into the ground during sprinting.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Distance"}'::text[], 'From the A-position (knee driven to hip height), extend the lower leg out and ''paw'' it down and back underneath the hip before the foot lands, then switch legs.', 'A distinct pulling/pawing sensation through the hamstring just before ground contact.', 'Do not let the paw land out in front of the hips; it must strike directly underneath.', 4, NULL::text[], NULL::text[], 'moderate', 1, 1, NULL::integer, true, false),
  ('B-Run (Run-Out)', 'b-run-run-out', 'warm_up', 'running_drills', 'Sprint Mechanics', 'The B-Skip pawing pattern integrated into a fast jog -- combines hamstring-cycling mechanics with real sprinting speed.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Distance"}'::text[], 'Begin with the B-Skip pawing rhythm and accelerate it into a fast jog, maintaining the paw-down-under-the-hip mechanic at speed.', 'The same active pawing action as the B-Skip, now happening within a real running stride.', 'Do not let the leg reach out in front to compensate for speed; keep the paw action directly underneath.', 7, NULL::text[], NULL::text[], 'moderate', 1, 1, NULL::integer, true, false),
  ('C-Skip', 'c-skip', 'warm_up', 'running_drills', 'Sprint Mechanics', 'Advanced hip-mobility skip extending the leg at peak knee drive and pulling the foot down under the body -- opens the full hip range used at top speed.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Distance"}'::text[], 'At peak knee drive, extend the leg forward and pull the toes down-and-back to land on the ball of the foot underneath the body, cycling continuously.', 'A full, exaggerated hip-flexion-to-extension cycle with an active downward pull on every step.', 'Do not let the extended leg land stiff-legged out in front; the pull-back action must happen before landing.', 6, NULL::text[], NULL::text[], 'advanced', 1, 1, NULL::integer, true, false),
  ('Fast-Leg Drill (Every 3rd Step)', 'fast-leg-drill', 'warm_up', 'running_drills', 'Sprint Mechanics', 'Explosive full leg-cycle inserted every third step during a jog -- trains reactive turnover and the ''foot from above'' cue used at top speed.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Distance"}'::text[], 'Jog at a normal pace with a single explosive, full-cycle knee drive inserted every third step, then return to normal steps before the next explosive rep.', 'A sharp, distinct burst of speed and knee drive on the explosive step, clearly different from the normal steps around it.', 'Do not let the explosive step become just a slightly bigger normal step; it should be a distinctly faster, fuller cycle.', 6, NULL::text[], NULL::text[], 'advanced', 1, 1, NULL::integer, true, false),
  ('Scissor / 1-2 Switch Drill', 'scissor-1-2-switch-drill', 'warm_up', 'running_drills', 'Sprint Mechanics', 'Fast leg-exchange drill in a 90-degree knee position -- trains reactive turnover speed and the ''foot from above'' ground-contact cue.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Hold both knees at roughly 90 degrees (one forward, one back) and rapidly switch their positions in the air, landing lightly and switching again immediately.', 'A fast, light, reactive switching rhythm with minimal time spent on the ground between switches.', 'Do not let the switches slow down into a controlled march; the drill''s value is in the speed of the exchange.', 5, NULL::text[], NULL::text[], 'moderate', 1, 8, NULL::integer, true, false),
  ('Straight-Leg Run (Primetimes)', 'straight-leg-run-primetimes', 'warm_up', 'running_drills', 'Sprint Mechanics', 'Stiff-leg running drill with an active downward strike -- trains front-side mechanics and reactive ground contact stiffness.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Distance"}'::text[], 'Run forward with the legs kept relatively straight (minimal knee bend), actively striking each foot down and back under the hips.', 'A stiff, quick, reactive contact through the front of the shin and ankle on every step.', 'Do not lock the knees completely rigid; keep a very slight bend to avoid jarring the joints.', 5, NULL::text[], NULL::text[], 'moderate', 1, 1, NULL::integer, true, false),
  ('Ankling', 'ankling', 'warm_up', 'running_drills', 'Sprint Mechanics', 'Quick, low, stiff-ankle foot pops with minimal knee movement -- isolates reactive ankle stiffness, the foundation quality underneath every sprint mechanic.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Distance"}'::text[], 'Take rapid, small, low foot pops forward with a stiff ankle and almost no knee bend, staying on the balls of the feet.', 'A quick, light, reactive tapping sensation through the ankles and calves.', 'Do not let the knees bend to absorb the contacts; the ankle alone should manage each pop.', 4, NULL::text[], NULL::text[], 'beginner', 1, 1, NULL::integer, true, false),
  ('Walking Spiderman with Rotation', 'walking-spiderman-rotation', 'warm_up', 'dynamic_stretch', 'Mobility', 'Deep lunge walk with a trunk rotation and reach -- opens the hips, groin, and thoracic spine together in one dynamic movement.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Step into a deep lunge, plant the same-side hand on the ground, and rotate the torso upward reaching the opposite arm toward the ceiling, then step through into the next lunge.', 'A deep stretch through the hip flexor and groin of the back leg, plus an open feeling across the rotated chest and upper back.', 'Do not let the front knee collapse inward during the lunge or rotate from the lower back instead of the upper spine.', 3, NULL::text[], NULL::text[], 'beginner', 1, 6, NULL::integer, true, false),
  ('Ankle Rocks (Knee Over Toe)', 'ankle-rocks-knee-over-toe', 'warm_up', 'dynamic_stretch', 'Mobility', 'Controlled rocking of the knee forward over the toe -- restores ankle dorsiflexion range needed for a strong sprint push-off and safe landings.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'In a half-kneeling or standing lunge position, rock the front knee forward over the toe repeatedly, keeping the heel flat on the ground.', 'A stretch through the front of the ankle and lower calf that eases with each repetition.', 'Do not let the heel lift off the ground to fake the range; the stretch must come from true ankle mobility.', 2, NULL::text[], NULL::text[], 'beginner', 1, 10, NULL::integer, true, false),
  ('Pogo Hops (Warm-Up, Low)', 'pogo-hops-warmup-low', 'warm_up', 'activation', 'Reactive', 'Low-intensity warm-up version of the pogo hop -- primes reactive ankle stiffness before the main session without accumulating real fatigue.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Perform light, low-amplitude bilateral hops with stiff ankles, keeping the effort easy and the contacts quick.', 'A light, springy warm-up sensation through the ankles -- easy effort, not a maximal plyometric.', 'Do not turn this into a maximal-effort plyometric set; keep the intent light since this is a warm-up primer.', 2, NULL::text[], NULL::text[], 'beginner', 2, 15, NULL::integer, true, false),
  ('Toy Soldier / Straight-Leg March', 'toy-soldier-straight-leg-march', 'warm_up', 'dynamic_stretch', 'Mobility', 'Walking straight-leg kicks reaching toward the opposite hand -- dynamic hamstring and hip-flexor mobility used in nearly every field warm-up.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Walk forward, kicking one straight leg up to meet the opposite hand reaching down, then alternate sides with each step.', 'A dynamic hamstring stretch through the raised leg on every kick.', 'Do not round the lower back to reach the hand to the foot; keep the chest tall and let the leg do the reaching.', 3, NULL::text[], NULL::text[], 'beginner', 1, 10, NULL::integer, true, false),
  ('Leg Swings (Side to Side)', 'leg-swings-side-to-side', 'warm_up', 'dynamic_stretch', 'Mobility', 'Lateral leg-swing drill -- opens the adductors and abductors in the frontal plane, complementing the front-to-back leg swing already in the library.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Hold a wall or partner for balance, and swing one leg side to side across the body in a controlled, increasing arc.', 'A dynamic stretch through the inner and outer thigh as the swing arc increases.', 'Do not let the torso sway to add range; keep the trunk stable and let the hip do the moving.', 3, NULL::text[], NULL::text[], 'beginner', 1, 10, NULL::integer, true, false),
  ('Band Lateral Walk', 'band-lateral-walk', 'warm_up', 'activation', 'Activation', 'Lateral stepping against a mini-band around the thighs or ankles -- glute-medius activation used before lateral and change-of-direction work.', NULL, '{"Mini Band"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Place a band around the thighs or ankles, get into a quarter-squat, and step laterally against the band tension for the prescribed distance, then return.', 'A steady burn through the outer hip and glute of the trailing leg with every step.', 'Do not let the knees drift together or the torso bob up and down; stay low and level throughout.', 5, NULL::text[], NULL::text[], 'beginner', 2, 10, NULL::integer, true, false)
) AS v (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.name = v.name AND e.category = v.category
);
