-- Backfill: 52 exercise-catalog rows that exist in the live `exercises` table but
-- were never committed to a tracked migration (same class of gap as the
-- sponsors/video_bookmarks/weekly_training_analysis backfill, 20260701234500).
-- The tracked seed (20260306071950) covers only the 22 mobility/warm-up/foam-roll/
-- recovery/cool-down basics; the Strength/Speed/Power/Agility/Position-Specific
-- catalog (plus later recovery/warm-up/cool-down additions) was seeded directly
-- in production. Reconstructed verbatim from live-schema introspection.
--
-- Idempotent: WHERE NOT EXISTS on (name, category) — a no-op against the live
-- project (all 52 rows already exist there); populates a fresh `supabase db reset`.
-- id/created_at/updated_at are intentionally regenerated (nothing references
-- exercise ids across environments except protocol_exercises rows created at runtime).

INSERT INTO public.exercises
  (name, slug, category, subcategory, movement_pattern, description, video_id, video_url,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.name, v.slug, v.category, v.subcategory, v.movement_pattern, v.description,
       v.video_id, v.video_url, v.equipment_needed, v.position_specific,
       v.applicable_positions::uuid[], v.metrics_tracked, v.how_text, v.feel_text,
       v.compensation_text, v.load_contribution_au, v.muscle_groups, v.target_muscles,
       v.difficulty_level, v.default_sets, v.default_reps, v.default_hold_seconds,
       v.active, v.is_high_intensity
FROM (VALUES
  ('Bulgarian Split Squat', 'bulgarian-split-squat', 'Strength', NULL, 'Unilateral', 'Single-leg strength builder for deceleration and lower-body resilience.', '2C-uNgKwPLE', NULL, '{Bench,Dumbbells}'::text[], NULL, NULL, '{Sets,Reps,Weight}'::text[], 'Descend under control and drive through the full foot.', 'Front leg should do the work.', 'Do not bounce out of the bottom or dump into the lower back.', 14, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Copenhagen Plank', 'copenhagen-plank', 'Strength', NULL, 'Adductor', 'Adductor-focused plank supporting groin resilience for COD athletes.', 'Pk6P-q1UYYI', NULL, '{Bench}'::text[], NULL, NULL, '{Sets,Duration}'::text[], 'Stay long through the body and breathe behind the brace.', 'Adductors should work steadily without hip dropping.', 'Do not twist or sag through the trunk.', 8, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Front Squat', 'front-squat', 'Strength', NULL, 'Squat', 'Anterior-loaded squat that reinforces torso stiffness and leg drive.', 'jWMzLJzYqUE', NULL, '{Barbell}'::text[], NULL, NULL, '{Sets,Reps,Weight}'::text[], 'Stay tall through the rack and drive knees over toes.', 'Upper back engagement with even foot pressure.', 'Avoid elbows dropping or chest collapsing.', 16, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Glute Activation Circuit', 'glute-activation-circuit', 'Strength', NULL, 'Activation', 'Activate the glutes before sprinting, cutting, and lower-body work.', 'eIcIJ5oq_9U', NULL, '{"Mini Band"}'::text[], NULL, NULL, '{Duration,Reps}'::text[], 'Control each rep and keep tension on the band.', 'Glutes should feel switched on before speed work.', 'Avoid using the lower back to cheat the range.', 5, NULL, NULL, 'low', 1, NULL, NULL, true, false),
  ('Goblet Squat', 'goblet-squat', 'Strength', NULL, 'Squat', 'Foundational squat for leg strength and trunk control.', 'MeIiIdhvXT4', NULL, '{Kettlebell}'::text[], NULL, NULL, '{Sets,Reps,Weight}'::text[], 'Stay tall and sit between the hips.', 'Even pressure through the whole foot.', 'Do not collapse inward at the knees.', 12, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Half-Kneeling Pallof Press', 'half-kneeling-pallof-press', 'Strength', NULL, 'Anti-Rotation', 'Core anti-rotation drill supporting rotational power transfer.', 'AThVe2U51E8', NULL, '{Cable,Band}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Sets,Reps,Resistance}'::text[], 'Brace before each press and own the return.', 'The trunk should resist rotation instead of twisting.', 'Do not let the band pull the torso off center.', 8, NULL, NULL, 'low', 1, NULL, NULL, true, false),
  ('Landmine Press', 'landmine-press', 'Strength', NULL, 'Push', 'Shoulder-friendly upper-body press for quarterbacks.', 'VJPvjuXVlKA', NULL, '{Landmine,Barbell}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Sets,Reps,Weight}'::text[], 'Press up and out while keeping ribs stacked.', 'Smooth pressing path without shoulder pinch.', 'Do not flare the rib cage or shrug hard at lockout.', 12, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Lateral Lunge', 'lateral-lunge', 'Strength', NULL, 'Lateral', 'Frontal-plane strength builder for COD resilience.', 'Ic9fFCHOtmk', NULL, '{None}'::text[], NULL, NULL, '{Sets,Reps,Weight}'::text[], 'Sit back into the hip and own the return.', 'Inside thigh and glute should absorb the load.', 'Do not cave the knee or shift onto the toes.', 10, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Nordic Hamstring Curl', 'nordic-hamstring-curl', 'Strength', 'hamstring', NULL, NULL, 'GUg_MHqxFZ8', 'https://www.youtube.com/watch?v=GUg_MHqxFZ8', NULL, NULL, NULL, NULL, 'Kneel on a pad. Partner holds ankles (or use a GHD). With a straight torso, slowly lower body toward floor resisting with hamstrings. Catch with hands, push up, curl back using hamstrings.', 'Deep hamstring tension on the way down — the pull should be strong through the back of the thigh, not the lower back.', NULL, 25, '{hamstrings,glutes,calves}'::text[], '{"biceps femoris",semitendinosus,semimembranosus}'::text[], 'advanced', 3, 8, NULL, true, true),
  ('Scapular Activation', 'scapular-activation', 'Strength', NULL, 'Activation', 'Prime the shoulder girdle before upper-body work and throwing.', 'zJiNB0cFyuI', NULL, '{"Resistance Band"}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Duration,Reps}'::text[], 'Control protraction and retraction with tempo.', 'Shoulders should feel stable and warm.', 'Avoid shrugging or rushing through the band tension.', 6, NULL, NULL, 'low', 1, NULL, NULL, true, false),
  ('Single-Leg Romanian Deadlift', 'single-leg-romanian-deadlift', 'Strength', NULL, 'Hip Hinge', 'Single-leg posterior-chain builder for balance and hamstring strength.', 'G9GTnSmBpC8', NULL, '{Dumbbells}'::text[], NULL, NULL, '{Sets,Reps,Weight}'::text[], 'Reach long through the rear leg and keep hips square.', 'Hamstrings and glutes should load cleanly.', 'Do not rotate open through the pelvis.', 12, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Trap Bar Deadlift', 'trap-bar-deadlift', 'Strength', NULL, 'Hip Hinge', 'Primary posterior-chain lift for force production.', 'JtNQYfOGLYo', NULL, '{"Trap Bar"}'::text[], NULL, NULL, '{Sets,Reps,Weight}'::text[], 'Push the floor away and finish tall.', 'Leg drive and hip extension should carry the lift.', 'Do not round the upper back or jerk from the floor.', 18, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('L-Drill (3-Cone)', 'l-drill-3-cone', 'Agility', NULL, 'Change of Direction', 'Three-cone drill for deceleration, re-acceleration, and body control.', 'kJuHdC68U0Y', NULL, '{Cones}'::text[], NULL, NULL, '{Reps,Time}'::text[], 'Sink hips and own each plant before accelerating out.', 'Sharp edges through each change of direction.', 'Do not overrun the cone and reach to recover.', 12, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Pro Agility (5-10-5)', 'pro-agility-5-10-5', 'Agility', NULL, 'Lateral', 'Classic lateral COD drill for offensive and defensive skill players.', 'wAn7kH6f_rw', NULL, '{Cones}'::text[], NULL, NULL, '{Reps,Time}'::text[], 'Explode out of each plant with low hips.', 'Balanced cuts and aggressive re-acceleration.', 'Do not cross the feet or pop upright on the middle turn.', 12, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Reactive Mirror Drill', 'reactive-mirror-drill', 'Agility', NULL, 'Reactive', 'Partner-driven change-of-direction drill for live reactions.', 'UXdJV5pMy0A', NULL, '{None}'::text[], '{wr_db}'::text[], '{fc673039-ec26-4c0e-8c32-14d6dafc36d3,9f89a874-b3d4-4615-8c35-53d26c02fa15}'::text[], '{Duration,Reps}'::text[], 'Stay square and react off the partner, not anticipation.', 'Quick feet with controlled posture.', 'Do not reach or cross over too early.', 10, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Lateral Bound', 'lateral-bound', 'Power', NULL, 'Lateral', 'Single-leg lateral power exercise with controlled stick landings.', 'XFEjeiQfhOs', NULL, '{None}'::text[], NULL, NULL, '{Reps,Distance}'::text[], 'Jump aggressively sideways and own the landing.', 'Powerful lateral push with stable landings.', 'Do not let the knee collapse on contact.', 12, NULL, NULL, 'high', 1, NULL, NULL, true, false),
  ('Medicine Ball Throws', 'medicine-ball-throws', 'Power', NULL, 'Explosive', 'Rotational and chest-pass throws to build total-body power.', 'VNHEuCjuaAI', NULL, '{"Medicine Ball"}'::text[], NULL, NULL, '{Throws,Sets}'::text[], 'Explode through the floor and finish the throw cleanly.', 'Crisp power transfer through hips and trunk.', 'Avoid overextending the low back on the finish.', 12, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Single-Leg Hop (Forward)', 'single-leg-hop-forward', 'Power', NULL, 'Unilateral', 'Forward single-leg power and landing control drill.', 'bG9TIW87bqg', NULL, '{None}'::text[], NULL, NULL, '{Reps,Distance}'::text[], 'Project forward while landing quietly and balanced.', 'Strong elastic rebound from each leg.', 'Do not lose alignment through the landing knee.', 12, NULL, NULL, 'high', 1, NULL, NULL, true, false),
  ('Skater Jumps', 'skater-jumps', 'Power', NULL, 'Lateral', 'Continuous lateral power drill for frontal-plane explosiveness.', 'oVhPRHlwuDI', NULL, '{None}'::text[], NULL, NULL, '{Reps,Distance}'::text[], 'Attack side-to-side jumps with clean rhythm.', 'Elastic lateral push and soft reception.', 'Do not rush the landing position.', 12, NULL, NULL, 'high', 1, NULL, NULL, true, false),
  ('Unilateral Jump Series', 'unilateral-jump-series', 'Power', NULL, 'Unilateral', 'Single-leg hops and bounds for force production and landing control.', 'bG9TIW87bqg', NULL, '{None}'::text[], NULL, NULL, '{Reps,Sets,Distance}'::text[], 'Stick the landing before the next effort.', 'Powerful take-off with stable single-leg landings.', 'Avoid noisy landings and excessive trunk sway.', 12, NULL, NULL, 'high', 1, NULL, NULL, true, false),
  ('10-Yard Burst', '10-yard-burst', 'Speed', NULL, 'Acceleration', 'Short acceleration exposure focused on first-step violence and projection.', 'ZBqaHBDyF2k', NULL, '{Cones}'::text[], '{wr_db}'::text[], '{fc673039-ec26-4c0e-8c32-14d6dafc36d3,9f89a874-b3d4-4615-8c35-53d26c02fa15}'::text[], '{Reps,Time}'::text[], 'Drive low through the first three steps.', 'Feel powerful projection from the start.', 'Do not stand up too early.', 10, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('3-Step Acceleration Drill', '3-step-acceleration-drill', 'Speed', NULL, '3-step acceleration', 'Explosive first three steps for pocket movement and scramble efficiency.', 'vJRLJbLiRdo', NULL, '{Cones}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Reps,Time,Distance}'::text[], 'Stay low and attack out of the first step.', 'Feel force into the ground with each projection.', 'Do not pop upright too early.', 10, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Deceleration Drill', 'deceleration-drill', 'Speed', NULL, 'Deceleration', 'Teach safe stopping mechanics after acceleration and sprint work.', 'uOvmzs6FGMM', NULL, '{Cones}'::text[], NULL, NULL, '{Reps,Distance}'::text[], 'Own the final two steps and brake with control.', 'Balanced hips and quiet feet into the stop.', 'Do not crash into the stop or let knees cave in.', 8, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Flying 20m Sprint', 'flying-20m-sprint', 'Speed', NULL, 'Top-End Speed', 'Build to max velocity before entering a timed flying sprint zone.', 'I8O4YULZ0ls', NULL, '{Cones}'::text[], NULL, NULL, '{Reps,Time}'::text[], 'Relax into the build and attack the fly zone.', 'Fast hips and elastic contacts at speed.', 'Avoid overstriding as speed rises.', 14, NULL, NULL, 'high', 1, NULL, NULL, true, false),
  ('Flying 30m Sprint', 'flying-30m-sprint', 'Speed', NULL, 'Top-End Speed', 'Build gradually before entering a maximal fly zone.', 'I8O4YULZ0ls', NULL, '{Cones}'::text[], NULL, NULL, '{Reps,Time}'::text[], 'Stay relaxed into the fly zone and let speed rise.', 'Fast contacts and upright posture at speed.', 'Avoid reaching out with the front foot.', 14, NULL, NULL, 'high', 1, NULL, NULL, true, false),
  ('Hill Sprint (Short)', 'hill-sprint-short', 'Speed', NULL, 'Acceleration', 'Short hill sprint for horizontal projection and front-side mechanics.', 'O7ZRKuuvYdU', NULL, '{Hill}'::text[], NULL, NULL, '{Reps,Time}'::text[], 'Attack the hill with a powerful knee drive.', 'Projection and force should feel natural uphill.', 'Do not collapse at the hips on the slope.', 12, NULL, NULL, 'high', 1, NULL, NULL, true, false),
  ('Resisted Sprint (Band)', 'resisted-sprint-band', 'Speed', NULL, 'Acceleration', 'Partner-resisted sprint to build horizontal force application.', 'wR4hn-uT5eM', NULL, '{Band}'::text[], NULL, NULL, '{Reps,Distance}'::text[], 'Keep shin angles aggressive and steps decisive.', 'Feel force driving backward into the ground.', 'Do not let resistance pull you upright.', 12, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Backpedal Technique Drill', 'backpedal-technique-drill', 'Position-Specific', NULL, 'Coverage', 'Backpedal and transition drill for defensive backs.', 'JnCFxNrK4OA', NULL, '{Cones}'::text[], '{wr_db,db}'::text[], '{9f89a874-b3d4-4615-8c35-53d26c02fa15}'::text[], '{Distance,Reps}'::text[], 'Keep hips loaded and feet under the center of mass.', 'Smooth backward movement with ready hips.', 'Do not click the heels or let the chest drift back.', 10, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Progressive Throwing Sequence', 'progressive-throwing-sequence', 'Position-Specific', NULL, 'Throwing', 'Structured throwing build-up from short to moderate distances.', 'k5E-L8CLQLQ', NULL, '{Football}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Throws,Distance}'::text[], 'Build distance gradually while keeping mechanics crisp.', 'Arm should feel hot but under control.', 'Do not jump to max velocity before the arm is ready.', 16, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('QB Arm Care Routine', 'qb-arm-care-routine', 'Position-Specific', NULL, 'Arm Care', 'Rotator cuff and elbow-health sequence for quarterbacks.', 'RWPOU9RCTCY', NULL, '{"Light Band"}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Duration,Sets,Reps}'::text[], 'Move slowly through cuff and forearm prep.', 'Arm should feel supported, not fatigued.', 'Stop if pain sharpens through the front of the shoulder.', 6, NULL, NULL, 'low', 1, NULL, NULL, true, false),
  ('Route Tree Practice - Slant/In', 'route-tree-practice-slant-in', 'Position-Specific', NULL, 'Route Running', 'Route-running block for sharp inside breaks and acceleration out of cuts.', 'tYVHjFzqA3s', NULL, '{Cones,Football}'::text[], '{wr_db,wr}'::text[], '{fc673039-ec26-4c0e-8c32-14d6dafc36d3}'::text[], '{Routes,"Completion Rate"}'::text[], 'Win the stem before attacking the break.', 'Explosive separation out of the cut.', 'Do not drift into the break or rise up too early.', 10, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Throwing Volume Session - 120 Throws', 'throwing-volume-120', 'Position-Specific', NULL, 'Throwing', 'Controlled 120-throw workload for late-foundation and early-build weeks.', 'k5E-L8CLQLQ', NULL, '{Football}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Throws,Duration}'::text[], 'Organize throws into quality blocks with short resets.', 'Notice repeatable footwork and release timing.', 'Do not let tempo outrun mechanics.', 24, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Throwing Volume Session - 160 Throws', 'throwing-volume-160', 'Position-Specific', NULL, 'Throwing', 'Mid-build throwing session at 160 total throws.', 'k5E-L8CLQLQ', NULL, '{Football}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Throws,Duration}'::text[], 'Split volume into manageable series and monitor arm freshness.', 'Arm should stay fast without losing accuracy.', 'Stop the session if mechanics break down.', 28, NULL, NULL, 'high', 1, NULL, NULL, true, false),
  ('Throwing Volume Session - 200 Throws', 'throwing-volume-200', 'Position-Specific', NULL, 'Throwing', 'High-volume quarterback session at 200 total throws.', 'k5E-L8CLQLQ', NULL, '{Football}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Throws,Duration}'::text[], 'Keep recovery breaks structured and consistent.', 'High output with controlled fatigue.', 'Do not compress rest just to finish faster.', 32, NULL, NULL, 'high', 1, NULL, NULL, true, false),
  ('Throwing Volume Session - 240 Throws', 'throwing-volume-240', 'Position-Specific', NULL, 'Throwing', 'Advanced throwing workload at 240 total throws.', 'k5E-L8CLQLQ', NULL, '{Football}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Throws,Duration}'::text[], 'Work in blocks and maintain decision-making quality.', 'Fast arm with disciplined pacing.', 'Do not let footwork deteriorate late in the session.', 34, NULL, NULL, 'high', 1, NULL, NULL, true, false),
  ('Throwing Volume Session - 280 Throws', 'throwing-volume-280', 'Position-Specific', NULL, 'Throwing', 'Near-peak quarterback throwing session at 280 throws.', 'k5E-L8CLQLQ', NULL, '{Football}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Throws,Duration}'::text[], 'Preserve mechanics through deliberate breaks and sequencing.', 'The arm should stay fast late into the session.', 'Do not add volume once accuracy drops.', 36, NULL, NULL, 'high', 1, NULL, NULL, true, false),
  ('Throwing Volume Session - 320 Throws (Peak)', 'throwing-volume-320', 'Position-Specific', NULL, 'Throwing', 'Peak-season throwing session capped at 320 throws.', 'k5E-L8CLQLQ', NULL, '{Football}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Throws,Duration}'::text[], 'Treat this like a peak competition workload with planned recovery blocks.', 'High intent with game-specific precision.', 'Do not exceed the target volume.', 40, NULL, NULL, 'high', 1, NULL, NULL, true, false),
  ('Throwing Volume Session - 50 Throws', 'throwing-volume-50', 'Position-Specific', NULL, 'Throwing', 'Return-to-throwing session capped at 50 throws.', 'k5E-L8CLQLQ', NULL, '{Football}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Throws,Duration}'::text[], 'Keep intent low and mechanics crisp.', 'Arm should finish fresher than it started.', 'Do not chase velocity during reintroduction weeks.', 18, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('Throwing Volume Session - 80 Throws', 'throwing-volume-80', 'Position-Specific', NULL, 'Throwing', 'Foundation throwing session at 80 total throws.', 'k5E-L8CLQLQ', NULL, '{Football}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Throws,Duration}'::text[], 'Stay rhythmic through each throw family.', 'Steady volume with stable mechanics.', 'Do not add extra throws once mechanics fade.', 20, NULL, NULL, 'moderate', 1, NULL, NULL, true, false),
  ('WR/DB Dynamic Warm-up', 'wrdb-dynamic-warmup', 'Position-Specific', NULL, 'Warm-up', 'Dynamic movement prep for acceleration, backpedal, shuffle, and crossover mechanics.', 'LaxlMu8YQUY', NULL, '{Cones}'::text[], '{wr_db}'::text[], '{fc673039-ec26-4c0e-8c32-14d6dafc36d3,9f89a874-b3d4-4615-8c35-53d26c02fa15}'::text[], '{Duration,Completion}'::text[], 'Move from mobility into progressively faster mechanics.', 'Legs should feel springy and ready to cut.', 'Do not skip the slower prep reps.', 8, NULL, NULL, 'low', 1, NULL, NULL, true, false),
  ('Ankle Mobility Sequence', 'ankle-mobility-sequence', 'cool_down', NULL, 'Mobility', 'Restore ankle range of motion before training and on recovery days.', 'ghwdVE4xn-U', NULL, '{None}'::text[], NULL, NULL, '{Duration,ROM}'::text[], 'Move through controlled dorsiflexion and rotation drills.', 'Looser ankles and easier shin angles.', 'Avoid collapsing the arch or rushing the range.', 4, NULL, NULL, 'low', 1, NULL, NULL, true, false),
  ('Hip 90/90 Stretch Sequence', 'hip-90-90-stretch-sequence', 'cool_down', NULL, 'Mobility', 'Restore hip internal and external rotation for sharp route breaks and hip flips.', 'v_ZnFMgCiAg', NULL, '{None}'::text[], '{wr_db}'::text[], '{fc673039-ec26-4c0e-8c32-14d6dafc36d3,9f89a874-b3d4-4615-8c35-53d26c02fa15}'::text[], '{Duration,ROM}'::text[], 'Transition smoothly between 90/90 positions.', 'Hips should open without pinching.', 'Do not force end range or twist through the low back.', 4, NULL, NULL, 'low', 1, NULL, NULL, true, false),
  ('Hip Mobility Sequence', 'hip-mobility-sequence', 'cool_down', NULL, 'Mobility', 'Open internal and external hip rotation for throwing and lower-body work.', 'eFgqVbDe5Ps', NULL, '{None}'::text[], NULL, NULL, '{Duration,ROM}'::text[], 'Use 90/90 transitions and hip flexor mobility.', 'Hips should feel freer through stance and stride.', 'Do not force end range or rotate through the lumbar spine.', 4, NULL, NULL, 'low', 1, NULL, NULL, true, false),
  ('Thoracic Rotation Drills', 'thoracic-rotation-drills', 'cool_down', NULL, 'Mobility', 'Improve thoracic rotation to support efficient throwing mechanics.', 'FGIGlBUFbKc', NULL, '{None}'::text[], '{quarterback}'::text[], '{e43ab0e8-ec2a-451b-814d-266b3ca247b0}'::text[], '{Duration,Rotations}'::text[], 'Rotate through the upper back while keeping hips stable.', 'More torso rotation without shoulder strain.', 'Do not over-rotate through the lower back.', 4, NULL, NULL, 'low', 1, NULL, NULL, true, false),
  ('Box Breathing', 'box-breathing', 'recovery', NULL, NULL, NULL, 'paqAzWbLIUw', NULL, NULL, NULL, NULL, NULL, 'Inhale for 4 seconds, hold for 4, exhale for 4, hold for 4. Repeat for 5 rounds. Sit or lie comfortably with eyes closed.', 'Heart rate should slow noticeably within 3 rounds. The exhale phase is the most calming — make it deliberate.', NULL, 0, NULL, NULL, 'beginner', 1, 5, NULL, true, false),
  ('Hip Flexor Lunge Stretch', 'hip-flexor-lunge-stretch', 'recovery', NULL, NULL, NULL, 'v_ZnFMgCiAg', NULL, NULL, NULL, NULL, NULL, 'Kneel on one knee in a lunge position. Squeeze the glute of the rear leg and shift your hips forward until you feel a stretch at the front of the rear hip. Hold and switch.', 'You should feel an elongation at the front of the hip and thigh — not in the knee. Posterior pelvic tilt deepens it.', NULL, 0, NULL, NULL, 'beginner', 1, NULL, 45, true, false),
  ('Pigeon Pose', 'pigeon-pose', 'recovery', NULL, NULL, NULL, 'qZ_KgFnRlhI', NULL, NULL, NULL, NULL, NULL, 'From a push-up position, bring one knee forward toward the same-side wrist. Lower your hips and fold forward over the shin. Hold, breathe, and switch sides.', 'Deep release through the outer hip and glute. Breathe through any tightness — do not push into sharp pain.', NULL, 0, NULL, NULL, 'beginner', 1, NULL, 60, true, false),
  ('Seated Hamstring Stretch', 'seated-hamstring-stretch', 'recovery', NULL, NULL, NULL, 'LB2V2jVHudc', NULL, NULL, NULL, NULL, NULL, 'Sit tall on the floor with legs extended. Hinge from the hips (not rounding the lower back) and reach toward the feet. Hold the position with soft knees.', 'Steady pull behind the knee and up through the hamstring. Breathing deeply should deepen the stretch.', NULL, 0, NULL, NULL, 'beginner', 1, NULL, 45, true, false),
  ('Supine Spinal Twist', 'supine-spinal-twist', 'recovery', NULL, NULL, NULL, 'FGIGlBUFbKc', NULL, NULL, NULL, NULL, NULL, 'Lie on your back. Draw one knee to the chest, then guide it across the body with the opposite hand. Extend both arms wide and breathe. Repeat other side.', 'Gentle wringing sensation through the thoracic and lumbar spine. The shoulder that lifts is normal — breathe it down.', NULL, 0, NULL, NULL, 'beginner', 1, NULL, 45, true, false),
  ('Copenhagen Plank', 'copenhagen-plank-warmup', 'warm_up', NULL, NULL, NULL, 'Pk6P-q1UYYI', NULL, NULL, NULL, NULL, NULL, 'Lie on your side. Rest top foot on a bench or box. Bottom leg hangs free. Press up so body forms a straight line. Hold with top-leg adductor doing the work.', 'Distinct pull in the inner thigh of the top leg — that is the adductor engaging. This is the primary groin injury prevention exercise for sprinters.', 'If groin cramps: shorten hold to 15s and build up. If hip drops: reduce leverage by placing knee (not ankle) on bench.', 3, NULL, NULL, NULL, 1, NULL, 30, true, false),
  ('Single Arm Plank', 'single-arm-plank-warmup', 'warm_up', NULL, NULL, NULL, 'Pk6P-q1UYYI', NULL, NULL, NULL, NULL, NULL, 'Start in forearm plank. Extend one arm forward, parallel to the floor. Fight the urge to rotate — keep both hips square to the ground.', 'Strong oblique pull on the working side fighting rotation. If you feel nothing in the obliques, you are rotating too much.', 'If hips rotate: reduce arm lift height. If lower back takes over: return to two-arm plank and build more time.', 2, NULL, NULL, NULL, 1, NULL, 30, true, false),
  ('Straight Plank', 'straight-plank-warmup', 'warm_up', NULL, NULL, NULL, 'Pk6P-q1UYYI', NULL, NULL, NULL, NULL, NULL, 'Forearms on ground, elbows under shoulders. Body forms a rigid line from heels to head. Brace hard — tuck the pelvis slightly so your lower back stays flat.', 'Deep tension through the entire core simultaneously — abs, obliques, glutes all on at once. Lower back feels stable, not compressed.', 'If hips sag: squeeze glutes harder and tuck pelvis. If lower back aches: reduce to 30s and rebuild hip flexor length.', 2, NULL, NULL, NULL, 1, NULL, 60, true, false)
) AS v(name, slug, category, subcategory, movement_pattern, description, video_id, video_url,
       equipment_needed, position_specific, applicable_positions, metrics_tracked,
       how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
       target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
       active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.name = v.name AND e.category = v.category
);
