-- strength batch 2: 30 new exercise-catalog rows (loaded barbell/dumbbell/kettlebell staples).
-- Idempotent on (name, category) via WHERE NOT EXISTS.

INSERT INTO public.exercises (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.* FROM (VALUES
  ('Barbell Back Squat', 'barbell-back-squat', 'Strength', NULL, 'Squat', 'Bilateral barbell squat -- the foundational lower-body strength movement once external load is available, building maximal leg and hip strength beyond bodyweight ceilings.', NULL, '{"Barbell","Squat Rack"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Position the bar across the upper back, brace the core, and squat down until the hip crease is at or below knee level, then drive back up through the whole foot.', 'A deep, controlled tension through the quads, glutes, and hips on the way down, with a powerful drive on the way up.', 'Do not let the knees cave inward or the heels rise off the ground; keep the chest up and the weight centered over mid-foot.', 14, NULL::text[], NULL::text[], 'advanced', 4, 6, NULL::integer, true, false),
  ('Barbell Front Squat', 'barbell-front-squat', 'Strength', NULL, 'Squat', 'Front-loaded barbell squat -- shifts load anterior, demanding more quad and upper-back strength while reinforcing an upright torso.', NULL, '{"Barbell","Squat Rack"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Rest the bar across the front of the shoulders with elbows high, squat down keeping the torso upright, then drive back up.', 'A strong quad-dominant burn with the upper back working hard to keep the bar racked and the torso vertical.', 'Do not let the elbows drop, which collapses the rack position and rounds the upper back.', 15, NULL::text[], NULL::text[], 'advanced', 4, 5, NULL::integer, true, false),
  ('Trap Bar Deadlift', 'trap-bar-deadlift', 'Strength', NULL, 'Hip Hinge', 'Deadlift performed inside a trap/hex bar -- a safer-leverage total-body pulling strength movement than a straight bar deadlift for most athletes.', NULL, '{"Trap Bar"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Stand inside the bar, hinge at the hips with a flat back, grip the handles, and drive through the floor to stand tall, then lower with control.', 'A strong, whole-body pulling tension through the legs, hips, and back as you drive the floor away.', 'Do not let the hips shoot up faster than the chest; the hips and shoulders should rise together.', 15, NULL::text[], NULL::text[], 'advanced', 4, 5, NULL::integer, true, false),
  ('Barbell Romanian Deadlift', 'barbell-romanian-deadlift', 'Strength', 'hamstring', 'Hip Hinge', 'Barbell RDL -- direct posterior-chain (hamstring/glute) strength work through a hip-hinge pattern, complementing the Nordic curl for hamstring resilience.', NULL, '{"Barbell"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Holding the bar at the thighs, hinge at the hips while keeping the knees softly bent and the bar close to the legs, lowering until a deep hamstring stretch is felt, then drive the hips forward to stand.', 'A deep stretch and loading through the hamstrings on the way down, with a strong glute squeeze at the top.', 'Do not round the lower back to chase extra range; stop the descent where a flat back can be maintained.', 13, NULL::text[], NULL::text[], 'moderate', 4, 8, NULL::integer, true, false),
  ('Single-Leg Romanian Deadlift (Dumbbell)', 'single-leg-rdl-dumbbell', 'Strength', 'hamstring', 'Hip Hinge', 'Unilateral RDL holding a dumbbell -- combines posterior-chain strength with the single-leg balance and stability demands of sprinting and cutting.', NULL, '{"Dumbbell"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Balance on one leg holding a dumbbell in the opposite hand, hinge forward at the hip while the free leg extends back for balance, then return to standing.', 'A strong hamstring and glute stretch in the standing leg, with the core working hard to keep the hips square.', 'Do not let the hips rotate open; keep them square to the ground throughout the hinge.', 11, NULL::text[], NULL::text[], 'advanced', 3, 8, NULL::integer, true, false),
  ('Bulgarian Split Squat (Dumbbell)', 'bulgarian-split-squat-dumbbell', 'Strength', NULL, 'Unilateral', 'Rear-foot-elevated split squat holding dumbbells -- one of the most transferable unilateral leg-strength builders for acceleration and change of direction.', NULL, '{"Dumbbells","Bench"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'With the rear foot elevated on a bench behind you, lower the front knee toward the ground under control, then drive back up through the front leg.', 'A deep quad and glute burn in the front leg, with the back leg providing only light balance support.', 'Do not let the front knee travel far past the toes or let the torso lean too far forward.', 13, NULL::text[], NULL::text[], 'advanced', 3, 8, NULL::integer, true, false),
  ('Walking Lunge (Loaded)', 'walking-lunge-loaded', 'Strength', NULL, 'Unilateral', 'Weighted walking lunge -- builds single-leg strength and stability through a dynamic, traveling pattern rather than a static stance.', NULL, '{"Dumbbells"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Holding dumbbells at the sides, step forward into a lunge, lower the back knee toward the ground, then push through the front leg to step into the next lunge.', 'A continuous quad and glute working sensation as you travel forward, with each leg loading and driving in turn.', 'Do not let the front knee cave inward or let the torso lean forward excessively.', 12, NULL::text[], NULL::text[], 'moderate', 3, 10, NULL::integer, true, false),
  ('Weighted Step-Up', 'weighted-step-up', 'Strength', NULL, 'Unilateral', 'Step-up onto a box holding dumbbells -- single-leg strength with a strong concentric emphasis, mirroring the drive phase of acceleration.', NULL, '{"Dumbbells","Box"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Holding dumbbells, step fully onto a box with one leg, driving through the heel to stand tall, then step back down under control.', 'A strong, driving push through the stepping leg''s glute and quad on the way up.', 'Do not push off the trailing leg to assist; the working leg on the box should do all the lifting.', 11, NULL::text[], NULL::text[], 'moderate', 3, 8, NULL::integer, true, false),
  ('Barbell Hip Thrust', 'barbell-hip-thrust', 'Strength', NULL, 'Hip Extension', 'Loaded hip thrust -- the highest-load glute-strength builder available, directly supporting sprint drive and hip extension power.', NULL, '{"Barbell","Bench"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'With upper back braced on a bench and a barbell across the hips, drive through the heels to extend the hips fully, squeezing the glutes at the top, then lower under control.', 'A maximal glute squeeze at the top of every rep, with the hamstrings assisting.', 'Do not hyperextend the lower back at the top; stop at a straight line from shoulders to knees.', 14, NULL::text[], NULL::text[], 'advanced', 4, 8, NULL::integer, true, false),
  ('Barbell Bench Press', 'barbell-bench-press', 'Strength', NULL, 'Push', 'Barbell bench press -- the standard loaded horizontal press for upper-body strength once bodyweight pressing is no longer sufficient stimulus.', NULL, '{"Barbell","Bench"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Lower the bar under control to the chest, keeping the elbows at roughly 45 degrees, then press back up to full extension.', 'Steady, even chest, shoulder, and tricep tension through the full press.', 'Do not bounce the bar off the chest or let the hips rise off the bench.', 12, NULL::text[], NULL::text[], 'moderate', 4, 8, NULL::integer, true, false),
  ('Dumbbell Bench Press', 'dumbbell-bench-press', 'Strength', NULL, 'Push', 'Dumbbell variation of the bench press -- allows a greater range of motion and independent arm strength development compared to a barbell.', NULL, '{"Dumbbells","Bench"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Press two dumbbells from chest level to full extension above the chest, then lower under control.', 'A deeper stretch through the chest at the bottom than a barbell press, with even tension through the press.', 'Do not let the dumbbells drift together or apart unevenly; keep the path controlled and symmetric.', 11, NULL::text[], NULL::text[], 'moderate', 4, 10, NULL::integer, true, false),
  ('Barbell Overhead Press', 'barbell-overhead-press', 'Strength', NULL, 'Push', 'Standing barbell press overhead -- builds shoulder strength and total-body bracing under load.', NULL, '{"Barbell"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'From the front-rack position, press the bar straight overhead to full extension, then lower under control.', 'Strong shoulder and tricep tension with the core bracing hard to prevent the lower back from arching.', 'Do not lean back excessively to press the bar up; keep the ribs down and core braced.', 11, NULL::text[], NULL::text[], 'advanced', 4, 6, NULL::integer, true, false),
  ('Dumbbell Overhead Press', 'dumbbell-overhead-press', 'Strength', NULL, 'Push', 'Standing dumbbell press overhead -- shoulder strength with independent arm paths, useful for addressing left-right asymmetries.', NULL, '{"Dumbbells"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Press two dumbbells from shoulder height straight overhead, then lower under control.', 'Even shoulder and tricep tension through both arms with the core staying braced.', 'Do not let one arm lag or press unevenly; slow down if symmetry breaks down.', 10, NULL::text[], NULL::text[], 'moderate', 3, 8, NULL::integer, true, false),
  ('Pull-Up', 'pull-up', 'Strength', NULL, 'Pull', 'Overhand vertical pulling movement -- a loadable progression beyond the bodyweight Inverted Row for upper-back and grip strength.', NULL, '{"Pull-Up Bar"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Hang from a bar with an overhand grip and pull the chin above the bar, then lower under control to a full hang.', 'A strong pull through the lats and upper back on the way up, with a controlled stretch on the way down.', 'Do not kip or swing to generate momentum; keep the movement strict.', 11, NULL::text[], NULL::text[], 'advanced', 4, 6, NULL::integer, true, false),
  ('Chin-Up', 'chin-up', 'Strength', NULL, 'Pull', 'Underhand vertical pulling movement -- similar to the pull-up with greater bicep involvement, useful variation for grip and pulling volume.', NULL, '{"Pull-Up Bar"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Hang from a bar with an underhand grip and pull the chin above the bar, then lower under control to a full hang.', 'A strong pull through the lats and biceps on the way up.', 'Do not kip or swing to generate momentum; keep the movement strict.', 10, NULL::text[], NULL::text[], 'advanced', 4, 6, NULL::integer, true, false),
  ('Lat Pulldown', 'lat-pulldown', 'Strength', NULL, 'Pull', 'Cable-machine vertical pull -- an accessible entry point to vertical pulling strength for athletes not yet able to perform a full pull-up.', NULL, '{"Cable Machine"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Pull the bar down to the upper chest, squeezing the shoulder blades together, then let it return under control.', 'A strong lat and upper-back contraction on the pull, with a full stretch on the return.', 'Do not lean back excessively or use body momentum to pull the bar down.', 8, NULL::text[], NULL::text[], 'beginner', 3, 10, NULL::integer, true, false),
  ('Seated Cable Row', 'seated-cable-row', 'Strength', NULL, 'Pull', 'Horizontal cable row -- loadable back-strength work complementing the bodyweight Inverted Row and band row.', NULL, '{"Cable Machine"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Pull the handle to the torso, squeezing the shoulder blades together, then return under control with a full stretch forward.', 'A strong mid-back squeeze at the finish of every pull.', 'Do not round the lower back or use torso swing to move the weight.', 9, NULL::text[], NULL::text[], 'moderate', 3, 10, NULL::integer, true, false),
  ('Dumbbell Bent-Over Row', 'dumbbell-bent-over-row', 'Strength', NULL, 'Pull', 'Single or double-arm dumbbell row from a hinged position -- back strength with an added hip-hinge stability demand.', NULL, '{"Dumbbells"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Hinge forward at the hips with a flat back, and row the dumbbell(s) to the ribs, squeezing the shoulder blade, then lower under control.', 'A strong contraction through the mid-back with the hips staying locked in the hinge.', 'Do not let the torso rotate or rock to help the pull.', 10, NULL::text[], NULL::text[], 'moderate', 3, 10, NULL::integer, true, false),
  ('Kettlebell Swing', 'kettlebell-swing', 'Strength', NULL, 'Hip Hinge', 'Ballistic hip-hinge swing -- builds explosive hip extension power with a strength-conditioning hybrid demand.', NULL, '{"Kettlebell"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Hinge at the hips to swing the kettlebell back between the legs, then explosively extend the hips to drive it forward to chest height, letting it float before the next hinge.', 'A powerful, snapping hip extension on every rep, driven by the glutes and hamstrings, not the arms.', 'Do not squat the movement or use the arms to lift the bell; the power must come from the hip snap.', 13, NULL::text[], NULL::text[], 'moderate', 4, 15, NULL::integer, true, true),
  ('Kettlebell Goblet Squat', 'kettlebell-goblet-squat', 'Strength', NULL, 'Squat', 'Front-loaded kettlebell squat -- an accessible loaded squat pattern that reinforces an upright torso and full depth.', NULL, '{"Kettlebell"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Hold the kettlebell at the chest and squat down to full depth, keeping the elbows inside the knees, then drive back up.', 'A deep quad and glute burn with the upper back working to keep the chest tall.', 'Do not let the heels lift or the chest collapse forward at the bottom.', 10, NULL::text[], NULL::text[], 'moderate', 3, 10, NULL::integer, true, false),
  ('Farmer''s Carry', 'farmers-carry', 'Strength', NULL, 'Loaded Carry', 'Heavy loaded walk holding weight at the sides -- builds grip, trunk stability, and total-body strength endurance with direct carryover to fatigue-resistant posture.', NULL, '{"Dumbbells or Kettlebells"}'::text[], NULL::text[], NULL::uuid[], '{"Distance"}'::text[], 'Hold a heavy weight in each hand and walk a set distance while keeping the torso tall and shoulders back.', 'A demanding grip and trunk-bracing challenge that builds throughout the carry.', 'Do not let the shoulders round forward or the walk turn into a shuffle; keep posture tall.', 9, NULL::text[], NULL::text[], 'moderate', 3, 1, NULL::integer, true, false),
  ('Suitcase Carry (Single-Arm)', 'suitcase-carry-single-arm', 'Strength', NULL, 'Loaded Carry', 'Single-arm loaded carry -- adds an anti-lateral-flexion core demand on top of the standard farmer''s carry.', NULL, '{"Dumbbell or Kettlebell"}'::text[], NULL::text[], NULL::uuid[], '{"Distance"}'::text[], 'Hold a heavy weight in one hand and walk a set distance, resisting the pull toward that side with the obliques, then switch sides.', 'A strong oblique and core bracing sensation resisting the sideways pull of the weight.', 'Do not let the torso lean toward the loaded side; stay upright and resist the pull.', 10, NULL::text[], NULL::text[], 'moderate', 3, 1, NULL::integer, true, false),
  ('Sled Push', 'sled-push', 'Strength', NULL, 'Horizontal Push', 'Loaded sled push -- pure horizontal force production with zero eccentric braking demand, ideal for building acceleration-specific strength safely.', NULL, '{"Sled"}'::text[], NULL::text[], NULL::uuid[], '{"Distance"}'::text[], 'Drive the sled forward with an aggressive forward lean, taking short, powerful, driving steps.', 'A demanding, full-body driving sensation through the legs and hips, similar to the drive phase of a sprint.', 'Do not let the hips rise up tall; stay low and driving through the whole push.', 14, NULL::text[], NULL::text[], 'advanced', 4, 1, NULL::integer, true, true),
  ('Sled Pull (Reverse Drag)', 'sled-pull-reverse-drag', 'Strength', NULL, 'Deceleration Strength', 'Backward sled drag -- builds eccentric quad strength and knee resilience, directly supporting deceleration mechanics.', NULL, '{"Sled"}'::text[], NULL::text[], NULL::uuid[], '{"Distance"}'::text[], 'Facing the sled, walk backward dragging it, taking controlled steps and keeping the shins tracking over the toes.', 'A deep, sustained quad burn with every backward step.', 'Do not rush the steps; controlled, driven backward steps build more quad strength than fast shuffling.', 12, NULL::text[], NULL::text[], 'moderate', 3, 1, NULL::integer, true, false),
  ('Pallof Press', 'pallof-press', 'Strength', NULL, 'Anti-Rotation', 'Cable or band anti-rotation press -- core stability work resisting rotation, directly supporting tackling-angle and contact stability.', NULL, '{"Cable Machine or Resistance Band"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Stand side-on to the anchor, hold the handle at the chest, and press it straight out in front of the body, resisting the pull that tries to rotate the torso, then return.', 'The core working hard to resist rotation throughout the press and return.', 'Do not let the hips or shoulders rotate toward the anchor; keep the torso square.', 6, NULL::text[], NULL::text[], 'moderate', 3, 10, NULL::integer, true, false),
  ('Landmine Press', 'landmine-press', 'Strength', NULL, 'Push', 'Single-arm press of a barbell anchored in a landmine unit -- a shoulder-friendly loaded pressing option along a natural arcing path.', NULL, '{"Barbell","Landmine Attachment"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Hold the end of the barbell at shoulder height and press it up and away along its natural arc, then lower under control.', 'A strong shoulder and chest press with the core bracing against the offset load.', 'Do not let the torso rotate excessively to assist the press; keep the core braced.', 9, NULL::text[], NULL::text[], 'moderate', 3, 8, NULL::integer, true, false),
  ('Landmine Rotation', 'landmine-rotation', 'Strength', NULL, 'Rotational', 'Rotational sweep of a landmine-anchored barbell across the body -- builds rotational core power that transfers to throwing and cutting.', NULL, '{"Barbell","Landmine Attachment"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Hold the end of the barbell with both hands and rotate it from one hip to the other in a controlled arc, driving with the hips and core.', 'Power generated from the hips and core sweeping through to the arms.', 'Do not let the arms do the work independent of the hips; the rotation should originate low.', 8, NULL::text[], NULL::text[], 'moderate', 3, 10, NULL::integer, true, false),
  ('Renegade Row', 'renegade-row', 'Strength', NULL, 'Anti-Rotation', 'Alternating dumbbell row performed from a plank position -- combines back strength with anti-rotation core stability.', NULL, '{"Dumbbells"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'From a plank position with hands on dumbbells, row one dumbbell to the ribs while resisting rotation through the hips, then lower and switch sides.', 'A strong back contraction on the row combined with intense core bracing to keep the hips square.', 'Do not let the hips rotate toward the rowing side; keep them level throughout.', 9, NULL::text[], NULL::text[], 'advanced', 3, 8, NULL::integer, true, false),
  ('Ab Wheel Rollout', 'ab-wheel-rollout', 'Strength', NULL, 'Core Anti-Extension', 'Rollout on an ab wheel -- one of the most demanding anti-extension core exercises, building the trunk stiffness needed to transfer force through contact.', NULL, '{"Ab Wheel"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'From a kneeling position, roll the wheel forward as far as control allows while keeping the core braced and the lower back flat, then pull back to the start.', 'Intense core tension resisting the lower back from arching as the wheel extends away.', 'Do not let the lower back sag or arch; stop the roll-out at the range where control is lost.', 9, NULL::text[], NULL::text[], 'advanced', 3, 8, NULL::integer, true, false),
  ('Reverse Hyperextension', 'reverse-hyperextension', 'Strength', NULL, 'Hip Extension', 'Posterior-chain hip extension performed with the torso fixed and the legs moving -- glute and lower-back strength with minimal spinal loading.', NULL, '{"Bench or GHD"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Lying face down with the hips at the edge of a bench and legs hanging, raise the legs behind you to hip height using the glutes and hamstrings, then lower under control.', 'A strong glute and hamstring contraction with the lower back staying relaxed.', 'Do not swing the legs using momentum; keep the movement controlled and driven by the glutes.', 7, NULL::text[], NULL::text[], 'moderate', 3, 12, NULL::integer, true, false)
) AS v (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.name = v.name AND e.category = v.category
);
