-- isometric: 12 new exercise-catalog rows.
-- Source: Ljubljana Frogs 2026 Summer Pre-Season Program (physio-approved
-- 9-week block) + standard flag-football S&C/technical drill taxonomy.
-- Idempotent on (name, category) via WHERE NOT EXISTS (no unique constraint
-- exists on exercises besides the id PK).

INSERT INTO public.exercises (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.* FROM (VALUES
  ('Wall Sit', 'wall-sit', 'Isometric', NULL, 'Squat Hold', 'Foundational quad/glute isometric hold for tendon stiffness and positional strength.', NULL, '{"Wall"}'::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Back flat against a wall, slide down until thighs are parallel to the ground, knees at 90 degrees. Hold.', 'Deep, steady burn through the front of the thighs that builds over the hold, not a sharp pain.', 'Do not let the knees creep past the toes or the lower back round off the wall.', 6, NULL::text[], NULL::text[], 'beginner', 3, NULL::integer, 40, true, false),
  ('Iso Squat Hold (100-120 deg)', 'iso-squat-hold-mid-range', 'Isometric', NULL, 'Squat Hold', 'Mid-range squat isometric at the sticking-point knee angle -- builds tendon stiffness through the range that matters for acceleration.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Lower into a squat until the knee angle is roughly 100-120 degrees (thighs above parallel). Hold that exact position without sinking or rising.', 'Constant tension through quads and glutes with zero movement -- the position should not drift.', 'Do not let the hold slide toward a deeper squat over the set; reset if position degrades.', 8, NULL::text[], NULL::text[], 'moderate', 4, NULL::integer, 35, true, false),
  ('Iso Wall Sit (Loaded)', 'iso-wall-sit-loaded', 'Isometric', NULL, 'Squat Hold', 'Wall sit progression with external resistance (band across thighs or partner-applied pressure) for advanced tendon loading.', NULL, '{"Wall","Resistance Band"}'::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Set up as a standard wall sit with a band looped around the thighs for added tension, or have a partner apply gentle downward pressure on the shoulders.', 'Same quad/glute burn as a bodyweight wall sit, arriving faster and demanding more focus to hold form.', 'Do not let the added load pull the knees inward or the hips shift off the wall.', 10, NULL::text[], NULL::text[], 'advanced', 3, NULL::integer, 45, true, false),
  ('Maximal Iso Squat Push', 'maximal-iso-squat-push', 'Isometric', NULL, 'Squat Hold', 'Near-maximal effort isometric push against a fixed, immovable object -- peak force isometric for late-phase force development.', NULL, '{"Fixed Object or Band Anchor"}'::text[], NULL::text[], NULL::uuid[], '{"Duration","Effort"}'::text[], 'In a quarter-squat position, push maximally against an immovable object (rack pin, wall, heavily anchored band) for the full duration. Nothing moves -- all output is internal.', 'A hard, near-maximal push you could not sustain for more than a few seconds -- true 95-100% effort.', 'Do not hold your breath through the whole rep; brace and breathe. Stop immediately if the lower back takes over from the legs.', 12, NULL::text[], NULL::text[], 'advanced', 5, NULL::integer, 6, true, true),
  ('Iso Split-Squat Hold', 'iso-split-squat-hold', 'Isometric', NULL, 'Lunge Hold', 'Single-leg isometric hold in a split stance -- builds unilateral tendon stiffness for deceleration and change of direction.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Step into a lunge stance and lower until both knees are near 90 degrees. Hold that exact mid-range position on the front leg.', 'Front-leg quad and glute burn with the back leg providing light balance support only.', 'Do not let the front knee cave inward or let weight shift onto the back leg to escape the hold.', 8, NULL::text[], NULL::text[], 'moderate', 3, NULL::integer, 20, true, false),
  ('Iso Hamstring Hold (Nordic Mid-Range)', 'iso-hamstring-hold-nordic', 'Isometric', 'hamstring', 'Hip Hinge Hold', 'Isometric hold at the hardest mid-range point of the Nordic curl -- targets the same eccentric-hamstring injury-prevention window without the full eccentric lower.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Kneel with ankles anchored (partner or GHD). Lower to roughly 45 degrees from vertical -- the hardest point of the range -- and hold, resisting the fall with the hamstrings.', 'Deep hamstring tension held steady, not a burning stretch -- the back of the thigh should feel like it is doing continuous work.', 'Do not let the hips pike or the lower back round to escape the load; if the hold breaks, the set is over.', 14, NULL::text[], NULL::text[], 'advanced', 4, NULL::integer, 6, true, true),
  ('Iso Push-Up Hold (Top)', 'iso-pushup-hold-top', 'Isometric', NULL, 'Push Hold', 'Isometric top-of-push-up plank hold -- builds shoulder and core stability for contact and ground-based recovery positions.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Hold the top push-up position: arms locked, body in a straight line from heels to head, core braced.', 'Steady tension through the shoulders, chest, and core with a rigid, board-like body line.', 'Do not let the hips sag or pike; reset the brace if the line breaks.', 4, NULL::text[], NULL::text[], 'beginner', 3, NULL::integer, 30, true, false),
  ('Iso Push-Up Hold (Mid-Range)', 'iso-pushup-hold-mid', 'Isometric', NULL, 'Push Hold', 'Isometric hold at the halfway point of a push-up -- builds pressing tendon stiffness through the hardest part of the range.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Lower to the halfway point of a push-up (elbows near 90 degrees) and hold, keeping the body rigid.', 'Constant chest, shoulder, and tricep tension without the body dropping or rising.', 'Do not let the elbows flare wide or the lower back sag toward the floor.', 6, NULL::text[], NULL::text[], 'moderate', 3, NULL::integer, 20, true, false),
  ('Single-Leg Iso Calf Hold', 'single-leg-iso-calf-hold', 'Isometric', NULL, 'Calf Hold', 'Single-leg calf isometric at end-range -- supports ankle/Achilles tendon stiffness for repeated sprint contacts.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Rise onto the ball of one foot to full calf contraction and hold, using a wall or rail for light balance only.', 'A deep, sustained calf contraction that should not need the support hand to bear real weight.', 'Do not let the ankle roll outward or the heel drift back down mid-hold.', 5, NULL::text[], NULL::text[], 'moderate', 3, NULL::integer, 25, true, false),
  ('Copenhagen Plank Hold (Full)', 'copenhagen-plank-hold-full', 'Isometric', 'hamstring', 'Adductor Hold', 'Full (long-lever) Copenhagen plank isometric -- the advanced progression once the bent-knee version is easy, for groin/adductor resilience.', NULL, '{"Bench"}'::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Lie on your side with the top foot on a bench and the leg fully extended (not bent). Press the hips up into a straight line, held entirely by the top-leg adductor.', 'A much stronger adductor pull than the bent-knee version -- the top leg is doing significantly more work.', 'Regress to the bent-knee Copenhagen Plank immediately if the hips cannot stay level.', 12, NULL::text[], NULL::text[], 'advanced', 3, NULL::integer, 20, true, false),
  ('Prone Hip Extension Iso Hold', 'prone-hip-extension-iso-hold', 'Isometric', NULL, 'Hip Extension Hold', 'Isometric glute/hamstring hold at end-range hip extension -- reinforces posterior-chain lockout used in sprint drive.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Lie face down, lift one leg a few inches off the ground to full hip extension, and hold without arching the lower back.', 'A steady glute and hamstring squeeze in the lifted leg with a flat, braced lower back.', 'Do not lift the leg high enough that the lower back arches to compensate.', 4, NULL::text[], NULL::text[], 'beginner', 3, NULL::integer, 20, true, false),
  ('Band-Resisted Iso Row Hold', 'band-resisted-iso-row-hold', 'Isometric', NULL, 'Row Hold', 'Isometric mid-row hold against band resistance -- builds scapular/upper-back stability for tackling angles and ball security.', NULL, '{"Resistance Band"}'::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Anchor a band at chest height, pull to the mid-row position (elbows tucked, shoulder blades squeezed), and hold.', 'Constant tension across the upper back and rear shoulders with the chest tall throughout.', 'Do not let the shoulders shrug toward the ears or the lower back arch to help the pull.', 6, NULL::text[], NULL::text[], 'moderate', 3, NULL::integer, 25, true, false)
) AS v (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.name = v.name AND e.category = v.category
);
