
-- Update calf & Achilles knowledge entries with evidence-upgraded content (v1.0.1)

UPDATE knowledge_base_entries SET
  answer = 'Modern calf and Achilles assessment utilizes isometric testing using force plates and specialized equipment like VALD ForceFrame. Testing includes knee-straight (gastrocnemius dominant) and knee-bent (soleus dominant) positions to assess each muscle group independently. Objective metrics include peak force, rate of force development, and bilateral asymmetries. Regular monitoring helps identify deficits before injury occurs and tracks rehabilitation progress. Use MDC (minimal detectable change) to interpret change and asymmetry; reliability depends on joint position and setup standardization—instrumented plantarflexion testing shows excellent reliability at neutral ankle position. The 10–15% asymmetry threshold is commonly used but often not evidence-based; better to use MDC, individual baselines, and context (sport, task, season) because injury/performance links are inconsistent.',
  protocols = '{"equipment": ["ForceFrame", "ForceDecks"], "test_positions": ["knee_straight_gastrocnemius", "knee_bent_soleus"], "metrics": ["peak_force", "rate_of_force_development", "bilateral_asymmetry", "MDC_for_interpretation"], "frequency": "weekly_during_rehab_monthly_for_monitoring", "outcome_measures_note": "VISA-A historically common; Rasch/COSMIN raises validity concerns—consider newer instruments (JOSPT CPG)", "quantitative_claims": [{"metric": "bilateral_asymmetry", "operator": ">=", "value_range": {"min": 10, "max": 15}, "unit": "percent", "population_context": "athletes", "interpretation": "commonly_used_often_arbitrary_prefer_MDC_and_context", "source_ref": "systematic_review_2022"}]}'::jsonb,
  best_practices = ARRAY['Test both knee-straight and knee-bent positions', 'Use objective force measurement technology', 'Use MDC to interpret change and asymmetry; standardize joint position and setup for reliability', 'Track rate of force development', 'Regular monitoring for injury prevention', 'Compare to normative data for sport']
WHERE topic = 'calf_achilles_assessment_protocols';

UPDATE knowledge_base_entries SET
  answer = 'Common injuries include Achilles tendinopathy (overuse and tendon degeneration), calf strains (acute muscle tears, often in the medial gastrocnemius), Achilles ruptures (complete tendon failure), and plantaris injuries. Achilles tendinopathy is highly prevalent in running and jumping athletes due to repetitive loading. Calf strains typically occur during acceleration, sprinting, or push-off movements. Risk factors include rapid training load increases, previous injury history, reduced calf strength and endurance, biomechanical issues, and inadequate recovery. AFL registry data: soleus ~25.4 ± 16.2 days vs gastrocnemius ~19.1 ± 14.1 days RTP; MRI grade and connective tissue involvement affect time to return. Symptoms are not reliable guides for rehabilitation—use objective measures.',
  protocols = COALESCE(protocols, '{}'::jsonb) || '{"quantitative_claims": [{"metric": "soleus_RTP_days", "operator": "=", "value_range": {"mean": 25.4, "SD": 16.2}, "unit": "days", "population_context": "AFL_registry", "interpretation": "mean_SD"}, {"metric": "gastrocnemius_RTP_days", "operator": "=", "value_range": {"mean": 19.1, "SD": 14.1}, "unit": "days", "population_context": "AFL_registry", "interpretation": "mean_SD"}]}'::jsonb
WHERE topic = 'calf_achilles_injuries_pathologies';

UPDATE knowledge_base_entries SET
  answer = 'Effective rehabilitation follows progressive loading principles: isometrics early for tolerated loading and strength stimulus (immediate analgesia is not reliable in Achilles tendinopathy—evidence is mixed). Progressive tendon loading is critical: heavy slow resistance (HSR) and eccentrics both work; choose based on patient preference, equipment, irritability, and adherence. Then plyometric and explosive work for return to sport. Load management is critical—tendinopathy responds to progressive loading, not rest. Objective strength testing guides progression through phases. Return to sport requires multidomain criteria: strength (one component), function, sport-specific tasks (heel-rise endurance, hop capacity, plyometric tolerance), and symptom response. Per JOSPT CPG; strength alone is insufficient. Trainable changes in one domain (e.g. isometric) do not necessarily transfer to others—comprehensive assessment is critical.',
  summary = 'Progressive loading: isometrics, HSR or eccentrics (both work), plyometrics. Load management critical. Multidomain RTS criteria (strength, function, sport-specific, symptoms).',
  protocols = '{"phases": ["pain_management_isometric", "heavy_slow_resistance_training", "eccentric_loading", "plyometric_training", "return_to_sport"], "key_metrics": ["strength", "pain_levels", "function", "RFD", "sport_specific_tasks"], "progression_criteria": "objective_strength_measures_guide_advancement", "return_to_sport_criteria": "multidomain_strength_function_sport_specific_symptom_response", "quantitative_claims": [{"metric": "rts_criteria", "operator": "=", "value_range": {}, "unit": "multidomain", "population_context": "return_to_sport", "interpretation": "strength_function_sport_specific_symptom_response_per_CPG"}]}'::jsonb,
  best_practices = ARRAY['Progressive loading is key for tendinopathy', 'Isometrics for early tolerated loading—immediate analgesia not reliable', 'Heavy slow resistance builds tendon capacity', 'Progressive tendon loading critical; HSR and eccentrics both effective', 'Use objective testing to guide progression', 'Meet multidomain RTS criteria (strength + function + sport-specific + symptoms)', 'Address biomechanical and load factors']
WHERE topic = 'calf_achilles_rehabilitation';

UPDATE knowledge_base_entries SET
  answer = 'Prevention focuses on building adequate calf strength (especially soleus), implementing proper load management, including eccentric training programs, addressing biomechanical issues, and monitoring training loads. Regular strength testing identifies deficits before injury occurs. Eccentric calf exercises have been shown to reduce Achilles tendinopathy risk. Avoiding rapid training load increases is critical—no well-defined weekly load threshold is proven; load changes should be individualized and monitored (pain response, function, recovery, objective capacity). Bilateral asymmetries: 10–15% is commonly used but often arbitrary; better to use MDC, individual baselines, and context (sport, task, season) because evidence is inconsistent. Most demanding tasks (jumps, accelerations) place over 12x bodyweight through the calf MTU—adequate strength and stiffness are essential.',
  protocols = COALESCE(protocols, '{}'::jsonb) || '{"quantitative_claims": [{"metric": "bilateral_asymmetry", "operator": ">=", "value_range": {"min": 10, "max": 15}, "unit": "percent", "population_context": "athletes", "interpretation": "commonly_used_often_arbitrary_prefer_MDC_and_context", "source_ref": "systematic_review_2022"}]}'::jsonb,
  best_practices = ARRAY['Include regular calf strengthening (gastrocnemius and soleus)', 'Implement eccentric training programs', 'Monitor training loads and avoid spikes', 'Regular strength testing to identify deficits', 'Monitor asymmetries with individual baselines and context', 'Proper warm-up and cool-down protocols', 'Progressive return from time off', 'Monitor fatigue and recovery']
WHERE topic = 'calf_achilles_injury_prevention';

UPDATE knowledge_base_entries SET
  answer = 'The gastrocnemius (knee-straight) and soleus (knee-bent) have different functions and injury profiles. AFL registry: soleus ~25.4 ± 16.2 days vs gastrocnemius ~19.1 ± 14.1 days RTP; soleus often presents with subtler symptoms. MRI grade/connective tissue involvement affects RTP time. Test both positions independently: knee-straight for gastrocnemius dominance, knee-bent 90° for soleus. Emphasize soleus for running endurance and Achilles loading—it has greater oxidative capacity and is primary plantar flexor in many activities. Gastrocnemius contributes more to explosive movements. Both are needed for sprinting and jumping; address imbalances. Soleus-specific strengthening (seated calf raises, knee-bent holds) important for tendinopathy and running athletes.',
  protocols = '{"gastrocnemius_test": "knee_straight_plantar_flexion", "soleus_test": "knee_bent_90_plantar_flexion", "soleus_exercises": ["seated_calf_raise", "knee_bent_isometric_hold"], "quantitative_claims": [{"metric": "soleus_RTP_days", "operator": "=", "value_range": {"mean": 25.4, "SD": 16.2}, "unit": "days", "population_context": "AFL_registry", "interpretation": "mean_SD"}, {"metric": "gastrocnemius_RTP_days", "operator": "=", "value_range": {"mean": 19.1, "SD": 14.1}, "unit": "days", "population_context": "AFL_registry", "interpretation": "mean_SD"}]}'::jsonb
WHERE topic = 'soleus_gastrocnemius_differentiation';
