-- power batch 2: 5 new exercise-catalog rows (advanced reactive/ballistic power).
-- Idempotent on (name, category) via WHERE NOT EXISTS.

INSERT INTO public.exercises (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.* FROM (VALUES
  ('Depth Jump (Full)', 'depth-jump-full', 'Power', NULL, 'Reactive', 'Step off a box and immediately rebound into a maximal vertical jump -- the full-intensity reactive-strength plyometric, appropriate once the Depth Drop to Stick Landing is mastered.', NULL, '{"Plyo Box"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Contact Time"}'::text[], 'Step off a box, and the instant the feet touch the ground, explode immediately into a maximal vertical jump with minimal ground contact time.', 'A sharp, reactive rebound -- the ground contact should feel almost like touching a hot surface.', 'Do not let ground contact time creep up into a slow squat-and-jump; if that happens, lower the box height.', 16, NULL::text[], NULL::text[], 'advanced', 4, 4, NULL::integer, true, true),
  ('Single-Leg Bound for Distance', 'single-leg-bound-distance', 'Power', NULL, 'Horizontal', 'Maximal single-leg bound for distance -- unilateral horizontal power that isolates and identifies left-right power asymmetries.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Distance","Reps"}'::text[], 'From a single-leg stance, bound forward for maximal distance, landing balanced on the same leg, then reset and repeat.', 'A maximal, explosive push through the hip, knee, and ankle of the jumping leg.', 'Do not land on the opposite leg to save balance; the landing leg must match the takeoff leg.', 14, NULL::text[], NULL::text[], 'advanced', 3, 4, NULL::integer, true, true),
  ('Rotational Med Ball Scoop Toss', 'rotational-med-ball-scoop-toss', 'Power', NULL, 'Rotational', 'Low-to-high rotational medicine ball toss -- builds explosive rotational power through the hips and trunk with a vertical force component.', NULL, '{"Medicine Ball"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Start with the ball low and to one side, then explosively rotate and extend to toss the ball up and away to the opposite side.', 'A powerful, whipping rotation driven by the hips and legs, not just the arms.', 'Do not round the lower back reaching for the ball at the bottom; keep the spine neutral.', 11, NULL::text[], NULL::text[], 'moderate', 3, 8, NULL::integer, true, false),
  ('Kettlebell Snatch', 'kettlebell-snatch', 'Power', NULL, 'Explosive', 'Single-arm ballistic kettlebell snatch from between the legs to overhead -- total-body explosive power and hip-drive under load.', NULL, '{"Kettlebell"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Hike the kettlebell back between the legs, then explosively extend the hips to drive it upward, punching the hand through to lock it out overhead.', 'An explosive hip snap driving the bell upward, finishing with a quick punch-through at the top.', 'Do not muscle the bell up with the arm; the drive must come from the hip extension.', 13, NULL::text[], NULL::text[], 'advanced', 4, 6, NULL::integer, true, true),
  ('Trap Bar Jump Shrug', 'trap-bar-jump-shrug', 'Power', NULL, 'Vertical', 'Explosive triple-extension pull from a trap bar finishing in a small jump -- develops rate of force development for a loaded lower body.', NULL, '{"Trap Bar"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'From a hip-hinge start, explosively extend the hips, knees, and ankles to jump slightly off the ground while shrugging the bar upward.', 'A fast, explosive full-body extension with the feet briefly leaving the ground.', 'Do not let the bar drift away from the body during the pull; keep it close throughout.', 14, NULL::text[], NULL::text[], 'advanced', 4, 5, NULL::integer, true, true)
) AS v (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.name = v.name AND e.category = v.category
);
