-- position_specific: 26 new exercise-catalog rows.
-- Source: Ljubljana Frogs 2026 Summer Pre-Season Program (physio-approved
-- 9-week block) + standard flag-football S&C/technical drill taxonomy.
-- Idempotent on (name, category) via WHERE NOT EXISTS (no unique constraint
-- exists on exercises besides the id PK).

INSERT INTO public.exercises (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.* FROM (VALUES
  ('Route Tree -- Slant', 'route-tree-slant', 'Position-Specific', NULL, 'Route Running', 'Quick inside-breaking route off the line -- the fastest-developing route in the tree, timed with a quick release.', NULL, '{"Cones","Football"}'::text[], '{"wr_db","wr"}'::text[], NULL::uuid[], '{"Reps","Release Time"}'::text[], 'Release off the line at a slight outside angle for 2-3 steps, then break sharply inside at 45 degrees, accelerating away from the defender.', 'A quick, decisive break with no rounding -- the change of direction should be sharp and immediate.', 'Do not round the break into a slow arc; the cut should be a single sharp plant-and-go.', 9, NULL::text[], NULL::text[], 'moderate', 1, 6, NULL::integer, true, false),
  ('Route Tree -- Out', 'route-tree-out', 'Position-Specific', NULL, 'Route Running', 'Route breaking sharply toward the sideline at a fixed depth -- requires a hard plant and full 90-degree redirect.', NULL, '{"Cones","Football"}'::text[], '{"wr_db","wr"}'::text[], NULL::uuid[], '{"Reps","Break Depth"}'::text[], 'Run straight upfield to the prescribed depth, plant the inside foot hard, and break at 90 degrees toward the sideline.', 'A firm, decisive plant absorbing real force before driving explosively toward the new direction.', 'Do not drift toward the sideline gradually before the depth mark; the route should be straight until the break point.', 10, NULL::text[], NULL::text[], 'moderate', 1, 6, NULL::integer, true, false),
  ('Route Tree -- Comeback', 'route-tree-comeback', 'Position-Specific', NULL, 'Route Running', 'Deep route that breaks back toward the quarterback -- tests deceleration control and the ability to create separation coming back to the ball.', NULL, '{"Cones","Football"}'::text[], '{"wr_db","wr"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Sprint upfield as if running deep, then decelerate and plant to break back toward the quarterback at an angle, creating separation from the defender''s momentum.', 'A hard deceleration followed by an explosive change of direction back toward the ball.', 'Do not telegraph the comeback by slowing down gradually; the deceleration and break should look identical to a deep route until the last moment.', 11, NULL::text[], NULL::text[], 'advanced', 1, 5, NULL::integer, true, true),
  ('Route Tree -- Post', 'route-tree-post', 'Position-Specific', NULL, 'Route Running', 'Deep route breaking toward the middle of the field at a 45-degree angle -- attacks the deep middle of the defense.', NULL, '{"Cones","Football"}'::text[], '{"wr_db","wr"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Run upfield at speed, then break at roughly 45 degrees toward the middle of the field while maintaining top-end speed through the cut.', 'A fast break that loses minimal speed -- the angle change should happen without a full deceleration.', 'Do not slow down significantly to make the cut; a post is run through at speed, not decelerated into.', 11, NULL::text[], NULL::text[], 'advanced', 1, 5, NULL::integer, true, false),
  ('Route Tree -- Corner', 'route-tree-corner', 'Position-Specific', NULL, 'Route Running', 'Deep route breaking toward the sideline and end zone corner at a 45-degree angle -- the mirror image of the post route.', NULL, '{"Cones","Football"}'::text[], '{"wr_db","wr"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Run upfield at speed, then break at roughly 45 degrees toward the sideline corner while maintaining speed through the cut.', 'A fast, speed-preserving break toward the corner, mirroring the post route mechanics to the opposite side.', 'Do not round the break into a lazy diagonal drift; commit to the angle change decisively.', 11, NULL::text[], NULL::text[], 'advanced', 1, 5, NULL::integer, true, false),
  ('Route Tree -- Fade', 'route-tree-fade', 'Position-Specific', NULL, 'Route Running', 'Deep vertical route drifting toward the sideline -- pure top-end speed with a slight sideline lean, used to win one-on-one deep.', NULL, '{"Cones","Football"}'::text[], '{"wr_db","wr"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Release and run vertically upfield at full speed, gradually drifting toward the sideline while maintaining top-end speed the entire route.', 'Relaxed, high-speed running with a subtle lean toward the sideline, never a hard cut.', 'Do not make a sharp cut toward the sideline; the fade is a gradual drift, not a break.', 12, NULL::text[], NULL::text[], 'advanced', 1, 4, NULL::integer, true, true),
  ('Route Tree -- Curl', 'route-tree-curl', 'Position-Specific', NULL, 'Route Running', 'Route that runs upfield then turns back to face the quarterback at a fixed depth -- creates a stationary target with the body shielding legally (no hand use on the defender).', NULL, '{"Cones","Football"}'::text[], '{"wr_db","wr"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Run upfield to the prescribed depth, plant, and turn to face the quarterback, settling into open space with hands ready for the ball.', 'A controlled deceleration into a stable, balanced turn -- ready to move again immediately after the turn.', 'Do not turn your back fully to the quarterback during the turn; keep the eyes coming back to the ball as early as possible.', 8, NULL::text[], NULL::text[], 'moderate', 1, 6, NULL::integer, true, false),
  ('Route Tree -- Option / Choice Route', 'route-tree-option-choice', 'Position-Specific', NULL, 'Route Running', 'Route where the receiver reads the defender''s leverage at the break point and chooses in or out accordingly -- trains the decision-making layer on top of the physical break.', NULL, '{"Cones","Football"}'::text[], '{"wr_db","wr"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Run upfield to the break point, read the defender''s leverage (inside or outside shoulder), and break to the open space accordingly.', 'The physical break should feel identical regardless of which way you choose -- the decision happens in the eyes, not in hesitant feet.', 'Do not slow down to make the read; the decision should happen in stride, not by stopping to look.', 10, NULL::text[], NULL::text[], 'advanced', 1, 6, NULL::integer, true, false),
  ('Route Tree -- Double-Move Release', 'route-tree-double-move-release', 'Position-Specific', NULL, 'Route Running', 'Route that sells one break before continuing into a second, deeper break -- an advanced double-move used to beat aggressive coverage.', NULL, '{"Cones","Football"}'::text[], '{"wr_db","wr"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Sell a hard break in one direction (e.g. an out) convincingly enough to move the defender, then immediately plant and accelerate into the true, deeper route.', 'The first break must be a real, full-commitment plant -- a fake break with no real deceleration will not fool a defender.', 'Do not rush the first break so much it looks obviously fake; sell it with the same effort as a real route.', 13, NULL::text[], NULL::text[], 'advanced', 1, 4, NULL::integer, true, true),
  ('Flag Pull Technique -- Reach and Rip', 'flag-pull-technique-reach-rip', 'Position-Specific', NULL, 'Defensive Technique', 'Correct hand mechanics for pulling a flag at full speed -- reach with one hand, rip cleanly downward-and-away rather than grabbing at the body.', NULL, '{"Flag Belt"}'::text[], '{"wr_db","db"}'::text[], NULL::uuid[], '{"Reps","Success Rate"}'::text[], 'As you close on the ball carrier, extend one hand toward the near-side flag, grip it firmly, and rip it downward and away from the hip in one clean motion. Do not lunge with both hands at the body.', 'A quick, targeted reach-and-pull motion focused entirely on the flag, not on the runner''s body or jersey.', 'Do not tackle, grab clothing, or wrap up the runner with the arms -- pull only the flag, and disengage immediately after.', 6, NULL::text[], NULL::text[], 'moderate', 1, 10, NULL::integer, true, false),
  ('Angle of Pursuit Drill', 'angle-of-pursuit-drill', 'Position-Specific', NULL, 'Defensive Technique', 'Teaches the correct pursuit angle to cut off a ball carrier''s path rather than chasing directly from behind -- the single biggest factor in defensive flag-pull success.', NULL, '{"Cones"}'::text[], '{"wr_db","db"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Starting from an angle behind and to the side of a moving target (partner or cone marker), take the shortest angle to intercept their projected path rather than running directly at their current position.', 'A controlled, calculated sprint on a converging angle, arriving at the interception point in balance, not at a flat sprint from behind.', 'Do not run directly at the ball carrier''s current position; that is always the slower, losing angle.', 9, NULL::text[], NULL::text[], 'moderate', 1, 8, NULL::integer, true, false),
  ('Break-Down Position Drill', 'break-down-position-drill', 'Position-Specific', NULL, 'Defensive Technique', 'Teaches the balanced, low defensive stance used in the final steps before a flag pull attempt -- controls speed so the defender doesn''t overrun the pull.', NULL, NULL::text[], '{"wr_db","db"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Sprint toward a target, and a few steps before reaching it, chop the steps shorter and lower the hips into a wide, balanced stance -- ''breaking down'' speed under control before attempting the pull.', 'A controlled deceleration into a stable, athletic base, ready to react to a last-second cut by the ball carrier.', 'Do not stay upright and fast all the way to the pull attempt; an out-of-control defender misses more flags.', 8, NULL::text[], NULL::text[], 'moderate', 1, 8, NULL::integer, true, false),
  ('Flag Pull vs Evasive Ball Carrier', 'flag-pull-vs-evasive-ball-carrier', 'Position-Specific', NULL, 'Defensive Technique', 'Live reps closing on and pulling the flag of a partner actively trying to evade -- combines pursuit angle, break-down, and reach-and-rip technique under realistic pressure.', NULL, '{"Flag Belt","Partner"}'::text[], '{"wr_db","db"}'::text[], NULL::uuid[], '{"Reps","Success Rate"}'::text[], 'A partner runs at moderate-to-full speed attempting legal evasive moves (change of direction, hesitation) while you pursue on the correct angle, break down, and execute a clean reach-and-rip flag pull.', 'A realistic blend of pursuit, controlled deceleration, and a final decisive hand action, exactly as it happens in a game.', 'Do not grab the runner''s body or jersey if the flag pull is missed; reset and pursue again legally.', 12, NULL::text[], NULL::text[], 'advanced', 1, 8, NULL::integer, true, true),
  ('Evasive Footwork -- Juke Step', 'evasive-footwork-juke-step', 'Position-Specific', NULL, 'Evasive Footwork', 'Lateral fake-and-go footwork used to make a defender commit to the wrong direction before cutting away -- the primary legal evasion tool for a ball carrier (no hand-based flag guarding).', NULL, '{"Cones"}'::text[], '{"wr_db","wr"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Approach a defender (or cone) at speed, plant hard to one side with a real weight shift to sell that direction, then immediately push off that foot and cut explosively the opposite way.', 'A committed, believable fake with real weight transfer, followed by an explosive true cut in the new direction.', 'Do not use the hands or arms to push off or shield the flags from a defender -- evasion must be footwork only.', 11, NULL::text[], NULL::text[], 'advanced', 1, 8, NULL::integer, true, true),
  ('Evasive Footwork -- Hesitation Move', 'evasive-footwork-hesitation-move', 'Position-Specific', NULL, 'Evasive Footwork', 'A deliberate momentary slow-down to disrupt a defender''s pursuit timing, followed by an explosive re-acceleration -- exploits the pursuit angle rather than pure speed.', NULL, '{"Cones"}'::text[], '{"wr_db","wr"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'While running at speed, briefly chop your stride and appear to slow or stutter for a half-step, then explode back to full speed in the same or a new direction.', 'A real, visible change of rhythm during the hesitation, then a sharp re-acceleration -- not just a continuous run at one pace.', 'Do not hesitate so long that you lose all momentum; the move should cost the defender more time than it costs you.', 9, NULL::text[], NULL::text[], 'advanced', 1, 8, NULL::integer, true, false),
  ('Evasive Footwork -- Stutter-Step', 'evasive-footwork-stutter-step', 'Position-Specific', NULL, 'Evasive Footwork', 'A rapid series of short, quick steps used to disguise the true direction of the next cut -- creates hesitation in the defender without a large loss of forward speed.', NULL, '{"Cones"}'::text[], '{"wr_db","wr"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Take several rapid, short choppy steps while approaching a defender, keeping the hips loaded and ready to explode in any direction, then commit hard to the chosen cut.', 'Fast, light, low-amplitude steps that keep options open, followed by a decisive, explosive final cut.', 'Do not let the stutter steps become slow or telegraphed; they should be quick and non-committal until the final cut.', 9, NULL::text[], NULL::text[], 'advanced', 1, 8, NULL::integer, true, false),
  ('Change-of-Direction Sprint (Open Field)', 'change-of-direction-sprint-open-field', 'Position-Specific', NULL, 'Evasive Footwork', 'Open-field running with unpredictable, self-selected direction changes -- builds the decision-making and body-control layer of evasion beyond fixed cone patterns.', NULL, NULL::text[], '{"wr_db","wr"}'::text[], NULL::uuid[], '{"Duration"}'::text[], 'Run in open space at moderate-to-high speed, making your own unpredictable direction changes as if avoiding defenders, staying balanced through every cut.', 'Continuous, athletic, low-center-of-gravity running with quick, self-directed changes of direction.', 'Do not let fatigue turn the cuts sloppy or high-risk for the knees; stop the set if control degrades.', 10, NULL::text[], NULL::text[], 'advanced', 3, NULL::integer, 15, true, false),
  ('Backpedal-to-Break', 'backpedal-to-break', 'Position-Specific', NULL, 'Coverage', 'Backpedal transitioning explosively into a forward break on the ball -- the core defensive-back movement pattern for reacting to a receiver''s route.', NULL, '{"Cones"}'::text[], '{"wr_db","db"}'::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Backpedal in a controlled defensive stance, then on a signal, plant and drive explosively forward and to the side to simulate breaking on a route.', 'A smooth backward-to-forward transition with no wasted false step or stand-up moment before driving.', 'Do not cross the feet during the backpedal, and do not stand upright before the break -- transition directly from the backpedal stance.', 10, NULL::text[], NULL::text[], 'moderate', 1, 8, NULL::integer, true, false),
  ('Pedal-and-Plant', 'pedal-and-plant', 'Position-Specific', NULL, 'Coverage', 'Backpedal with a hard plant-and-redirect at a called angle -- isolates the plant mechanics that precede every defensive break.', NULL, '{"Cones"}'::text[], '{"wr_db","db"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Backpedal for the prescribed distance, then plant hard on the outside foot and redirect at the called angle (45 or 90 degrees) without a forward sprint follow-through.', 'A firm, stable plant absorbing real force with the hips staying low through the redirect.', 'Do not let the plant foot slide or the knee cave inward under the direction change.', 9, NULL::text[], NULL::text[], 'moderate', 1, 10, NULL::integer, true, false),
  ('Backpedal-to-Sprint Transition', 'backpedal-to-sprint-transition', 'Position-Specific', NULL, 'Coverage', 'Full backpedal-to-forward-sprint transition over distance -- the complete defensive-back movement chain from coverage stance to closing speed.', NULL, '{"Cones"}'::text[], '{"wr_db","db"}'::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Backpedal for the prescribed distance, then transition directly into a full-speed forward sprint on a signal, sprinting through a finish line.', 'The fastest possible transition from backward to forward movement, then true top-end sprinting to the finish.', 'Do not add extra steps during the transition; the goal is the fewest possible steps from backpedal to full sprint.', 11, NULL::text[], NULL::text[], 'advanced', 1, 6, NULL::integer, true, true),
  ('Press-Jam Release', 'press-jam-release', 'Position-Specific', NULL, 'Coverage', 'Hand-fighting and footwork drill for a defender in press coverage recovering after a jam attempt -- legal hand-use is limited to a single contact at the line under most flag rules, so recovery footwork matters more than continued hand fighting.', NULL, '{"Partner"}'::text[], '{"wr_db","db"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Start in a press stance opposite a partner release-running past you. Execute a single legal jam/contact at the line if the ruleset allows, then immediately open the hips and recover into a backpedal or turn-and-run to stay with the release.', 'A quick, decisive hip turn and recovery sprint the instant the release direction is read.', 'Do not continue grabbing or hand-fighting down the field; recover with footwork, not extended contact, to stay within legal limits.', 10, NULL::text[], NULL::text[], 'advanced', 1, 8, NULL::integer, true, false),
  ('Snap-and-Protect', 'snap-and-protect', 'Position-Specific', NULL, 'Center Technique', 'Center''s snap motion immediately followed by a protective hand-fight stance -- protects the snapping hand/wrist and establishes a stable base against the rush.', NULL, '{"Football"}'::text[], '{"center"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Execute a clean snap to the quarterback, then immediately snap the head and hands up into a stable, athletic protection stance facing the rusher.', 'A quick, clean transition from the snap motion into a braced, ready stance with no delay.', 'Do not let the head stay down after the snap; the eyes and hands must come up immediately to track the rush.', 7, NULL::text[], NULL::text[], 'moderate', 1, 10, NULL::integer, true, false),
  ('Snap-and-Release (Route)', 'snap-and-release-route', 'Position-Specific', NULL, 'Center Technique', 'Center''s snap immediately followed by releasing into a short route -- many flag-football rulesets allow the center to release as an eligible receiver, so transition speed off the snap matters.', NULL, '{"Football"}'::text[], '{"center"}'::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Execute a clean snap, then release immediately and explosively into a short designated route, catching up to full speed as fast as possible.', 'The fastest possible transition from the snap motion into full-speed running.', 'Do not let the snap itself slow down to make the release faster; the snap must stay clean and accurate first.', 9, NULL::text[], NULL::text[], 'moderate', 1, 8, NULL::integer, true, false),
  ('Rush-Lane Drill', 'rush-lane-drill', 'Position-Specific', NULL, 'Rusher Technique', 'Straight-line and angled rush-lane acceleration from the mark -- trains the rusher''s explosive first steps within the legal rush-count and rush-lane rules.', NULL, '{"Cones"}'::text[], '{"blitzer","rusher"}'::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Start at the mark and, on the snap signal, explode forward through the designated rush lane toward the quarterback''s position as fast as possible.', 'A powerful, low first step immediately followed by full acceleration through the lane.', 'Do not stand up out of the start too early; stay low and driving through the first several steps.', 10, NULL::text[], NULL::text[], 'moderate', 1, 8, NULL::integer, true, false),
  ('Contain Rush Angle Drill', 'contain-rush-angle-drill', 'Position-Specific', NULL, 'Rusher Technique', 'Angled rush pattern designed to contain the quarterback''s escape lane rather than run straight upfield -- teaches the rusher to take away space, not just speed to the mark.', NULL, '{"Cones"}'::text[], '{"blitzer","rusher"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'Rush from the mark on a bending angle that cuts off the quarterback''s likely escape direction, staying under control rather than sprinting straight past the pocket.', 'A controlled, angled sprint that curves to close space rather than a straight-line burst.', 'Do not run so far upfield in a straight line that an escape lane opens up behind you.', 9, NULL::text[], NULL::text[], 'moderate', 1, 6, NULL::integer, true, false),
  ('QB Scramble Escape Drill', 'qb-scramble-escape-drill', 'Position-Specific', NULL, 'QB Mobility', 'Pocket movement and escape footwork under simulated rush pressure -- builds the quarterback''s ability to extend plays and throw on the move.', NULL, '{"Cones","Football"}'::text[], '{"quarterback"}'::text[], NULL::uuid[], '{"Reps"}'::text[], 'From a dropback position, react to a simulated rush angle (partner or cone) by sliding or stepping up in the pocket, then, if the lane is fully closed, scrambling to the side while keeping the eyes downfield.', 'Quick, small, balanced steps within the pocket, transitioning to a controlled scramble only when necessary.', 'Do not turn your back to the defense while scrambling; keep the shoulders open to the field as long as possible.', 10, NULL::text[], NULL::text[], 'advanced', 1, 6, NULL::integer, true, false)
) AS v (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.name = v.name AND e.category = v.category
);
