-- speed: 13 new exercise-catalog rows.
-- Source: Ljubljana Frogs 2026 Summer Pre-Season Program (physio-approved
-- 9-week block) + standard flag-football S&C/technical drill taxonomy.
-- Idempotent on (name, category) via WHERE NOT EXISTS (no unique constraint
-- exists on exercises besides the id PK).

INSERT INTO public.exercises (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.* FROM (VALUES
  ('3-Step Deceleration Drill', '3-step-deceleration-drill', 'Speed', NULL, 'Deceleration', 'Three controlled steps to a full stop from moderate speed -- the direct counterpart to the 3-Step Acceleration Drill for teaching safe braking mechanics.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Build to moderate speed, then decelerate to a complete stop in exactly three steps, dropping the hips and widening the base on the final step.', 'Increasing braking force through the legs on each of the three steps, ending fully balanced and under control.', 'Do not let the knees cave in on the final stopping step or let the torso pitch forward.', 8, NULL::text[], NULL::text[], 'moderate', 1, 8, NULL::integer, true, false),
  ('Sprint-to-Stop (Deceleration)', 'sprint-to-stop-deceleration', 'Speed', NULL, 'Deceleration', 'Full sprint immediately decelerated to a controlled stop -- game-realistic braking demand for route breaks and pursuit angles.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Distance"}'::text[], 'Sprint at full effort for the prescribed distance, then decelerate as quickly and safely as possible to a complete, balanced stop.', 'A hard eccentric braking load through the quads and hips absorbing the sprint''s momentum.', 'Do not let the deceleration turn into an uncontrolled stumble; if it does, extend the braking distance.', 10, NULL::text[], NULL::text[], 'moderate', 1, 6, NULL::integer, true, false),
  ('Build-Up Runs (Progressive Acceleration)', 'build-up-runs-progressive', 'Speed', NULL, 'Acceleration', 'Progressive-effort runs building from roughly 70 percent to 90 percent across the rep -- the reference program''s bridge from drills to full-speed sprinting.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps","Distance"}'::text[], 'Run the prescribed distance building speed progressively -- around 70 percent effort for the first third, 85 percent for the middle third, and 90 percent for the final third.', 'A smooth, gradual rise in speed and effort, never a sudden jump to maximal.', 'Do not sprint at maximal effort from the start; the point is the progressive ramp, not top speed.', 9, NULL::text[], NULL::text[], 'moderate', 1, 3, NULL::integer, true, false),
  ('RSA Sprint Set -- Game-Replica (1:8)', 'rsa-sprint-set-game-replica', 'Speed', NULL, 'Repeated Sprint', 'Repeated 5-second maximal sprints on the real flag-football play-clock rest ratio (~40s rest per sprint, approximately 1:8 work:rest) -- rehearses the exact rhythm of up to 40 plays per game.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps","Decrement %"}'::text[], 'Sprint maximally for approximately 5 seconds (roughly 30m), then rest 40 seconds (the real play-clock rhythm) before the next rep. Repeat for the full set.', 'Each individual sprint should feel close to fully recovered and maximal effort -- fatigue should build gradually across the set, not from rep one.', 'Do not shorten the rest to fit more reps in less time; the 40-second rest IS the training stimulus.', 18, NULL::text[], NULL::text[], 'advanced', 2, 10, NULL::integer, true, true),
  ('RSA Sprint Set -- Tank-Builder (1:4-5)', 'rsa-sprint-set-tank-builder', 'Speed', NULL, 'Repeated Sprint', 'Repeated sprints with deliberately compressed rest (roughly 1:4-5 work:rest) -- incomplete phosphagen recovery forces aerobic-system adaptation, building the repeated-sprint ''tank'' without slow distance running.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps","Decrement %"}'::text[], 'Sprint maximally for approximately 20m, then rest only 20-25 seconds before the next rep -- noticeably shorter than a fully-recovered sprint set.', 'Fatigue should build noticeably across the set -- the later reps will feel slower than the early ones, and that decrement is the point.', 'Do not use this rest scheme on your primary top-speed sprint work; reserve compressed rest for this specific tank-building purpose only.', 20, NULL::text[], NULL::text[], 'advanced', 1, 8, NULL::integer, true, true),
  ('Referee-Load Simulation (Play-Then-Ref)', 'referee-load-simulation-play-then-ref', 'Speed', NULL, 'Mixed Conditioning', 'Sprint block, then sustained jog at refereeing pace, then a second sprint block -- rehearses producing game-speed sprints on legs already loaded by continuous sub-maximal work, the specific worst-case demand of a 7-player roster playing then refereeing.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Decrement Block 1 vs 2"}'::text[], 'Complete a full sprint block (a ''game''), then run a sustained, continuous jog at roughly 50 percent of max pace for 8-12 minutes without stopping (the ''ref'' block), then complete a second sprint block at the same intensity as the first.', 'The second sprint block should feel harder than the first -- track how much your fastest sprint time drops from block one to block two.', 'Do not let the jog block become a walk or a stop; it must stay continuous, sub-maximal movement to replicate real refereeing.', 28, NULL::text[], NULL::text[], 'advanced', 1, 1, NULL::integer, true, true),
  ('Easy Aerobic Base Run', 'easy-aerobic-base-run', 'Speed', NULL, 'Aerobic', 'Continuous, genuinely easy running -- builds the aerobic base that refills the phosphagen tank between sprints, kept off speed days to protect explosiveness.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Run continuously at a comfortable, conversational pace for the prescribed duration. This should never feel like a hard effort.', 'Easy, sustainable breathing throughout -- you should be able to hold a conversation the entire time.', 'Do not let this drift into a harder tempo effort; if breathing becomes labored, slow down.', 10, NULL::text[], NULL::text[], 'beginner', 1, 1, NULL::integer, true, false),
  ('Position Sprint -- WR Release', 'position-sprint-wr-release', 'Speed', 'position_specific', 'Acceleration', 'Explosive release off the line simulating a wide receiver beating press coverage -- sport-specific acceleration pattern rather than a generic straight-line sprint.', NULL, '{"Cones"}'::text[], '{"wr_db"}'::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Start in a receiver stance, react to a signal, and explode off the line at a slight angle to simulate releasing past a defender, accelerating to top speed.', 'A sharp first-step burst followed by smooth acceleration into the route.', 'Do not stand up out of the stance too early; stay low through the first three steps.', 10, NULL::text[], NULL::text[], 'moderate', 1, 6, NULL::integer, true, false),
  ('Position Sprint -- DB Close', 'position-sprint-db-close', 'Speed', 'position_specific', 'Acceleration', 'Closing sprint from a backpedal/shuffle start simulating a defensive back breaking on the ball -- sport-specific acceleration from a defensive ready position.', NULL, '{"Cones"}'::text[], '{"wr_db"}'::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Start in a backpedal or shuffle, react to a signal, and transition explosively into a forward sprint to close distance on a target.', 'A crisp, powerful transition from backward/lateral movement into forward acceleration with no wasted steps.', 'Do not false-step backward before driving forward; the transition should be direct.', 10, NULL::text[], NULL::text[], 'moderate', 1, 6, NULL::integer, true, false),
  ('Flying 20 Sprint (Top Speed)', 'flying-20-sprint-top-speed', 'Speed', NULL, 'Top-End Speed', 'Short maximal-velocity fly zone after a build-up -- isolates true top-end speed rather than acceleration, matching the reference program''s peak-week testing standard.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Build up over 15-20m to reach full speed, then sprint maximally through a marked 20m fly zone, timing only the fly portion.', 'Relaxed, high-speed running through the fly zone -- tension in the face or shoulders means you''re forcing it.', 'Do not overstride reaching for extra distance as speed rises; stay tall and let the legs cycle underneath you.', 15, NULL::text[], NULL::text[], 'advanced', 1, 5, NULL::integer, true, true),
  ('First-Step Drill (Varied Stances)', 'first-step-drill-varied-stances', 'Speed', NULL, 'Acceleration', 'Short acceleration bursts started from multiple different stances (2-point, 3-point, lateral, backpedal) -- trains the first-step reaction from every position a flag football play might start from.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Start each rep from a different stance (standing, staggered, lateral-facing, or backpedaling) and explode into a short sprint on a signal.', 'A sharp, reactive first step regardless of starting position -- each stance should feel equally explosive.', 'Do not anticipate the signal by false-starting; wait for the true cue each rep.', 9, NULL::text[], NULL::text[], 'moderate', 1, 10, NULL::integer, true, false),
  ('Hill Sprint (Force Focus)', 'hill-sprint-force-focus', 'Speed', NULL, 'Acceleration', 'Maximal-effort hill sprint -- the reference program''s primary lower-risk force-development sprint variant, using the incline to overload horizontal force production.', NULL, '{"Hill"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Distance"}'::text[], 'Sprint maximally up a moderate incline, driving hard through the ground with an aggressive forward lean and knee drive, then walk back down as recovery.', 'A powerful, driving push through the ground on every step -- the hill should make full-speed sprinting feel like pushing against real resistance.', 'Do not choose too steep a hill that forces a choppy, unathletic stride; the incline should be moderate.', 13, NULL::text[], NULL::text[], 'advanced', 1, 6, NULL::integer, true, true),
  ('Resisted Sprint (Partner Manual)', 'resisted-sprint-partner-manual', 'Speed', NULL, 'Acceleration', 'Partner-applied manual resistance sprint using a hand-held band -- builds horizontal force application during the acceleration phase without equipment.', NULL, '{"Resistance Band","Partner"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Distance"}'::text[], 'A partner holds one end of a band looped around your waist and provides resistance as you drive forward from a stationary start.', 'A strong forward lean with aggressive ground drive against the resistance, similar to pushing a sled.', 'Do not let the partner apply so much resistance that mechanics break down into a stiff, upright stagger.', 11, NULL::text[], NULL::text[], 'moderate', 1, 6, NULL::integer, true, false)
) AS v (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.name = v.name AND e.category = v.category
);
