-- These 3 tables exist live but were never tracked by any migration (not in
-- supabase_migrations.schema_migrations, not referenced in any migration's
-- statements) -- applied directly outside the CLI flow at some point, with no
-- record of the original DDL. Reconstructed from live information_schema /
-- pg_constraint / pg_indexes / pg_policies introspection (2026-07-01 audit),
-- same technique as the 2026-06-25 doc clean-slate reconstruction. This is a
-- backfill for version control, not a re-application -- CREATE TABLE IF NOT
-- EXISTS / DROP POLICY IF EXISTS make it a no-op against the live project.

-- ============================================================================
-- sponsors
-- ============================================================================
CREATE TABLE IF NOT EXISTS sponsors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    logo_url TEXT NOT NULL,
    website_url TEXT,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE sponsors ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read active sponsors" ON sponsors;
CREATE POLICY "Anyone can read active sponsors"
ON sponsors FOR SELECT
TO public
USING (is_active = true);

-- ============================================================================
-- video_bookmarks
-- ============================================================================
CREATE TABLE IF NOT EXISTS video_bookmarks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    video_id TEXT NOT NULL,
    video_title TEXT NOT NULL,
    video_url TEXT NOT NULL,
    creator_username TEXT,
    saved_at TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT,
    UNIQUE (user_id, video_id)
);

ALTER TABLE video_bookmarks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own bookmarks" ON video_bookmarks;
CREATE POLICY "Users can view own bookmarks"
ON video_bookmarks FOR SELECT
TO public
USING (user_id = (SELECT auth.uid()));

DROP POLICY IF EXISTS "Users can create own bookmarks" ON video_bookmarks;
CREATE POLICY "Users can create own bookmarks"
ON video_bookmarks FOR INSERT
TO public
WITH CHECK (user_id = (SELECT auth.uid()));

DROP POLICY IF EXISTS "Users can update own bookmarks" ON video_bookmarks;
CREATE POLICY "Users can update own bookmarks"
ON video_bookmarks FOR UPDATE
TO public
USING (user_id = (SELECT auth.uid()));

DROP POLICY IF EXISTS "Users can delete own bookmarks" ON video_bookmarks;
CREATE POLICY "Users can delete own bookmarks"
ON video_bookmarks FOR DELETE
TO public
USING (user_id = (SELECT auth.uid()));

-- ============================================================================
-- weekly_training_analysis
-- ============================================================================
CREATE TABLE IF NOT EXISTS weekly_training_analysis (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    week_start_date DATE NOT NULL,
    week_end_date DATE NOT NULL,
    total_training_sessions INTEGER,
    total_training_duration_minutes INTEGER,
    total_training_load INTEGER,
    daily_loads INTEGER[],
    mean_daily_load NUMERIC(7, 2),
    standard_deviation NUMERIC(7, 2),
    training_monotony NUMERIC(4, 2),
    monotony_interpretation VARCHAR(30),
    training_strain NUMERIC(8, 2),
    strain_interpretation VARCHAR(30),
    monotony_injury_risk NUMERIC(3, 2),
    strain_injury_risk NUMERIC(3, 2),
    load_distribution_quality NUMERIC(3, 2),
    rest_days_count INTEGER,
    consecutive_high_load_days INTEGER,
    load_change_from_previous_week NUMERIC(5, 2),
    load_progression_safety VARCHAR(30),
    recommended_rest_days INTEGER,
    recommended_load_variation NUMERIC(3, 2),
    next_week_load_target INTEGER,
    high_load_days TEXT[],
    recovery_day_adequacy NUMERIC(3, 2),
    exceeds_monotony_threshold BOOLEAN,
    exceeds_strain_threshold BOOLEAN,
    weeks_consecutive_high_monotony INTEGER,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE (user_id, week_start_date)
);

ALTER TABLE weekly_training_analysis ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own weekly analysis" ON weekly_training_analysis;
CREATE POLICY "Users can view own weekly analysis"
ON weekly_training_analysis FOR SELECT
TO public
USING (user_id = (SELECT auth.uid()));
