-- strength: 20 new exercise-catalog rows.
-- Source: Ljubljana Frogs 2026 Summer Pre-Season Program (physio-approved
-- 9-week block) + standard flag-football S&C/technical drill taxonomy.
-- Idempotent on (name, category) via WHERE NOT EXISTS (no unique constraint
-- exists on exercises besides the id PK).

INSERT INTO public.exercises (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.* FROM (VALUES
  ('Push-Up (Tempo Eccentric)', 'pushup-tempo-eccentric', 'Strength', NULL, 'Push', 'Standard push-up with a controlled 3-second lowering phase -- the reference program''s primary bodyweight chest/tricep mass-retention movement.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Lower over a full 3-second count with elbows at roughly 45 degrees from the body, then press back up with control.', 'Deep, sustained chest and tricep tension through the slow lowering phase, not just at the bottom.', 'Do not let the hips sag or pike; keep a straight line from heels to head throughout.', 10, NULL::text[], NULL::text[], 'moderate', 4, 13, NULL::integer, true, false),
  ('Push-Up (Feet Elevated)', 'pushup-feet-elevated', 'Strength', NULL, 'Push', 'Push-up with feet raised on a bench or step -- increases loading on the chest and shoulders using only bodyweight.', NULL, '{"Bench or Step"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Place feet on a raised surface and perform push-ups with the same tempo and control as the standard version.', 'Noticeably more shoulder and upper-chest demand than a flat push-up.', 'Do not let the lower back arch to compensate for the added lean angle.', 12, NULL::text[], NULL::text[], 'moderate', 4, 12, NULL::integer, true, false),
  ('Push-Up (Explosive / Clap)', 'pushup-explosive-clap', 'Strength', NULL, 'Push', 'Maximal-effort push-up that leaves the ground -- upper-body plyometric power, the reference program''s peak-intensification chest movement.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Lower under control, then press explosively enough that the hands leave the ground, landing softly with elbows slightly bent to absorb.', 'A sharp, explosive push followed by a soft, controlled landing.', 'Do not let the elbows lock out stiffly on landing; absorb through a slight bend every rep.', 14, NULL::text[], NULL::text[], 'advanced', 5, 6, NULL::integer, true, true),
  ('Pike Push-Up', 'pike-pushup', 'Strength', NULL, 'Push', 'Push-up performed in a pike (hips high) position -- shoulder-dominant press substituting for overhead pressing without equipment.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Start in a downward-dog-like pike position with hips high, then bend the elbows to lower the head toward the ground and press back up.', 'Shoulder-focused pressing tension, similar to an overhead press but angled through the pike.', 'Do not let the hips drop toward a flat push-up position; keep them elevated throughout.', 10, NULL::text[], NULL::text[], 'moderate', 3, 9, NULL::integer, true, false),
  ('Inverted Row', 'inverted-row', 'Strength', NULL, 'Pull', 'Bodyweight horizontal row under a bar, table edge, or suspension strap -- the main bodyweight back-strength counterbalance to all the pressing work.', NULL, '{"Bar or Suspension Strap"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Lie under a fixed bar or hold suspension straps, body straight, and pull the chest up to the bar/hands, squeezing the shoulder blades together.', 'A strong squeeze across the upper back and rear shoulders at the top of every rep.', 'Do not let the hips sag or lead with the chin instead of the chest.', 11, NULL::text[], NULL::text[], 'moderate', 4, 11, NULL::integer, true, false),
  ('Band Row (Bent-Over)', 'band-row-bent-over', 'Strength', NULL, 'Pull', 'Bent-over rowing motion against band resistance -- portable back-strength work for outdoor bodyweight/band training.', NULL, '{"Resistance Band"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Anchor the band low, hinge forward at the hips with a flat back, and pull the band to the ribs, squeezing the shoulder blades together.', 'A strong contraction across the mid-back on every pull, with the torso staying still.', 'Do not let the torso rock to help the pull or the lower back round during the hinge.', 10, NULL::text[], NULL::text[], 'moderate', 4, 12, NULL::integer, true, false),
  ('Band Face Pull', 'band-face-pull', 'Strength', NULL, 'Pull', 'High-elbow band pull to face height -- rear-shoulder and upper-back health work that protects the throwing/tackling shoulder.', NULL, '{"Resistance Band"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Anchor the band at chest-to-face height, pull toward the face with elbows high and out to the sides, squeezing the shoulder blades together at the finish.', 'A strong squeeze in the rear shoulders and upper back, not the arms.', 'Do not let the elbows drop low or the shoulders shrug up toward the ears.', 6, NULL::text[], NULL::text[], 'beginner', 3, 15, NULL::integer, true, false),
  ('Band Face Pull + External Rotation', 'band-face-pull-external-rotation', 'Strength', NULL, 'Pull', 'Face pull finished with an external rotation at the top -- adds rotator-cuff work on top of the standard face pull for shoulder resilience.', NULL, '{"Resistance Band"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Perform a band face pull, and at the top, rotate the forearms upward (external rotation) before returning and repeating.', 'The same upper-back squeeze as a face pull, plus a distinct rotator-cuff engagement on the rotation.', 'Do not use momentum to whip the rotation; keep it slow and controlled.', 6, NULL::text[], NULL::text[], 'moderate', 3, 12, NULL::integer, true, false),
  ('Jump Squat (Band-Loaded)', 'jump-squat-band-loaded', 'Strength', NULL, 'Squat', 'Explosive squat with band resistance added -- the reference program''s primary explosive-intent lower-body movement once bodyweight alone is insufficient stimulus.', NULL, '{"Resistance Band"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Stand on a band anchored under the feet, held at the shoulders. Squat down and explode upward as fast as possible against the band tension.', 'Maximal explosive intent on every rep -- the band should make the top of the jump noticeably harder.', 'Do not let form break down chasing speed; if the band pulls you off balance, reduce tension.', 13, NULL::text[], NULL::text[], 'advanced', 5, 4, NULL::integer, true, true),
  ('Pistol Squat (Eccentric Control)', 'pistol-squat-eccentric-control', 'Strength', NULL, 'Unilateral', 'Single-leg squat to full depth with control -- the most advanced unilateral leg-strength progression, matching the reference program''s Week 6 peak-force phase.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Balance on one leg with the other extended forward, lower under control as deep as mobility allows, then drive back up. Use a light support if needed while building the pattern.', 'Deep, controlled single-leg quad and glute tension throughout the entire range.', 'Do not let the standing knee cave inward or rush the descent; regress to a supported or box version if control breaks down.', 14, NULL::text[], NULL::text[], 'advanced', 4, 5, NULL::integer, true, true),
  ('Squat to Stand (Mobility-Strength)', 'squat-to-stand', 'Strength', NULL, 'Squat', 'Deep squat combined with a hamstring stretch to standing -- a warm-up-to-strength bridge movement used to open the hips and hamstrings under light load.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Squat down and hold the ankles or shins, then straighten the legs to a hamstring stretch while keeping hands on the ground, then return to the squat. Repeat.', 'Alternating deep hip/ankle opening in the squat and a hamstring stretch on the straightening.', 'Do not round the upper back excessively; keep the chest reasonably tall throughout.', 3, NULL::text[], NULL::text[], 'beginner', 2, 8, NULL::integer, true, false),
  ('Hanging Leg Raise', 'hanging-leg-raise', 'Strength', NULL, 'Core Flexion', 'Hanging knee/leg raise from a bar -- direct lower-abdominal and hip-flexor strength work.', NULL, '{"Bar"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Hang from a bar with a firm grip and raise the knees (or straight legs, advanced) toward the chest under control, then lower without swinging.', 'Direct lower-ab tension on the raise, controlled the whole way down.', 'Do not use body swing/momentum to throw the legs up; if swinging starts, reduce reps.', 8, NULL::text[], NULL::text[], 'moderate', 3, 10, NULL::integer, true, false),
  ('Floor Leg Raise', 'floor-leg-raise', 'Strength', NULL, 'Core Flexion', 'Lying leg raise on the floor -- accessible lower-ab and hip-flexor strength work for anyone without a bar.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Lie on your back with legs straight, lower back pressed into the floor, and raise both legs to vertical, then lower under control without arching.', 'Steady lower-ab tension throughout, with the lower back staying flat against the ground.', 'Do not let the lower back arch off the floor as the legs lower; stop the range where control is lost.', 6, NULL::text[], NULL::text[], 'beginner', 3, 12, NULL::integer, true, false),
  ('Med-Ball Chest Throw', 'med-ball-chest-throw', 'Strength', NULL, 'Push', 'Explosive chest-pass throw against a wall or to a partner -- upper-body power that substitutes for a bench press in a bodyweight/outdoor setting.', NULL, '{"Medicine Ball"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Hold the ball at the chest and explosively push/throw it forward at a wall or partner, catching the rebound and repeating immediately.', 'A sharp, full-effort push through the chest and arms on every throw.', 'Do not let the throw become a slow push; if it stops being explosive, the set is done.', 9, NULL::text[], NULL::text[], 'moderate', 3, 8, NULL::integer, true, false),
  ('Band Chest Press', 'band-chest-press', 'Strength', NULL, 'Push', 'Standing chest press against band resistance -- a loadable pressing option for building chest/tricep strength beyond bodyweight push-up ceiling.', NULL, '{"Resistance Band"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Anchor the band behind you at chest height, press forward until the arms are extended, then return under control.', 'Steady, even chest and tricep tension through the full press.', 'Do not let the torso lean forward to help the press; keep the core braced and stance stable.', 8, NULL::text[], NULL::text[], 'moderate', 3, 14, NULL::integer, true, false),
  ('Dead Bug', 'dead-bug', 'Strength', NULL, 'Core Anti-Extension', 'Contralateral limb-lowering core drill -- teaches the lower back to stay flat under load, foundational for all standing power work.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Lie on your back, arms reaching up and knees bent at 90 degrees. Slowly lower one arm and the opposite leg toward the floor while keeping the lower back pressed flat, then return and switch.', 'Deep core engagement that should keep the lower back glued to the floor the entire time.', 'Stop the range the moment the lower back starts to arch off the floor.', 4, NULL::text[], NULL::text[], 'beginner', 3, 10, NULL::integer, true, false),
  ('Side Plank with Reach', 'side-plank-with-reach', 'Strength', NULL, 'Core Anti-Rotation', 'Side plank with a rotational arm reach underneath the body -- adds an anti-rotation and thoracic-mobility component to the standard side plank.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Hold a side plank, then thread the top arm underneath the torso in a rotation, and return it to reaching toward the ceiling. Repeat for reps while holding the plank.', 'Obliques working continuously to resist rotation while the reaching arm moves freely.', 'Do not let the hips drop or rotate with the reach; the trunk should stay stable.', 6, NULL::text[], NULL::text[], 'moderate', 3, 8, NULL::integer, true, false),
  ('Single-Arm Band Anti-Rotation Press', 'single-arm-band-anti-rotation-press', 'Strength', NULL, 'Anti-Rotation', 'Single-arm press against band tension pulling from the side -- core anti-rotation strength directly transferable to absorbing contact off-balance.', NULL, '{"Resistance Band"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Stand side-on to a band anchor at chest height, and press the band straight out in front of the chest with one arm, resisting the pull that tries to rotate the torso.', 'The core, especially the obliques, working hard to prevent the torso from turning toward the anchor.', 'Do not let the hips or shoulders rotate toward the band; if they do, reduce resistance.', 7, NULL::text[], NULL::text[], 'moderate', 3, 10, NULL::integer, true, false),
  ('Glute Bridge (Single-Leg)', 'glute-bridge-single-leg', 'Strength', NULL, 'Hip Extension', 'Single-leg glute bridge -- unilateral posterior-chain activation and strength, a core piece of the daily warm-up activation block.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Lie on your back with one knee bent and foot on the ground, the other leg extended. Drive through the grounded heel to lift the hips, squeezing the glute at the top.', 'A strong, isolated glute squeeze in the working leg at the top of every rep.', 'Do not let the hips rotate or the lower back arch to gain height; keep the pelvis level.', 6, NULL::text[], NULL::text[], 'beginner', 3, 8, NULL::integer, true, false),
  ('Nordic Curl (Band-Assisted)', 'nordic-curl-band-assisted', 'Strength', 'hamstring', 'Hip Hinge', 'Band-assisted Nordic hamstring curl -- an entry-level regression of the full Nordic Curl for athletes not yet ready for the unassisted version.', NULL, '{"Resistance Band"}'::text[], NULL::text[], NULL::uuid[], '{"Sets","Reps"}'::text[], 'Kneel with ankles anchored and a band looped around the torso/chest and anchored in front to assist the lowering. Lower under control as far as strength allows, then use the band to help return.', 'The same deep hamstring loading as the full Nordic Curl, with the band taking some of the load at the hardest point.', 'Do not let the hips pike; if the band assistance isn''t enough to keep good form, add more assistance.', 16, NULL::text[], NULL::text[], 'moderate', 3, 6, NULL::integer, true, false)
) AS v (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.name = v.name AND e.category = v.category
);
