-- agility batch 2: 14 new exercise-catalog rows (combine tests, reactive/lateral agility).
-- Skips L-Drill (3-Cone) -- already present in library under that slug.
-- Idempotent on slug (unique constraint uq_exercises_slug) via WHERE NOT EXISTS.

INSERT INTO public.exercises (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.* FROM (VALUES
  ('5-10-5 Pro Agility Shuttle', '5-10-5-pro-agility-shuttle', 'Agility', NULL, 'Change of Direction', 'Standard combine pro-agility shuttle: 5 yards one way, 10 yards back, 5 yards to finish -- the definitive test of short-area change-of-direction speed.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Start straddling the middle line, sprint 5 yards to one side and touch the line, sprint 10 yards to the far side and touch that line, then sprint 5 yards back through the start.', 'Three sharp, maximal direction changes in quick succession with minimal wasted motion at each touch.', 'Do not round the touches; a hard plant and touch at each line is faster than a wide, lazy turn.', 14, NULL::text[], NULL::text[], 'advanced', 1, 4, NULL::integer, true, true),
  ('W-Drill', 'w-drill', 'Agility', NULL, 'Multi-Directional', 'Zig-zag agility pattern combining forward sprints and lateral shuffles between five cones set in a W shape -- multi-directional conditioning and cutting drill.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Sprint diagonally forward to each cone in the W pattern, shuffling laterally between direction changes, moving through all five cones continuously.', 'Continuous diagonal cutting with the hips staying low through each transition.', 'Do not stand tall between cuts; stay in an athletic position the whole way through.', 12, NULL::text[], NULL::text[], 'advanced', 1, 3, NULL::integer, true, false),
  ('Diamond Drill', 'diamond-drill', 'Agility', NULL, 'Multi-Directional', 'Four-cone diamond pattern combining a sprint, two lateral shuffles, and a backpedal -- a compact multi-directional conditioning drill.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Sprint forward to the first cone, shuffle laterally to the second, shuffle laterally to the third, and backpedal to the start, moving continuously around the diamond.', 'A smooth flow between forward, lateral, and backward movement qualities.', 'Do not cross the feet during the lateral shuffle segments.', 11, NULL::text[], NULL::text[], 'advanced', 1, 3, NULL::integer, true, false),
  ('Numbers Reaction Drill', 'numbers-reaction-drill', 'Agility', NULL, 'Reactive', 'A partner calls out a number corresponding to a pre-assigned direction, and the athlete reacts instantly -- pure cognitive-reactive agility training.', NULL, '{"Partner","Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Assign each of several cones a number. Start in an athletic stance; when a partner calls a number, sprint immediately to the matching cone.', 'A genuine mental reaction delay followed by an explosive physical response.', 'Do not anticipate or guess the call before it happens; wait for the true cue.', 9, NULL::text[], NULL::text[], 'moderate', 1, 10, NULL::integer, true, false),
  ('Color-Cone Reaction Drill', 'color-cone-reaction-drill', 'Agility', NULL, 'Reactive', 'Colored cones assigned to different directions, called out by a partner -- a variation of the numbers drill for reactive agility training.', NULL, '{"Partner","Colored Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Set up cones of different colors in different directions. React to a called color by sprinting immediately to the matching cone.', 'A quick visual-to-physical reaction with an explosive first step toward the called cone.', 'Do not turn the head to look for the cone before moving; the first step should begin the instant the call is heard.', 9, NULL::text[], NULL::text[], 'moderate', 1, 10, NULL::integer, true, false),
  ('Zig-Zag Bound', 'zig-zag-bound', 'Agility', NULL, 'Change of Direction', 'Continuous bounding in a zig-zag pattern -- combines horizontal plyometric power with repeated change-of-direction demand.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Bound diagonally from one leg to the other in a zig-zag pattern through a line of cones, covering distance with each bound.', 'A powerful, springy bound-to-bound rhythm with direction changing on every landing.', 'Do not let the landings become flat-footed; stay reactive and springy through each bound.', 14, NULL::text[], NULL::text[], 'advanced', 3, 6, NULL::integer, true, true),
  ('Lateral Bound Series', 'lateral-bound-series', 'Agility', NULL, 'Lateral', 'Consecutive single-leg lateral bounds -- frontal-plane power and stability for cutting and coverage-shuffle mechanics.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Bound sideways off one leg, landing on the opposite leg with control, then immediately bound back the other way, continuing for the prescribed reps.', 'A strong lateral push and a stable, controlled landing on each bound.', 'Do not let the landing knee cave inward; if it does, reduce the bound distance.', 12, NULL::text[], NULL::text[], 'advanced', 3, 8, NULL::integer, true, false),
  ('Single-Leg Lateral Hop to Stick', 'single-leg-lateral-hop-to-stick', 'Agility', NULL, 'Lateral', 'Single lateral hop landing on the same leg with a held stick -- isolates frontal-plane landing control, a precursor to the full Lateral Bound Series.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Hop sideways a short distance on one leg, landing on the same leg, and hold the landing position for a full second before resetting.', 'A controlled, stable landing with the hip and knee absorbing force cleanly.', 'Do not let the knee cave inward on landing; regress the hop distance if it does.', 9, NULL::text[], NULL::text[], 'moderate', 3, 6, NULL::integer, true, false),
  ('Continuous Lateral Bound (Skater Hop)', 'continuous-lateral-bound-skater-hop', 'Agility', NULL, 'Lateral', 'Continuous side-to-side single-leg bounding -- the classic ''skater hop'' reactive lateral power drill.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Bound continuously from one leg to the other side to side, minimizing ground contact time on each landing.', 'A fast, reactive, springy side-to-side rhythm.', 'Do not let ground contact time lengthen into a slow series of separate hops; keep the rhythm continuous.', 13, NULL::text[], NULL::text[], 'advanced', 3, 10, NULL::integer, true, true),
  ('Cone Slalom Sprint', 'cone-slalom-sprint', 'Agility', NULL, 'Change of Direction', 'Fast weaving sprint through closely spaced cones -- a tighter, faster version of the standard cone weave for advanced change-of-direction training.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Sprint through a tight line of closely spaced cones, weaving with small, quick cuts rather than wide arcs.', 'Rapid, small direction changes maintained at speed.', 'Do not widen the path to go faster through the cones; the value is in the tight, controlled weaving.', 12, NULL::text[], NULL::text[], 'advanced', 1, 4, NULL::integer, true, false),
  ('Read-and-React Partner Drill', 'read-and-react-partner-drill', 'Agility', NULL, 'Reactive', 'Partner unpredictably points or signals a direction mid-sprint, and the athlete redirects instantly -- open-ended reactive agility training.', NULL, '{"Partner"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Jog or sprint toward a partner who unpredictably signals a direction (left, right, stop); react and redirect immediately on the cue.', 'A genuine cognitive processing delay followed by an explosive, correct redirect.', 'Do not guess the direction in advance; commit only once the cue is given.', 10, NULL::text[], NULL::text[], 'advanced', 1, 10, NULL::integer, true, false),
  ('Quarter-Eagle Turn Drill', 'quarter-eagle-turn-drill', 'Agility', NULL, 'Change of Direction', 'Sprint with a 90-degree hip-turn direction change without stopping -- trains the specific hip-turn mechanic used transitioning from a route or coverage angle.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Sprint forward, and at the marked cone, rotate the hips 90 degrees while maintaining speed, continuing to sprint in the new direction.', 'A fluid hip rotation that preserves speed through the direction change rather than a full stop-and-restart.', 'Do not decelerate to a near-stop to make the turn; the turn should be executed while still moving.', 11, NULL::text[], NULL::text[], 'advanced', 1, 6, NULL::integer, true, false),
  ('Speed Ladder -- Two In Sprint Out', 'speed-ladder-two-in-sprint-out', 'Agility', NULL, 'Footwork', 'Ladder drill stepping two feet into each box before sprinting out the final segment -- combines foot-speed coordination with an acceleration finish.', NULL, '{"Agility Ladder","Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Step both feet into each ladder box moving forward, and upon exiting the last box, immediately sprint through a marked finish line.', 'A quick, coordinated ladder rhythm transitioning into an explosive sprint finish.', 'Do not let the ladder portion slow down in anticipation of the sprint; treat the transition as seamless.', 10, NULL::text[], NULL::text[], 'moderate', 3, 1, NULL::integer, true, false),
  ('Reactive Cone Touch Drill', 'reactive-cone-touch-drill', 'Agility', NULL, 'Reactive', 'Athlete reacts to a partner pointing at one of several cones arranged around them and sprints to touch it -- 360-degree reactive agility.', NULL, '{"Partner","Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Stand in the middle of cones arranged in a circle or semicircle. React to a partner pointing at one and sprint to touch it, then return to center.', 'A quick reactive burst in a genuinely unpredictable direction.', 'Do not turn to face the cone before moving; react and move simultaneously.', 10, NULL::text[], NULL::text[], 'advanced', 1, 8, NULL::integer, true, false)
) AS v (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.slug = v.slug
);
