-- speed batch 2: 20 new exercise-catalog rows (shuttle conditioning, combine tests, low-impact conditioning).
-- Idempotent on (name, category) via WHERE NOT EXISTS.

INSERT INTO public.exercises (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.* FROM (VALUES
  ('Suicide Runs (Shuttle Ladder)', 'suicide-runs-shuttle-ladder', 'Speed', NULL, 'Mixed Conditioning', 'Ascending-and-descending shuttle sprint touching progressively further lines -- classic conditioning drill building repeated acceleration/deceleration capacity.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Sprint to the first line and back, then a further line and back, continuing to the farthest line, touching the ground or line at each turn.', 'Escalating fatigue with each successive shuttle, testing the ability to maintain sprint quality under accumulating fatigue.', 'Do not round the turns; touch the line and drive back explosively each time.', 20, NULL::text[], NULL::text[], 'advanced', 1, 1, NULL::integer, true, true),
  ('300-Yard Shuttle', '300-yard-shuttle', 'Speed', NULL, 'Mixed Conditioning', 'Timed 25-yard shuttle repeated 12 times (300 total yards) -- a classic combine-style conditioning test of repeated-sprint capacity.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Sprint 25 yards down and back six times continuously (300 total yards), touching the line at each turn, timed for the full effort.', 'Severe accumulating fatigue in the second half -- pacing and turn technique determine the final time as much as raw speed.', 'Do not round the turns to save effort; a fast, clean turn is faster than a lazy wide one even when tired.', 24, NULL::text[], NULL::text[], 'advanced', 1, 1, NULL::integer, true, true),
  ('Gasser (Sideline-to-Sideline)', 'gasser-sideline-to-sideline', 'Speed', NULL, 'Mixed Conditioning', 'Full-width field sprint down and back -- simulates the longer sustained sprint efforts occasionally required in flag football transition play.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Sprint the full width of the field, touch the sideline, and sprint back, repeating for the prescribed number of reps with set rest.', 'A long, sustained sprint effort that tests both speed and speed-endurance.', 'Do not let pacing drop off gradually across reps; hold as consistent an effort as possible.', 18, NULL::text[], NULL::text[], 'advanced', 1, 4, NULL::integer, true, true),
  ('Battle Rope Wave', 'battle-rope-wave', 'Speed', NULL, 'Conditioning', 'Alternating heavy rope waves -- upper-body and core conditioning with minimal joint-impact, useful as a lower-impact conditioning option.', NULL, '{"Battle Ropes"}'::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Holding one end of each rope, alternate driving each arm up and down explosively to create continuous waves for the prescribed duration.', 'A demanding shoulder, arm, and core burn that builds quickly.', 'Do not let the waves get so small they lose the wave pattern; keep consistent amplitude.', 10, NULL::text[], NULL::text[], 'moderate', 4, NULL::integer, 30, true, false),
  ('Jump Rope (Basic Bounce)', 'jump-rope-basic-bounce', 'Speed', NULL, 'Conditioning', 'Continuous basic jump-rope bouncing -- low-impact conditioning that also reinforces the reactive ankle stiffness trained in the pogo hop series.', NULL, '{"Jump Rope"}'::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Jump continuously with a small, quick bounce, turning the rope with the wrists rather than the whole arm.', 'A light, rhythmic bounce through the ankles and calves that should feel easy to sustain.', 'Do not jump excessively high; a small, efficient bounce is more sustainable and more useful.', 6, NULL::text[], NULL::text[], 'beginner', 3, NULL::integer, 60, true, false),
  ('Jump Rope (Double Under)', 'jump-rope-double-under', 'Speed', NULL, 'Conditioning', 'Jump-rope variation passing the rope twice per jump -- a higher-intensity progression of the basic bounce demanding more power and rhythm.', NULL, '{"Jump Rope"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Jump slightly higher than a basic bounce and whip the rope fast enough to pass it under the feet twice before landing.', 'A quick, powerful jump paired with fast wrist-driven rope speed.', 'Do not jump from the knees; the extra height should come from a quick ankle-driven pop.', 9, NULL::text[], NULL::text[], 'advanced', 3, 20, NULL::integer, true, false),
  ('Stair Sprint', 'stair-sprint', 'Speed', NULL, 'Acceleration', 'Sprinting up a flight of stairs -- a joint-friendly, high-force way to build acceleration power and leg strength using an incline.', NULL, '{"Stairs"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Sprint up a flight of stairs as fast as possible, driving hard through each step, then walk down as recovery.', 'A powerful, driving push through the legs on every step, breathing hard by the top.', 'Do not take two steps at a time if it compromises footing; a fast, controlled single-step cadence is safer and often faster.', 15, NULL::text[], NULL::text[], 'advanced', 1, 6, NULL::integer, true, true),
  ('Tempo Run (70 Percent Intervals)', 'tempo-run-70-percent', 'Speed', NULL, 'Aerobic', 'Moderate-effort interval running at a controlled 70 percent pace -- builds aerobic capacity and recovery-between-sprints ability without the CNS cost of maximal sprinting.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Distance"}'::text[], 'Run the prescribed distance at roughly 70 percent of maximal speed, with full recovery walked between reps.', 'A controlled, moderately hard effort -- noticeably faster than an easy jog but well short of a maximal sprint.', 'Do not let the pace creep up toward a near-maximal effort; the point of tempo work is the controlled sub-maximal intensity.', 9, NULL::text[], NULL::text[], 'moderate', 1, 6, NULL::integer, true, false),
  ('Bike Sprint Interval', 'bike-sprint-interval', 'Speed', NULL, 'Conditioning', 'Maximal-effort stationary bike sprints -- a joint-friendly alternative for building repeated-sprint conditioning during high-fatigue or return-to-play phases.', NULL, '{"Stationary Bike"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Pedal at maximal effort against resistance for the prescribed short interval, then recover at an easy pace before the next rep.', 'A maximal, breathless leg effort during the sprint interval with the heart rate climbing quickly.', 'Do not let the resistance be so low that the legs spin out without real force; set enough resistance to feel real load.', 14, NULL::text[], NULL::text[], 'advanced', 1, 8, NULL::integer, true, true),
  ('Row Erg Sprint Interval', 'row-erg-sprint-interval', 'Speed', NULL, 'Conditioning', 'Maximal-effort rowing machine sprints -- total-body, low-impact conditioning that also reinforces posterior-chain and pulling strength endurance.', NULL, '{"Rowing Machine"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Row at maximal effort for the prescribed short interval, driving with the legs first, then the back, then the arms, and recover at an easy pace before the next rep.', 'A demanding, total-body maximal effort with the legs doing most of the work on each stroke.', 'Do not row with the arms and back before the legs finish driving; the leg drive must come first each stroke.', 14, NULL::text[], NULL::text[], 'advanced', 1, 8, NULL::integer, true, true),
  ('10-20-30 Sprint Ladder', '10-20-30-sprint-ladder', 'Speed', NULL, 'Acceleration', 'Ascending sprint distances of 10, 20, and 30 meters with full recovery between -- builds acceleration across a range of distances in one structured set.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Sprint 10 meters at full effort, rest fully, then sprint 20 meters at full effort, rest fully, then sprint 30 meters at full effort.', 'Each sprint should feel fully fresh and maximal -- the recovery between reps should fully restore effort quality.', 'Do not shorten the rest between distances; each rep should start from a fully recovered state.', 12, NULL::text[], NULL::text[], 'moderate', 2, 3, NULL::integer, true, false),
  ('Ascending Sprint Ladder (5-10-15-20m)', 'ascending-sprint-ladder-5-10-15-20', 'Speed', NULL, 'Acceleration', 'Four progressively longer maximal sprints -- similar structure to the 10-20-30 ladder with finer distance increments for early-acceleration emphasis.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Sprint 5 meters at full effort with full recovery, then 10, then 15, then 20 meters, resting fully between each.', 'A sharp, maximal first-step effort on every rep regardless of the distance.', 'Do not let the shorter reps become sub-maximal warm-ups; every distance should be run at full effort.', 11, NULL::text[], NULL::text[], 'moderate', 2, 4, NULL::integer, true, false),
  ('Wave Sprint (Accel-Decel-Accel)', 'wave-sprint-accel-decel-accel', 'Speed', NULL, 'Mixed Conditioning', 'Sprint that accelerates, decelerates to a jog, then re-accelerates -- rehearses the stop-start rhythm of a live flag-football possession within a single rep.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Accelerate to full sprint for a short distance, decelerate to a jog for a few steps, then re-accelerate to full sprint again for a second segment.', 'Two distinct maximal accelerations within one continuous rep, separated by a brief controlled deceleration.', 'Do not let the middle jog segment become a full stop; keep it a continuous jog before re-accelerating.', 13, NULL::text[], NULL::text[], 'advanced', 1, 6, NULL::integer, true, false),
  ('Partner-Chase Sprint', 'partner-chase-sprint', 'Speed', NULL, 'Acceleration', 'Sprint chasing a partner who starts with a head-start gap -- competitive, game-realistic pursuit sprinting.', NULL, '{"Partner"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'A partner starts a short distance ahead and sprints away; chase and try to close the gap or catch them before the finish line.', 'A maximal, competitive sprint effort with urgency to close the gap.', 'Do not lunge or dive to close the gap at the finish; stay under control through the whole sprint.', 13, NULL::text[], NULL::text[], 'moderate', 1, 6, NULL::integer, true, false),
  ('Curve Sprint (Field Arc)', 'curve-sprint-field-arc', 'Speed', NULL, 'Acceleration', 'Sprinting along a curved path rather than a straight line -- trains the lean and lateral force application used chasing an angled route or pursuit line.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Sprint along a gentle curved path marked by cones, leaning slightly into the curve and adjusting stride to maintain speed through the arc.', 'A subtle inward lean with the outside leg applying extra lateral force through the curve.', 'Do not lean so hard into the curve that balance is lost; the lean should be subtle and controlled.', 11, NULL::text[], NULL::text[], 'moderate', 1, 5, NULL::integer, true, false),
  ('Backward Run Conditioning', 'backward-run-conditioning', 'Speed', NULL, 'Conditioning', 'Sustained backward running -- builds quad-eccentric conditioning and reinforces backpedal endurance for coverage positions.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Run backward continuously at a moderate pace for the prescribed distance or duration, staying low and looking over the shoulder periodically to check space.', 'A distinct quad burn different from forward running, with the core working to stabilize.', 'Do not stand upright while running backward; stay in an athletic, low position throughout.', 9, NULL::text[], NULL::text[], 'moderate', 3, 1, NULL::integer, true, false),
  ('Lateral Shuffle Conditioning Circuit', 'lateral-shuffle-conditioning-circuit', 'Speed', NULL, 'Conditioning', 'Repeated lateral shuffle intervals across a marked width -- conditioning for the frontal-plane movement demand of coverage and defensive positions.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Shuffle laterally between two markers continuously for the prescribed duration, staying low and avoiding crossing the feet.', 'A demanding hip and glute burn that builds quickly with continuous lateral movement.', 'Do not let the shuffle rise up tall as fatigue sets in; keep the athletic stance throughout.', 12, NULL::text[], NULL::text[], 'moderate', 3, NULL::integer, 30, true, false),
  ('Complex Conditioning Circuit (Sled + Sprint)', 'complex-conditioning-circuit-sled-sprint', 'Speed', NULL, 'Mixed Conditioning', 'Sled push immediately followed by a sprint -- combines maximal-force and maximal-velocity demands back to back, a high-value combination for in-season conditioning.', NULL, '{"Sled","Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps"}'::text[], 'Push the sled for a short distance at full effort, then immediately sprint an additional distance at full speed.', 'Heavy legs transitioning into a sprint -- the sprint segment will feel noticeably harder than a fresh sprint.', 'Do not pause between the sled push and the sprint; the transition should be immediate.', 19, NULL::text[], NULL::text[], 'advanced', 1, 5, NULL::integer, true, true),
  ('Broad Jump Series for Distance', 'broad-jump-series-distance', 'Speed', NULL, 'Horizontal', 'Consecutive maximal broad jumps for cumulative distance -- combines power output with repeated-effort conditioning.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Distance","Reps"}'::text[], 'Perform a series of consecutive maximal broad jumps, resetting balance briefly between each before jumping again.', 'A demanding combination of maximal power output and accumulating leg fatigue across the series.', 'Do not sacrifice landing control for extra distance as fatigue builds; stop the series if landings degrade.', 15, NULL::text[], NULL::text[], 'advanced', 3, 5, NULL::integer, true, true),
  ('Down-and-Back Shuttle', 'down-and-back-shuttle', 'Speed', NULL, 'Mixed Conditioning', 'Single down-and-back sprint touching a far line -- the simplest building block of shuttle conditioning, useful as a standalone rep or a component of larger shuttle sets.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Sprint to a marked line, touch it, and sprint back to the start as fast as possible.', 'A short, maximal sprint effort with a sharp direction change at the turn.', 'Do not round the turn at the far line; touch it directly and drive back explosively.', 10, NULL::text[], NULL::text[], 'moderate', 1, 6, NULL::integer, true, false)
) AS v (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.name = v.name AND e.category = v.category
);
