-- agility: 14 new exercise-catalog rows.
-- Source: Ljubljana Frogs 2026 Summer Pre-Season Program (physio-approved
-- 9-week block) + standard flag-football S&C/technical drill taxonomy.
-- Idempotent on (name, category) via WHERE NOT EXISTS (no unique constraint
-- exists on exercises besides the id PK).

INSERT INTO public.exercises (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
SELECT v.* FROM (VALUES
  ('Ladder -- Icky Shuffle', 'ladder-icky-shuffle', 'Agility', NULL, 'Footwork', 'Classic two-in, one-out agility-ladder pattern -- foundational foot-speed and coordination drill.', NULL, '{"Agility Ladder"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Step into each ladder box with both feet, then step laterally out with the trailing foot before entering the next box, alternating the lead foot each box.', 'A quick, rhythmic in-in-out pattern with light, fast ground contacts.', 'Do not look down at your feet; keep the eyes up and let the feet find the boxes by feel.', 7, NULL::text[], NULL::text[], 'beginner', 3, 1, NULL::integer, true, false),
  ('Ladder -- In-In-Out-Out', 'ladder-in-in-out-out', 'Agility', NULL, 'Footwork', 'Lateral ladder pattern stepping both feet in, then both feet out, moving sideways down the ladder.', NULL, '{"Agility Ladder"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Facing sideways to the ladder, step both feet into a box, then both feet out to the side of the next box, continuing laterally down the length.', 'A quick lateral rhythm with light, springy ground contacts and the hips staying low and athletic.', 'Do not let the hips rise up tall; stay in an athletic, ready position throughout.', 7, NULL::text[], NULL::text[], 'beginner', 3, 1, NULL::integer, true, false),
  ('Ladder -- Lateral High Knees', 'ladder-lateral-high-knees', 'Agility', NULL, 'Footwork', 'High-knee lateral run through the ladder -- combines foot speed with hip flexion drive for coverage-shuffle mechanics.', NULL, '{"Agility Ladder"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Facing sideways to the ladder, drive the knees high while stepping through each box laterally, one foot per box.', 'A fast, high-knee rhythm with quick ground contacts and the torso staying upright.', 'Do not let the knee drive drop low just to move faster through the ladder; keep the knees high.', 8, NULL::text[], NULL::text[], 'moderate', 3, 1, NULL::integer, true, false),
  ('Ladder -- 1-In 1-Out', 'ladder-1-in-1-out', 'Agility', NULL, 'Footwork', 'Single-foot-per-box ladder pattern moving forward -- a simpler foot-speed progression than the Icky Shuffle, good for early-phase coordination work.', NULL, '{"Agility Ladder"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Step one foot into each box and continue forward, alternating feet, moving straight down the ladder.', 'A quick, even forward rhythm, one light contact per box.', 'Do not let the stride lengthen to skip boxes; keep one foot per box the whole way.', 6, NULL::text[], NULL::text[], 'beginner', 3, 1, NULL::integer, true, false),
  ('Ladder -- Crossover Run', 'ladder-crossover-run', 'Agility', NULL, 'Footwork', 'Lateral crossover-step pattern through the ladder -- builds hip mobility and crossover mechanics used in man coverage and route breaks.', NULL, '{"Agility Ladder"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Facing sideways, cross the trailing foot in front of (or behind) the lead foot into each box, moving laterally down the ladder.', 'A fluid, hip-driven crossover rhythm with the shoulders staying square to the direction of travel where possible.', 'Do not let the shoulders and hips over-rotate away from the direction of travel.', 8, NULL::text[], NULL::text[], 'moderate', 3, 1, NULL::integer, true, false),
  ('Fast Feet Drill (Quick Steps in Place)', 'fast-feet-drill-quick-steps', 'Agility', NULL, 'Footwork', 'Rapid, low-amplitude stepping in place -- builds ground-contact speed and turnover rate without an agility ladder.', NULL, NULL::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Take rapid, small, quick steps in place, staying on the balls of the feet with a low, athletic base, for the prescribed duration.', 'A fast, light turnover through the feet and ankles -- the sound of the contacts should be quick and quiet, not stomping.', 'Do not let the stance rise up tall; stay low and athletic the whole time.', 6, NULL::text[], NULL::text[], 'beginner', 4, NULL::integer, 15, true, false),
  ('45-Degree Cut Off Cone', '45-degree-cut-off-cone', 'Agility', NULL, 'Change of Direction', 'Sprint into a 45-degree cut around a cone -- the exact cutting angle used in most flag-football route breaks and pursuit angles.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Sprint toward the cone, plant the outside foot, and cut sharply at 45 degrees, accelerating away in the new direction.', 'A firm plant and push off the outside foot with minimal speed lost through the cut.', 'Do not let the plant foot roll outward or round the cut into a wide, slow arc.', 10, NULL::text[], NULL::text[], 'moderate', 1, 8, NULL::integer, true, false),
  ('Cone Weave / Zig-Zag Cut', 'cone-weave-zigzag-cut', 'Agility', NULL, 'Change of Direction', 'Continuous zig-zag sprint through a line of cones -- repeated-cut conditioning for route running and coverage.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Sprint through a line of staggered cones, cutting sharply at each one to weave through the full line without slowing more than necessary.', 'Continuous quick direction changes with a low center of gravity maintained throughout.', 'Do not stand tall between cuts; stay in an athletic position the entire way through.', 11, NULL::text[], NULL::text[], 'moderate', 1, 4, NULL::integer, true, false),
  ('Star Drill', 'star-drill', 'Agility', NULL, 'Multi-Directional', 'Five-cone star pattern combining sprints, backpedals, and lateral shuffles from a center point -- multi-directional conditioning and reaction drill.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'From a center cone, sprint to each of four surrounding cones and back using the movement called for each direction (sprint forward, backpedal, shuffle left/right), returning to center between each.', 'A demanding mix of forward, backward, and lateral movement in quick succession.', 'Do not skip the return to center between cones; the full pattern is the drill.', 13, NULL::text[], NULL::text[], 'advanced', 1, 2, NULL::integer, true, true),
  ('T-Drill', 't-drill', 'Agility', NULL, 'Multi-Directional', 'T-shaped cone pattern combining a sprint, lateral shuffles, and a backpedal -- a standard combine-style test of multi-directional speed.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Sprint forward to the top cone, shuffle laterally to the left cone, shuffle laterally across to the right cone, shuffle back to center, then backpedal to the start.', 'A continuous flow between forward sprinting, lateral shuffling, and backward movement with minimal wasted motion at each transition.', 'Do not cross your feet during the lateral shuffle sections; stay in a true shuffle.', 12, NULL::text[], NULL::text[], 'advanced', 1, 3, NULL::integer, true, true),
  ('Reactive Ball Drop Sprint', 'reactive-ball-drop-sprint', 'Agility', NULL, 'Reactive', 'Sprint triggered by a partner dropping a ball -- pure reaction-time and first-step training rather than a pre-planned cue.', NULL, '{"Ball","Partner"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Stand a short distance from a partner holding a ball at chest height. When they drop it, sprint to catch it before the second bounce.', 'An explosive, reactive first step the instant the ball is released -- no anticipation, pure reaction.', 'Do not guess or jump early before the ball is actually released; that defeats the reactive purpose.', 9, NULL::text[], NULL::text[], 'moderate', 1, 8, NULL::integer, true, false),
  ('Mirror Drill (Partner Shadow)', 'mirror-drill-partner-shadow', 'Agility', NULL, 'Reactive', 'Partner-led shadowing drill where one athlete mirrors the other''s lateral movements -- reactive agility for man-to-man coverage mechanics.', NULL, '{"Partner"}'::text[], NULL::text[], NULL::uuid[], '{"Duration"}'::text[], 'Face a partner a few meters apart. The leader moves laterally, forward, and backward unpredictably; the follower mirrors every movement as closely as possible.', 'Constant, reactive small adjustments through the feet and hips, staying square to the leader.', 'Do not cross the feet while mirroring laterally; stay in a shuffle-based stance.', 8, NULL::text[], NULL::text[], 'moderate', 3, NULL::integer, 20, true, false),
  ('Lateral Shuffle to Sprint', 'lateral-shuffle-to-sprint', 'Agility', NULL, 'Change of Direction', 'Lateral defensive shuffle transitioned explosively into a forward sprint -- the exact pattern a DB uses breaking on a route.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Reps","Time"}'::text[], 'Shuffle laterally in an athletic defensive stance for a few steps, then plant and drive explosively into a forward sprint on a signal.', 'A smooth, powerful transition from lateral movement directly into forward acceleration with no false steps.', 'Do not stand up out of the shuffle before planting; stay low through the transition.', 10, NULL::text[], NULL::text[], 'moderate', 1, 8, NULL::integer, true, false),
  ('Box Drill (4-Cone Agility)', 'box-drill-4-cone-agility', 'Agility', NULL, 'Multi-Directional', 'Four-cone square pattern combining forward sprints, lateral shuffles, and a backpedal leg -- a standard multi-directional agility assessment and training drill.', NULL, '{"Cones"}'::text[], NULL::text[], NULL::uuid[], '{"Time"}'::text[], 'Sprint forward along one side of the square, shuffle laterally along the second side, backpedal along the third, then shuffle laterally back to the start along the fourth.', 'Four distinct movement qualities linked together with clean transitions at each corner.', 'Do not round the corners; plant and change direction sharply at each cone.', 11, NULL::text[], NULL::text[], 'advanced', 1, 3, NULL::integer, true, true)
) AS v (name, slug, category, subcategory, movement_pattern, description, video_id,
   equipment_needed, position_specific, applicable_positions, metrics_tracked,
   how_text, feel_text, compensation_text, load_contribution_au, muscle_groups,
   target_muscles, difficulty_level, default_sets, default_reps, default_hold_seconds,
   active, is_high_intensity)
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercises e WHERE e.name = v.name AND e.category = v.category
);
