-- Data for table: flag_football_performance_levels
-- Generated: 2025-12-02T20:33:56.637Z

INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (1, 'recreational', 'receiver', '40_yard_dash', '5.20', '5.80', '0.75', 'Beginner flag football players', '["basic_technique","conditioning"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (2, 'recreational', 'receiver', '10_yard_split', '1.80', '1.95', '0.75', 'Learning acceleration', '["start_technique","leg_strength"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (3, 'recreational', 'receiver', '3_cone_drill', '7.50', '8.20', '0.75', 'Basic agility', '["footwork","change_of_direction"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (4, 'recreational', 'receiver', 'vertical_jump', '24.00', '18.00', '0.75', 'Basic jumping ability', '["leg_power","technique"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (5, 'competitive', 'receiver', '40_yard_dash', '4.80', '5.30', '0.88', 'Organized league players', '["speed_technique","power_training"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (6, 'competitive', 'receiver', '10_yard_split', '1.70', '1.85', '0.88', 'Good acceleration', '["explosive_starts","reaction_time"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (7, 'competitive', 'receiver', '3_cone_drill', '7.00', '7.60', '0.88', 'Solid agility', '["cutting_technique","body_control"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (8, 'competitive', 'receiver', 'vertical_jump', '28.00', '21.00', '0.88', 'Good jumping power', '["plyometrics","jump_technique"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (9, 'elite', 'receiver', '40_yard_dash', '4.60', '5.00', '0.97', 'Top flag football players', '["elite_technique","sport_specific"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (10, 'elite', 'receiver', '10_yard_split', '1.60', '1.75', '0.97', 'Elite acceleration', '["max_power","biomechanics"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (11, 'elite', 'receiver', '3_cone_drill', '6.70', '7.20', '0.97', 'Elite agility', '["advanced_cutting","proprioception"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (12, 'elite', 'receiver', 'vertical_jump', '32.00', '24.00', '0.97', 'Elite jumping', '["max_power_development","sport_application"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (13, 'semi_pro', 'receiver', '40_yard_dash', '4.40', '4.80', '1.05', 'Semi-professional level', '["professional_training","genetic_optimization"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (14, 'semi_pro', 'receiver', '10_yard_split', '1.55', '1.70', '1.05', 'Semi-pro acceleration', '["elite_power","technical_mastery"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (15, 'semi_pro', 'receiver', '3_cone_drill', '6.50', '7.00', '1.05', 'Semi-pro agility', '["elite_agility","movement_mastery"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (16, 'semi_pro', 'receiver', 'vertical_jump', '35.00', '27.00', '1.05', 'Semi-pro power', '["maximal_power","genetic_potential"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (17, 'nfl_level', 'receiver', '40_yard_dash', '4.30', '4.60', '1.20', 'NFL combine elite level', '["genetic_gifts","professional_development"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (18, 'nfl_level', 'receiver', '10_yard_split', '1.50', '1.65', '1.20', 'NFL elite burst', '["world_class_power","elite_genetics"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (19, 'nfl_level', 'receiver', '3_cone_drill', '6.50', '6.80', '1.20', 'NFL elite agility', '["world_class_agility","elite_training"]', '2025-08-17T17:32:14.640Z');
INSERT INTO flag_football_performance_levels (id, level_name, position, test_name, male_target, female_target, percentage_of_nfl_elite, description, training_focus, created_at) VALUES (20, 'nfl_level', 'receiver', 'vertical_jump', '38.00', '30.00', '1.20', 'NFL elite power', '["elite_genetics","world_class_training"]', '2025-08-17T17:32:14.640Z');
