-- Data for table: game_day_workflows
-- Generated: 2025-12-02T20:33:56.983Z

INSERT INTO game_day_workflows (id, workflow_name, workflow_type, workflow_steps, estimated_duration_minutes, is_mandatory, created_at) VALUES (1, 'Pre-Game Preparation', 'pre_game', '[{"step":"Equipment Check","duration":15,"responsible":"player"},{"step":"Hydration Assessment","duration":10,"responsible":"medical_staff"},{"step":"Nutrition Review","duration":20,"responsible":"nutritionist"},{"step":"Warm-up Routine","duration":30,"responsible":"coach"},{"step":"Team Meeting","duration":15,"responsible":"head_coach"}]', 90, TRUE, '2025-08-17T20:08:18.797Z');
INSERT INTO game_day_workflows (id, workflow_name, workflow_type, workflow_steps, estimated_duration_minutes, is_mandatory, created_at) VALUES (2, 'During Game Monitoring', 'during_game', '[{"step":"Hydration Check","duration":5,"frequency":"every_quarter","responsible":"medical_staff"},{"step":"Fatigue Assessment","duration":3,"frequency":"every_quarter","responsible":"coach"},{"step":"Performance Review","duration":10,"frequency":"halftime","responsible":"coach"},{"step":"Adjustment Planning","duration":15,"frequency":"halftime","responsible":"coaching_staff"}]', 240, TRUE, '2025-08-17T20:08:18.797Z');
INSERT INTO game_day_workflows (id, workflow_name, workflow_type, workflow_steps, estimated_duration_minutes, is_mandatory, created_at) VALUES (3, 'Post-Game Recovery', 'post_game', '[{"step":"Immediate Hydration","duration":10,"responsible":"medical_staff"},{"step":"Cool Down","duration":20,"responsible":"player"},{"step":"Nutrition Replenishment","duration":30,"responsible":"nutritionist"},{"step":"Recovery Assessment","duration":15,"responsible":"medical_staff"},{"step":"Next Day Planning","duration":20,"responsible":"coach"}]', 95, TRUE, '2025-08-17T20:08:18.797Z');
INSERT INTO game_day_workflows (id, workflow_name, workflow_type, workflow_steps, estimated_duration_minutes, is_mandatory, created_at) VALUES (4, 'Pre-Game Preparation', 'pre_game', '[{"step":"Equipment Check","duration":15,"responsible":"player"},{"step":"Hydration Assessment","duration":10,"responsible":"medical_staff"},{"step":"Nutrition Review","duration":20,"responsible":"nutritionist"},{"step":"Warm-up Routine","duration":30,"responsible":"coach"},{"step":"Team Meeting","duration":15,"responsible":"head_coach"}]', 90, TRUE, '2025-08-17T20:08:35.143Z');
INSERT INTO game_day_workflows (id, workflow_name, workflow_type, workflow_steps, estimated_duration_minutes, is_mandatory, created_at) VALUES (5, 'During Game Monitoring', 'during_game', '[{"step":"Hydration Check","duration":5,"frequency":"every_quarter","responsible":"medical_staff"},{"step":"Fatigue Assessment","duration":3,"frequency":"every_quarter","responsible":"coach"},{"step":"Performance Review","duration":10,"frequency":"halftime","responsible":"coach"},{"step":"Adjustment Planning","duration":15,"frequency":"halftime","responsible":"coaching_staff"}]', 240, TRUE, '2025-08-17T20:08:35.143Z');
INSERT INTO game_day_workflows (id, workflow_name, workflow_type, workflow_steps, estimated_duration_minutes, is_mandatory, created_at) VALUES (6, 'Post-Game Recovery', 'post_game', '[{"step":"Immediate Hydration","duration":10,"responsible":"medical_staff"},{"step":"Cool Down","duration":20,"responsible":"player"},{"step":"Nutrition Replenishment","duration":30,"responsible":"nutritionist"},{"step":"Recovery Assessment","duration":15,"responsible":"medical_staff"},{"step":"Next Day Planning","duration":20,"responsible":"coach"}]', 95, TRUE, '2025-08-17T20:08:35.143Z');
