-- Data for table: sleep_guidelines
-- Generated: 2025-12-02T20:33:57.222Z

INSERT INTO sleep_guidelines (id, evidence_level, recommendation, citation_id, citation_title, citation_authors, citation_journal, citation_year, citation_doi, target_athlete_type, target_age_group, target_position, sleep_phase, implementation_steps, expected_benefits, contraindications, created_at) VALUES (1, 'very_high', 'Athletes should aim for 7-9 hours of sleep per night for optimal performance and recovery', NULL, 'Sleep and Athletic Performance: Impacts on Physical Performance, Mental Performance, Injury Risk and Recovery in Athletes', '["Watson AM"]', 'Sleep Medicine Clinics', 2017, NULL, 'all', NULL, NULL, 'sleep_quality', '["Establish consistent sleep schedule","Create dark, quiet sleep environment","Avoid screens 1 hour before bed"]', '["improved reaction time","better decision making","enhanced recovery","reduced injury risk"]', NULL, '2025-08-17T20:28:03.178Z');
INSERT INTO sleep_guidelines (id, evidence_level, recommendation, citation_id, citation_title, citation_authors, citation_journal, citation_year, citation_doi, target_athlete_type, target_age_group, target_position, sleep_phase, implementation_steps, expected_benefits, contraindications, created_at) VALUES (2, 'high', 'Avoid screen time within 90 minutes of bedtime to improve sleep quality', NULL, 'The effects of mobile phone dependence on athletic performance', '["Zhang L","Wang H"]', 'BMC Sports Science', 2023, NULL, 'all', NULL, NULL, 'bedtime', '["Set phone to do not disturb","Use blue light filters","Establish screen-free bedtime routine"]', '["faster sleep onset","deeper sleep","improved sleep efficiency"]', NULL, '2025-08-17T20:28:03.178Z');
INSERT INTO sleep_guidelines (id, evidence_level, recommendation, citation_id, citation_title, citation_authors, citation_journal, citation_year, citation_doi, target_athlete_type, target_age_group, target_position, sleep_phase, implementation_steps, expected_benefits, contraindications, created_at) VALUES (3, 'high', 'Maintain consistent sleep schedule even on weekends to optimize circadian rhythm', NULL, 'Sleep and Athletic Performance: A Review', '["Halson SL"]', 'Sports Medicine', 2014, NULL, 'elite', NULL, NULL, 'sleep_quality', '["Set consistent bedtime alarm","Avoid sleeping in more than 1 hour","Maintain regular meal times"]', '["better sleep quality","improved daytime alertness","enhanced performance consistency"]', NULL, '2025-08-17T20:28:03.178Z');
INSERT INTO sleep_guidelines (id, evidence_level, recommendation, citation_id, citation_title, citation_authors, citation_journal, citation_year, citation_doi, target_athlete_type, target_age_group, target_position, sleep_phase, implementation_steps, expected_benefits, contraindications, created_at) VALUES (4, 'very_high', 'Athletes should aim for 7-9 hours of sleep per night for optimal performance and recovery', NULL, 'Sleep and Athletic Performance: Impacts on Physical Performance, Mental Performance, Injury Risk and Recovery in Athletes', '["Watson AM"]', 'Sleep Medicine Clinics', 2017, NULL, 'all', NULL, NULL, 'sleep_quality', '["Establish consistent sleep schedule","Create dark, quiet sleep environment","Avoid screens 1 hour before bed"]', '["improved reaction time","better decision making","enhanced recovery","reduced injury risk"]', NULL, '2025-08-17T20:28:32.294Z');
INSERT INTO sleep_guidelines (id, evidence_level, recommendation, citation_id, citation_title, citation_authors, citation_journal, citation_year, citation_doi, target_athlete_type, target_age_group, target_position, sleep_phase, implementation_steps, expected_benefits, contraindications, created_at) VALUES (5, 'high', 'Avoid screen time within 90 minutes of bedtime to improve sleep quality', NULL, 'The effects of mobile phone dependence on athletic performance', '["Zhang L","Wang H"]', 'BMC Sports Science', 2023, NULL, 'all', NULL, NULL, 'bedtime', '["Set phone to do not disturb","Use blue light filters","Establish screen-free bedtime routine"]', '["faster sleep onset","deeper sleep","improved sleep efficiency"]', NULL, '2025-08-17T20:28:32.294Z');
INSERT INTO sleep_guidelines (id, evidence_level, recommendation, citation_id, citation_title, citation_authors, citation_journal, citation_year, citation_doi, target_athlete_type, target_age_group, target_position, sleep_phase, implementation_steps, expected_benefits, contraindications, created_at) VALUES (6, 'high', 'Maintain consistent sleep schedule even on weekends to optimize circadian rhythm', NULL, 'Sleep and Athletic Performance: A Review', '["Halson SL"]', 'Sports Medicine', 2014, NULL, 'elite', NULL, NULL, 'sleep_quality', '["Set consistent bedtime alarm","Avoid sleeping in more than 1 hour","Maintain regular meal times"]', '["better sleep quality","improved daytime alertness","enhanced performance consistency"]', NULL, '2025-08-17T20:28:32.294Z');
